### ISSUE TITLE
New Electricity meter

### ISSUE THREAD

**Issue by Horndrup** [weetmuts/wmbusmeters#126]
Would it be possible to support Landis Gyr E120LiME Electricity meter

https://www.landisgyr.cz/webfoo/wp-content/uploads/product-files/E120LiME_Fact_Sheet_EN_101.pdf

**Comment by weetmuts** [comment]
It does not look like it support wireless mbus...

I think the wireless local communication they mention in this document is standard 2.4GHz Wifi.

There are other landis gyr meters where you install a wireles mbus plugin into the meter.

**Comment by BIBOLV** [comment]
“Li” in “LiME” stands for LonWorks communication and “ME” indicates that it also supports multi-energy (gas/liquid flow, heat energy metering etc.). WMbus is not built in.
