### ISSUE TITLE
Techem Compact V heat meter

### ISSUE THREAD

**Issue by IzeQube** [weetmuts/wmbusmeters#129]
At my home i have a Techem Compact V heat meter. The funny thing is, that I can get decoded values using vario451, but the values are totally wrong.

I also get the warning: (vario451) unexpected meter version 0x45 !

Is there any way to get my heat meter working?

**Comment by weetmuts** [comment]
If you run with --debug and the meter name vario451 and then email me the log, then I can take a look.

**Comment by weetmuts** [comment]
Ping @IzeQube ?

**Comment by IzeQube** [comment]
Sorry for the late reply. After starting it with --debug I could see that the right values were being received, but are then converted what isn't needed for Compact V meter.

I then did a rather hacky fix with a new meter that reads the right values.

I can give you the details when I'm back home later or I can also post a pull request if you want...

**Comment by weetmuts** [comment]
Cool! Either way works!

**Comment by IzeQube** [comment]
I added a PR, took a while because my dev machine died

**Comment by weetmuts** [comment]
Hi @IzeQube ! As you can see I am ready to merge your pull request, but we need an example
telegram for the regression tests. You can email me a telegram if you like and I will anonymize it and add it to the test suite.

**Comment by weetmuts** [comment]
Closing this for now. Thanks for contributing the code @IzeQube !
