### ISSUE TITLE
AMT Integra Water Meter

### ISSUE THREAD

**Issue by righter83** [weetmuts/wmbusmeters#136]
Hi I found this one with a scan:

`Received telegram from: 64404946
          manufacturer: (AMT) INTEGRA METERING
           device type: Water meter`

But this type is not included yet.
Any chance to read it out?

**Comment by weetmuts** [comment]
Sure, run with - - debug to collect a log where we can see one or two raw telegrams. Post the log here.

**Comment by righter83** [comment]
Hi Thanks.
I just saw in the debug that the frame seems to be encrypted.
so you cannot do anything with the raw output before I have the key (Hopefully I got it from my water company)...

**Comment by weetmuts** [comment]
Ok! I will close this issue for now. Please re-open when you have they key!
