### ISSUE TITLE
Getting meter key from preconfigured wmbus->mbus converter.

### ISSUE THREAD

**Issue by Nikodemski2002** [weetmuts/wmbusmeters#145]
Hi. Is there any way I can get the meter key from Kamstrup RF module wM-BUS to M-BUS converter, and M-BUS master hat for RPi or the im871a-USB.

I have written an email to my provider with a question to send me these keys, but I haven't received any answer for four days

I mentioned this problem in the #140 case.

Regards.

**Comment by weetmuts** [comment]
Yes, I need to add wired mbus support to wmbusmeters. Its on my todo-list.
Do you have an mbus -> serial -> usb adapter in mind?

**Comment by Nikodemski2002** [comment]
No. I mean the wireless M-BUS to wired M-BUS Kamstrup donglt. It looks like this:
![wm-bus-dongle-1-1-1-1-1-1-1-1-1-1_25](https://user-images.githubusercontent.com/19575525/89876466-fb068880-dbbe-11ea-874e-943016dc303c.jpg)

And I have two options to read data from it the M-BUS master HAT for RPi or im871a-usb.

**Comment by weetmuts** [comment]
Cool, I have also ordered an M-BUS master HAT for RPi, to add mbus support to wmbusmeters.

**Comment by weetmuts** [comment]
But I will need your help to debug the mbus communication with your particular wmbus-dongle.

**Comment by weetmuts** [comment]
Aha, now I understand your question! I do not know if it is possible to extract the key from the dongle......
I somehow doubt that it is possible....but who knows.

**Comment by merbanan** [comment]
If you open the hardware there might be some clues on how to extract it.

**Comment by Nikodemski2002** [comment]
I read that you can read the AES key from this dongle, but only with Kamstrup USB-tool. But I already received the KEM file and decrypted it with [python script](https://gist.github.com/mbursa/caa654a01b9e804ad44d1f00208a2490).

Thanks for your interest.
Best regards.

**Comment by merbanan** [comment]
@Nikodemski2002 so how did you get them to send you the KEM file? Is the procedure that you need to buy this adapter and then request the KEM file that you then use with the Kamstrup USB-tool?

**Comment by Nikodemski2002** [comment]
@merbanan I just mailed them that I will not use the provided converter and asked them to send me the KEM file for certain water meters. Next time I will just register every water meter on Kastrup customer panel so I will have simple access to encryption keys.
