### ISSUE TITLE
Read interval

### ISSUE THREAD

**Issue by Horndrup** [weetmuts/wmbusmeters#15]
Is it possible to change how often it will read my Multical21

**Comment by weetmuts** [comment]
wmbusmeters just listens to radio telegrams arriving. It does not read the Multical21 per se.
Whatever is in the air, it will decode. :-)

Other meters can be configured to send only during daytime hours, or send more or less data,
to extend the lifetime of the battery. But it seems like the Multical21 is already pre-configured
and designed to broadcast a radio telegram 4 times per minute for 10-16 years, depending
on the meter type. Pretty amazing hardware I must say.
