### ISSUE TITLE
larsenpu - (lansenpu) unexpected meter version 0x0b !

### ISSUE THREAD

**Issue by anonymous-one** [weetmuts/wmbusmeters#151]
Not critical as the readings are coming in no problem, but the log is showing:

```
(lansenpu) unexpected meter version 0x0b !
```

Meter is a Lansen Pulse Counter (optical probe) – (LAN-WMBUS-G2-OOP).

Version / revision as per the sticker as well as printed on the PCB:

Ver 02.
Rev 0B.

**Comment by weetmuts** [comment]
I just added code for driver detection based on mfct,media and version.
I added a 0x0b entry in METER_DETECTION  in src/meters.h
should work now. It would be nice to have a test telegram for this version.
If you have the time, you could email a to me and I will anonymize it and add it to the test suite.

Closing this for now!

Thanks for the bug report!

**Comment by anonymous-one** [comment]
sorry about the slight delay on getting back regarding this. life has kept us busy here.

i will capture a few packets tonight and post them in here, not too concerned about the security etc. packets are unencrypted anyways so 'they' should just sit by the meter and get a dump every 60 seconds.

am i correct in assuming what you want is the output of:

`/usr/bin/rtl_sdr -f 868.95M -s 1.6e6 - | /usr/bin/rtl_wmbus`

for my devices specific id?

i recall reading somewhere (lansens site?) that the packet also includes the battery state. if its a V range or binary good / bad i am unsure... but that would be handy... then again i have my script notify me when a change has not happened in 6 hours which should be fairly fail safe unless we have a super long power outage.

**Comment by weetmuts** [comment]
Yes, rtl_wmbus output is good!
