### ISSUE TITLE
Diehl Hydrus Telegram Lenght

### ISSUE THREAD

**Issue by nickbardom** [weetmuts/wmbusmeters#152]
Hi and congratulations for this great piece of software.

I just installed wmbusmeters and I am trying to read the Hydrus meter. It is a 434Mhz meter.  Wmbusmeters can find it and it has the correct identifier that is printed on the meter. The problem is that wmbusmeters cannot read its data. It shows:
(wmbus) 00: 3e length (62 bytes). Is this length supported?
I tried to use the NOKEY parameter as I dont´t have any key. Do I need a key?  Is there a way to get it working or maybe extract the key? 

I can send a PM with the wmbusmeters debug showing the ID and the complete telegram.

**Comment by weetmuts** [comment]
Great that you can receive 434.47M telegrams! I will update the README to indicate that this i

Thanks, I looked at your telegram and you need a key. 

When you run with --debug you will see something like: AES_CBC_IV
which means that the payload is encrypted.
(wmbus) 0d: 3005 tpl-cfg 0530 (AES_CBC_IV nb=3 cntn=0 ra=0 hc=0 )
Wmbusmeters can detect decryption failure because the decrypted data does not start with 0x2f 0x2f.

**Comment by nickbardom** [comment]
Hi,
Thanks for replying!! Do you know if the length is correct? Any clue of how to get the key? Maybe brute force? Maybe some default keys?
Regards,
Nick


   
 
 
 


Great that you can receive 434.47M telegrams! I will update the README to indicate that this i

Thanks, I looked at your telegram and you need a key.

When you run with --debug you will see something like: AES_CBC_IV
which means that the payload is encrypted.
(wmbus) 0d: 3005 tpl-cfg 0530 (AES_CBC_IV nb=3 cntn=0 ra=0 hc=0 )
Wmbusmeters can detect decryption failure because the decrypted data does not start with 0x2f 0x2f.

**Comment by weetmuts** [comment]
> Do you know if the length is correct? 

No sorry, this can only be determined after the telegram has been decrypted and decoded.

>Any clue of how to get the key? 

If it is not your own bought meter, then you have to ask the owner of the meter, 
typically a water provider company or a municipal utility company. The one 
that you pay for your water consumption. :-) A lot of people in different
countries have actually been able to get their key for the meter installed in their house.
So its not impossible, but some companies just wont deliver it.

If you bought the meter yourself, then you should receive the key with the meter.

> Maybe brute force? 

Not a chance.  Its AES 128 bits.

> Maybe some default keys?

Some meters have default keys like all zeroes or all ones.
You could try that.

**Comment by nickbardom** [comment]
Hi,
Thanks again for replying. Dou you know how many digits does the Hydrus key have? So I can try it. 
Regards,
Marcus Vinicius
    Em segunda-feira, 24 de agosto de 2020 11:17:17 BRT, Fredrik Öhrström <notifications@github.com> escreveu:  
 
 



Do you know if the length is correct?


No sorry, this can only be determined after the telegram has been decrypted and decoded.


Any clue of how to get the key?


If it is not your own bought meter, then you have to ask the owner of the meter,
typically a water provider company or a municipal utility company. The one
that you pay for your water consumption. :-) A lot of people in different
countries have actually been able to get their key for the meter installed in their house.
So its not impossible, but some companies just wont deliver it.

If you bought the meter yourself, then you should receive the key with the meter.


Maybe brute force?


Not a chance. Its AES 128 bits.


Maybe some default keys?


Some meters have default keys like all zeroes or all ones.
You could try that.

**Comment by weetmuts** [comment]
> Dou you know how many digits does the Hydrus key have?

The keys are always the same length, 128 bits:
00112233445566778899AABBCCDDEEFF

**Comment by nickbardom** [comment]
Thanks for all the info, if I get the keys and get it working, I will let you know.

**Comment by weetmuts** [comment]
Good luck! Closing this for now then.
