### ISSUE TITLE
Daemon not getting any readings.

### ISSUE THREAD

**Issue by Kosygor** [weetmuts/wmbusmeters#171]
Hello finally I got aes key to my watter meter but I spent some time and i guess I am stuck. 

I have read about similar problems in [these](https://github.com/weetmuts/wmbusmeters/issues/40) and that [that](https://github.com/weetmuts/wmbusmeters/issues/69)

checking on services gives me: 
```pi@raspberrypi:~ $ sudo systemctl status wmbusmeters
wmbusmeters.service - "wmbusmeters service (no udev trigger)"
   Loaded: loaded (/etc/systemd/system/wmbusmeters.service; enabled; vendor preset: enabled)
   Active: **failed** (Result: exit-code) since Fri 2020-10-09 21:49:08 CEST; 8min ago
     Docs: https://github.com/weetmuts/wmbusmeters
           man:wmbusmeters(1)
 Main PID: 737 (code=exited, status=1/FAILURE)
paź 09 21:49:07 raspberrypi systemd[1]: Starting "wmbusmeters service (no udev trigger)"...
paź 09 21:49:07 raspberrypi wmbusmetersd[734]: (wmbusmeters) started /run/wmbusmeters/wmbusmeters.pid
paź 09 21:49:07 raspberrypi systemd[1]: Started "wmbusmeters service (no udev trigger)".
paź 09 21:49:07 raspberrypi wmbusmetersd[737]: No such key:
                                                #loglevel
paź 09 21:49:07 raspberrypi wmbusmetersd[737]: No such key:
                                                #loglevel
paź 09 21:49:08 raspberrypi systemd[1]: wmbusmeters.service: Main process exited, code=exited, status=1/FAILURE
paź 09 21:49:08 raspberrypi systemd[1]: wmbusmeters.service: Failed with result 'exit-code'.```

```
pi@raspberrypi:~ $ systemctl status wmbusmeters@-dev-rtlsdr_3
● wmbusmeters@-dev-rtlsdr_3.service - "wmbusmeters service on /dev/rtlsdr_3"
   Loaded: loaded (/lib/systemd/system/wmbusmeters@.service; enabled; vendor preset: enabled)
   Active: **active** (running) since Fri 2020-10-09 21:51:45 CEST; 6min ago
     Docs: https://github.com/weetmuts/wmbusmeters
           man:wmbusmeters(1)
  Process: 14871 ExecStart=/usr/sbin/wmbusmetersd --device=/dev/rtlsdr_3 /run/wmbusmeters/wmbusmeters--dev-rtlsdr_3.pid (code=exited, status=0/SUCCESS)
 Main PID: 14872 (wmbusmetersd)
    Tasks: 6 (limit: 3862)
   CGroup: /system.slice/system-wmbusmeters.slice/wmbusmeters@-dev-rtlsdr_3.service
           ├─14872 /usr/sbin/wmbusmetersd --device=/dev/rtlsdr_3 /run/wmbusmeters/wmbusmeters--dev-rtlsdr_3.pid
           ├─14874 /bin/sh -c /usr/bin/rtl_sdr -f 868.95M -s 1.6e6 - 2>/dev/null | /usr/bin/rtl_wmbus
           ├─14875 /usr/bin/rtl_sdr -f 868.95M -s 1.6e6 -
           └─14876 /usr/bin/rtl_wmbus
```

on the other hand :
`
wmbusmeters --logtelegrams --debug --verbose --format=json rtlwmbus:868.9M  name type id key
`
gives me perfect readings if i stop other services.

Services are starting after plugging dongle. 

`tail -f /var/log/syslog` gives
```Oct  9 22:15:07 raspberrypi systemd[1]: Invalid unit name "wmbusmeters@/dev/rtlsdr_3.service" was escaped as "wmbusmeters@-dev-rtlsdr_3.service" (maybe you should use systemd-escape?)
Oct  9 22:15:07 raspberrypi kernel: [  238.350967] usb 1-1.1.3: dvb_usb_v2: found a 'Realtek RTL2832U reference design' in warm state
Oct  9 22:15:07 raspberrypi systemd[1]: Starting "wmbusmeters service on /dev/rtlsdr_3"...
Oct  9 22:15:07 raspberrypi wmbusmetersd[14973]: (wmbusmeters) started /run/wmbusmeters/wmbusmeters--dev-rtlsdr_3.pid
Oct  9 22:15:07 raspberrypi systemd[1]: Started "wmbusmeters service on /dev/rtlsdr_3".
Oct  9 22:15:07 raspberrypi wmbusmetersd[14974]: No such key: #012#loglevel
Oct  9 22:15:07 raspberrypi wmbusmetersd[14974]: No such key: #012loglevel
Oct  9 22:15:07 raspberrypi kernel: [  238.386387] usb 1-1.1.3: dvb_usb_v2: will pass the complete MPEG2 transport stream to the software demuxer
Oct  9 22:15:07 raspberrypi kernel: [  238.386412] dvbdev: DVB: registering new adapter (Realtek RTL2832U reference design)
Oct  9 22:15:07 raspberrypi kernel: [  238.386420] usb 1-1.1.3: media controller created
Oct  9 22:15:07 raspberrypi kernel: [  238.388799] dvbdev: dvb_create_media_entity: media entity 'dvb-demux' registered.
Oct  9 22:15:07 raspberrypi kernel: [  238.414893] i2c i2c-11: Added multiplexed i2c bus 12
Oct  9 22:15:07 raspberrypi kernel: [  238.414903] rtl2832 11-0010: Realtek RTL2832 successfully attached
Oct  9 22:15:07 raspberrypi kernel: [  238.414999] usb 1-1.1.3: DVB: registering adapter 0 frontend 0 (Realtek RTL2832 (DVB-T))...
Oct  9 22:15:07 raspberrypi kernel: [  238.415014] dvbdev: dvb_create_media_entity: media entity 'Realtek RTL2832 (DVB-T)' registered.
Oct  9 22:15:07 raspberrypi kernel: [  238.436656] i2c i2c-12: fc0012: Fitipower FC0012 successfully identified
Oct  9 22:15:07 raspberrypi kernel: [  238.462367] Registered IR keymap rc-empty
Oct  9 22:15:07 raspberrypi kernel: [  238.463113] rc rc0: Realtek RTL2832U reference design as /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1.3/rc/rc0
Oct  9 22:15:07 raspberrypi kernel: [  238.463924] rc rc0: lirc_dev: driver dvb_usb_rtl28xxu registered at minor = 0, raw IR receiver, no transmitter
Oct  9 22:15:07 raspberrypi kernel: [  238.465441] input: Realtek RTL2832U reference design as /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1.3/rc/rc0/input0
Oct  9 22:15:07 raspberrypi kernel: [  238.465961] usb 1-1.1.3: dvb_usb_v2: schedule remote query interval to 200 msecs
Oct  9 22:15:07 raspberrypi kernel: [  238.474251] usb 1-1.1.3: dvb_usb_v2: 'Realtek RTL2832U reference design' successfully initialized and connected
Oct  9 22:15:07 raspberrypi kernel: [  238.474647] usbcore: registered new interface driver dvb_usb_rtl28xxu
Oct  9 22:15:07 raspberrypi mtp-probe: checking bus 1, device 5: "/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1.3"
Oct  9 22:15:07 raspberrypi mtp-probe: bus: 1, device: 5 was not an MTP device
Oct  9 22:15:07 raspberrypi systemd[1]: Invalid unit name "wmbusmeters@/dev/rtlsdr_3.service" was escaped as "wmbusmeters@-dev-rtlsdr_3.service" (maybe you should use systemd-escape?)
Oct  9 22:15:07 raspberrypi kernel: [  238.609904] dvb_usb_v2: 'Realtek RTL2832U reference design:1-1.1.3' successfully deinitialized and disconnected
```
`tail -f /var/log/wmbusmeters/wmbusmeters.log` gives :
```No wmbus device found! Exiting!
(wmbusmeters) logging started 2020-10-09 21:49:07
No wmbus device found! Exiting!
(wmbusmeters) logging started 2020-10-09 21:51:45
(wmbusmeters) waiting for telegrams
(wmbusmeters) shutting down
(wmbusmeters) logging started 2020-10-09 22:11:17
No wmbus device found! Exiting!
(wmbusmeters) logging started 2020-10-09 22:15:07
(wmbusmeters) waiting for telegrams```

Also i have changed 
```nano /lib/systemd/system/wmbusmeters.service
nano /lib/systemd/system/wmbusmeters@.service`
from original according to [this](https://github.com/zibous/ha-watermeter/blob/master/docs/build-wmbusmeters.md ) ainming for HA integration

in /etc/wmbusmeters.conf
```device=rtlwmbus:rtl_sdr -f 868.9M -s 1.6e6 - 2>/dev/null | rtl_wmbus
device=rtlwmbus:rtl_sdr -f 868.9M -s 1.6e6 - 2>/dev/rtlsdr3 | rtl_wmbus```

Since my meter is only responding to 868.9Mhz it is suspicious to me that i can see that in htop : 
![htop](https://user-images.githubusercontent.com/61921662/95629541-6a460f00-0a80-11eb-88c5-43416ecd109c.png)

**Comment by weetmuts** [comment]
Can you try this using the NewDetectionCode branch which will be the
new master in a few weeks.

Run ./configure; make; sudo make install
Now there only a single daemon, makes it easier to stop and start.

Set the device to auto:c1,t1 t
since your are using rtlwmbus which can detect both c1 and t1 at the same time.

To start and stop.
sudo systemctl start wmbusmeters.service
To enable/start at boot.
sudo systemctl enable wmbusmeters.service

**Comment by weetmuts** [comment]
If you need to adjust the frequency from 868.95M to 868.9M, you should use this device instead:

rtlwmbus:868.9M:c1,t1

**Comment by Kosygor** [comment]
Thank You for Your response
If 
`sudo git clone -b NewDetectionCode https://github.com/weetmuts/wmbusmeters.git`
is right command i did that.Since i do not know how to use uninstall.sh it gave me an error i jus delated previous embusmeters foders. 
I can see change in htop i have three processes called:
`/usr/sbin/wmbusmetersd /run/wmbusmeters/wbusmeters.pid`

sudo systemctl status wmbusmeters.service

`pi@raspberrypi:~ $ sudo systemctl status wmbusmeters.service
● wmbusmeters.service - "wmbusmeters service (no udev trigger)"
   Loaded: loaded (/etc/systemd/system/wmbusmeters.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-10-10 13:41:29 CEST; 54s ago
     Docs: https://github.com/weetmuts/wmbusmeters
           man:wmbusmeters(1)
  Process: 721 ExecStartPre=/bin/mkdir -p /var/log/wmbusmeters/meter_readings (code=exited, status=0/SUCCESS)
  Process: 723 ExecStartPre=/bin/chown -R wmbusmeters:wmbusmeters /var/log/wmbusmeters (code=exited, status=0/SUCCESS)
  Process: 726 ExecStartPre=/bin/mkdir -p /run/wmbusmeters (code=exited, status=0/SUCCESS)
  Process: 731 ExecStartPre=/bin/chown -R wmbusmeters:wmbusmeters /run/wmbusmeters (code=exited, status=0/SUCCESS)
  Process: 734 ExecStart=/usr/sbin/wmbusmetersd /run/wmbusmeters/wmbusmeters.pid (code=exited, status=0/SUCCESS)
 Main PID: 736 (wmbusmetersd)
    Tasks: 3 (limit: 3862)
   CGroup: /system.slice/wmbusmeters.service
           └─736 /usr/sbin/wmbusmetersd /run/wmbusmeters/wmbusmeters.pid

paź 10 13:41:28 raspberrypi systemd[1]: Starting "wmbusmeters service (no udev trigger)"...
paź 10 13:41:29 raspberrypi wmbusmetersd[734]: (wmbusmeters) started /run/wmbusmeters/wmbusmeters.pid
paź 10 13:41:29 raspberrypi systemd[1]: Started "wmbusmeters service (no udev trigger)".

`

weird thing that in `/etc/wmbusmetrs.sd` is now duplicating meter firle *.save


still i do not have any files in `/var/log/wmbusmeters/meter_readings/`

**Comment by weetmuts** [comment]
set
loglevel=debug
restart daemon and
tail -f /var/log/wmbusmeters/wmbusmeters.log

**Comment by Kosygor** [comment]
it gave:
`(shell) arg "wmbusmeters"
(serial) EVENT thread interrupted
(serial) EVENT thread interrupted
(shell) output: >>><<<
(shell) return code 1
(shell) 749 exited
(serial) registered regular callback HOT_PLUG_DETECTOR(0) every 2 seconds
(wmbusmeters) waiting for telegrams
(serial) waiting for stop
(serial) EVENT thread interrupted
`

**Comment by weetmuts** [comment]
Ok, stop the daemon. Unplug your rtlsdr dongle. Test with something simple.
Start wmbusmeters from the command line like this:
wmbusmeters auto:c1 
It prints:
No wmbus device detected, waiting for a device to be plugged in.
No meters configured. Printing id:s of all telegrams heard!

Now insert your rtlsdr dongle, and it will print:
Started auto rtlwmbus on 0_Realtek_RTL2838UHIDIR_00000001 listening on c1

Does this happen?

**Comment by Kosygor** [comment]
`sudo systemctl stop wmbusmeters.service`
freezes on empty line
but htop does not show any wmbusmeters service active do i think it works

`wmbusmeters auto:c1` prints:
```
No wmbus device detected, waiting for a device to be plugged in.
Notice! Wmbusmeters daemon (pid 742) is running and it might hog any wmbus devices.
No meters configured. Printing id:s of all telegrams heard!
```
after pluging dongle 
`Started auto rtlwmbus on 0_Realtek_RTL2838UHIDIR_00000001 listening on c1`
htop shows only running only: `wmbusmeters auto:c1`

**Comment by weetmuts** [comment]
So to get rid of the daemon:
sudo kill -9 742
sudo killall -9 rtl_sdr
sudo killall -9 rtl_wmbus

**Comment by weetmuts** [comment]
Since it printed "Started...", that means that it is listening on 868.95MHz ! Yay!
Now run:
wmbusmeters rtlwmbus:868.9M:c1
this will tune your receiver (rtlwmbus) to this fq instead of 868.95M which is the default.
Wait and see if you get any received telegrams.
(There is a silly alarm logging something about lost device, which is a bug, I will fix that, ignore it for the moment.)

**Comment by Kosygor** [comment]
```
sudo kill -9 742
sudo killall -9 rtl_sdr
sudo killall -9 rtl_wmbus
```
Gives `there is no such process` and `could not find such process. `
I have not seen them since installing branch.

`wmbusmeters rtlwmbus:868.9M:c1` prints
```
Received telegram from: 74159398
          manufacturer: (KAM) Kamstrup Energi (0x2c2d)
           device type: Cold water meter (0x16)
            device ver: 0x1b
         device driver: multical21
(alarm) device_not_found: rtlwmbus:868.9M:c1
Received telegram from: 74159398
          manufacturer: (KAM) Kamstrup Energi (0x2c2d)
           device type: Cold water meter (0x16)
            device ver: 0x1b
         device driver: multical21
(alarm) device_not_found: rtlwmbus:868.9M:c1
```

I am sorry to boter You. I am trying to figure something on my own reading logs etc. but I only acassionaly move outside docker with Home Assistant and therefore I do not have much expierience with linux.

**Comment by weetmuts** [comment]
Ah, there are known difficulties with the rtlsdr and docker and the current wmbusmeters master. 
I am not an expert on the docker stuff, but @BIBOLV is an expert. :-)
 
The NewDetectionCode branch is better since it does not require specifically named /dev/ files
for detection. We intend to make better docker version when this branch is merged.

Can you remove your wmbusmeters docker and run as a plain daemon instead?

//Fredrik

**Comment by Kosygor** [comment]
Im not an expert but since it it running on raspbian buster and I have installed it via ssh it is not in docker. 
Am I right ? 
Only thing that i have In docker is Home Assistant and accompanying addons .

**Comment by BIBOLV** [comment]
@Kosygor looking at your previous comment, looks like you are receiving meter readings ok, so now you just need to adjust configuration to adopt what you are using in command line.
But have you tried running wmbusmeters docker image and for HA integration [this](https://weetmuts.github.io/wmbusmeterswiki/HASS.html)?

**Comment by Kosygor** [comment]
@BIBOLV 
This is exactly what i was trying to do but neither of device configuration worked for me.
Yest I have tried 2 ways of getting data to HA: 
- one You mentioned ;
- https://github.com/zibous/ha-watermeter;
But I still belive there is something wrong im my particular case because there are no readings inside /var/log/wmbusmeters/meter_readings directory. 

No I did not. I just found it out after reading Your post. 
Hope I will menage to install It. I`m currently far from home and have not made any ssh access from outside. I will start testing on Friday. 
Sorry for being little clumsy I am doing my best :) .

**Comment by BIBOLV** [comment]
No worries, I`m sure we will get you up and running sooner or later :wink:
When running docker image read trough readme carefully as you are running rtl_sdr and it needs specific docker config.
Let us know how it goes.

**Comment by weetmuts** [comment]
Ok, I have pushed a fix for the buggy alarm when you specify the device. Please compile and install.

Stop the daemon, sudo systemctl stop wmbusmeters.service
Do:
sudo rm /var/log/wmbusmeters/wmbusmeters.log
then do 
sudo systemctl start wmbusmeters.service

email me the full  /var/log/wmbusmeters/wmbusmeters.log
email me the /etc/wmbusmeters.conf 
(you can cut out the key if you like)

Thanks!

**Comment by Kosygor** [comment]
I just got back to master branch left everything intect except for device configuration (initially I was  using conf from  [ha-watermeters](https://github.com/zibous/ha-watermeter/blob/master/docs/build-wmbusmeters.md) on it is running perfectly stable now. Just one thing left rtl-wmbus is using 40-100% of cpu so I am trying to clean up all copies that i made.
