### ISSUE TITLE
Suport for heat cost allocators Metrona telmetric star 

### ISSUE THREAD

**Issue by bdkacz** [weetmuts/wmbusmeters#205]
Does anybody try to read data from this device http://www.metrona.pl/telmetric-star.html ?

**Comment by BIBOLV** [comment]
Can you provide some decrypted telegrams?

**Comment by alalons** [comment]
I tried to read it and searched info on the net. Nowhere in the documentation mentions wmbus. It mentions 868Mhz transmision only.
Tried reading c mode, s mode an t mode without success. May require activation telegram or may not be wmbus at all.

**Comment by BIBOLV** [comment]
I also did not find any indications in documentation about wmbus, so it is save to assume that some proprietary protocol is being used. 
IMO this ticket can be closed for now.
