### ISSUE TITLE
Support of three Techem products

### ISSUE THREAD

**Issue by KeelOli** [weetmuts/wmbusmeters#206]
Dear Fredrik,

I'm super happy with your Wireless M-Bus program, it performs great on my raspberry pi. I got three Wireless M-Bus Meter from Techem to test:
- Heat cost allocator FHKV radio 4
- Water meter T30 with radio module 4
- Techem Kamstrup heat meter Multical 302 

I realized that all meter types have unknown driver, therefore I went through the how to add new meters with the goal that I can add as many meters as Techem can send me :P

I show you my progress so far with the FHKV 4:

Here the message:
```
Received telegram from: 14542076
          manufacturer: (TCH) Techem Service (0x5068)
                  type: Heat Cost Allocator (0x08)
                   ver: 0x94
                device: im871a[00102489]
                  rssi: -65 dBm
                driver: unknown!
```

with the telegram: 
`telegram=||4E4468507620541494087AAD004005089D86B62A329B3439873999738F82461ABDE3C7AC78692B363F3B41EB68607F9C9160F550769B065B6EA00A2E44346E29FF5DC5CB86283C69324AD33D137F6F|`

key: FCF41938F63432975B52505F547FCEDF

I created the file simulation_mymeter.txt in documents and executed the following command:
`wmbusmeters --debug simulation_mymeter.txt HKVT fhkvdataiii 14542076 FCF41938F63432975B52505F547FCEDF`

with the following result:
```
(wmbusmeters) version: 1.0.3-20-gd8b6583
(config) using device: simulation_mymeter.txt:any 
(config) number of meters: 1
(main) configured "HKVT" "fhkvdataiii" "14542076" encrypted
(lookup) with file "simulation_mymeter.txt"
(lookup) driver: simulation file
(main) opening simulation_mymeter.txt:any
Started config simulation on simulation_mymeter.txt listening on any
(simulation) in simulation_mymeter.txt
(main) regular reset of simulation  on simulation_mymeter.txt will happen every 82800 seconds
(main) added simulation_mymeter.txt to files
(wmbus) no alarm (expected activity) for simulation
(main) simulation_mymeter.txt already configured as simulation
(serial) registered regular callback HOT_PLUG_DETECTOR(0) every 2 seconds
(simulation) from file "4E4468507620541494087AAD004005089D86B62A329B3439873999738F82461ABDE3C7AC78692B363F3B41EB68607F9C9160F550769B065B6EA00A2E44346E29FF5DC5CB86283C69324AD33D137F6F"
(wmbus) parseDLL @0 79
(meter) HKVT: for me? 14542076
(meter) HKVT: meter detection did not match the selected driver fhkvdataiii! correct driver is: unknown!
(meter) please consider opening an issue at https://github.com/weetmuts/wmbusmeters/
(meter) to add support for this unknown mfct,media,version combination
(meter) HKVT: yes for me
(meter) HKVT fhkvdataiii handling telegram from 14542076
(meter) HKVT 14542076 "4E4468507620541494087AAD004005089D86B62A329B3439873999738F82461ABDE3C7AC78692B363F3B41EB68607F9C9160F550769B065B6EA00A2E44346E29FF5DC5CB86283C69324AD33D137F6F"
(wmbus) parseDLL @0 79
(telegram) DLL L=4e C=44 (from meter SND_NR) M=5068 (TCH) A=14542076 VER=94 TYPE=08 (Heat Cost Allocator) (driver unknown!) DEV= RSSI=0
(wmbus) parseELL @10 69
(wmbus) parseAFL @10 69
(wmbus) parseTPL @10 69
(TPL) decrypting "089D86B62A329B3439873999738F82461ABDE3C7AC78692B363F3B41EB68607F9C9160F550769B065B6EA00A2E44346E29FF5DC5CB86283C69324AD33D137F6F"
(TPL) num encrypted blocks 4 (64 bytes and remaining unencrypted 0 bytes)
(TPL) IV 6850762054149408ADADADADADADADAD
(TPL) decrypted  "2F2F036E020000436E190000426C9F2C83046E00000082046C7F2A8D04EE1F1E72FE000000000000000000000000000000000000000000000000030016002F2F"
(dvparser) found new format "036E436E426C83046E82046C8D04EE1F" with hash 4628, remembering!
(telegram) TPL CI=7a ACC=ad STS=00 CFG=0540 (AES_CBC_IV nb=4 cntn=0 ra=0 hc=0)
telegram=|4E4468507620541494087AAD0040052F2F|036E020000436E190000426C9F2C83046E00000082046C7F2A8D04EE1F1E72FE000000000000000000000000000000000000000000000000030016002F2F|+0
(fhkvdataiii) 00: 4e length (78 bytes)
(fhkvdataiii) 01: 44 dll-c (from meter SND_NR)
(fhkvdataiii) 02: 6850 dll-mfct (TCH)
(fhkvdataiii) 04: 76205414 dll-id (14542076)
(fhkvdataiii) 08: 94 dll-version
(fhkvdataiii) 09: 08 dll-type (Heat Cost Allocator)
(fhkvdataiii) 0a: 7a tpl-ci-field (EN 13757-3 Application Layer (short tplh))
(fhkvdataiii) 0b: ad tpl-acc-field
(fhkvdataiii) 0c: 00 tpl-sts-field
(fhkvdataiii) 0d: 4005 tpl-cfg 0540 (AES_CBC_IV nb=4 cntn=0 ra=0 hc=0 )
(fhkvdataiii) 0f: 2f2f decrypt check bytes
(fhkvdataiii) 11: 03 dif (24 Bit Integer/Binary Instantaneous value)
(fhkvdataiii) 12: 6E vif (Units for H.C.A.)
(fhkvdataiii) 13: 020000
(fhkvdataiii) 16: 43 dif (24 Bit Integer/Binary Instantaneous value storagenr=1)
(fhkvdataiii) 17: 6E vif (Units for H.C.A.)
(fhkvdataiii) 18: 190000
(fhkvdataiii) 1b: 42 dif (16 Bit Integer/Binary Instantaneous value storagenr=1)
(fhkvdataiii) 1c: 6C vif (Date type G)
(fhkvdataiii) 1d: 9F2C
(fhkvdataiii) 1f: 83 dif (24 Bit Integer/Binary Instantaneous value)
(fhkvdataiii) 20: 04 dife (subunit=0 tariff=0 storagenr=8)
(fhkvdataiii) 21: 6E vif (Units for H.C.A.)
(fhkvdataiii) 22: 000000
(fhkvdataiii) 25: 82 dif (16 Bit Integer/Binary Instantaneous value)
(fhkvdataiii) 26: 04 dife (subunit=0 tariff=0 storagenr=8)
(fhkvdataiii) 27: 6C vif (Date type G)
(fhkvdataiii) 28: 7F2A
(fhkvdataiii) 2a: 8D dif (variable length Instantaneous value)
(fhkvdataiii) 2b: 04 dife (subunit=0 tariff=0 storagenr=8)
(fhkvdataiii) 2c: EE vif (Units for H.C.A.)
(fhkvdataiii) 2d: 1F vife (Compact profile without register)
(fhkvdataiii) 2e: 1E varlen=30
(fhkvdataiii) 2f: 72FE00000000000000000000000000000000000000000000000003001600
(fhkvdataiii) 4d: 2F skip
(fhkvdataiii) 4e: 2F skip
HKVT	14542076	0 hca	2021-12-06T02:00:00Z	1155 hca	2022-04-31T02:00:00Z	11.54 °C	326.2 °C	2021-01-05 14:26.51
(serial) stopping manager
(serial) waiting for stop
(serial) EVENT thread interrupted
(serial) event loop stopped!
(serial) TIMER thread interrupted
(wmbus) deleted simulation
```

Opened meters.h and added 
`    X(fhkvdataiv, T1_bit, HeatCostAllocationMeter,        FHKVDATAIV,    FHKVDataIV)     \`
to LIST_OF_METERS and:
`    X(FHKVDATAIV,MANUFACTURER_TCH,  0x08,  0x94) \`
to METER_DETECTION

I then added the line $(BUILD)/meter_fhkvdataiv.o \
to the Makefile.

Then I copied meter_fhkvdataiii.cc and renamed it to meter_fhkvdataiv.cc. I changed all the MeterFHKVDataIII to MeterFHKVDataIV as well as createFHKVDataIII to createFHKVDataIV in line 52. According to your manual, I have to adapt now the void MeterFHKVDataIV::processContent(Telegram *t), so I did the following:
```
void MeterFHKVDataIV::processContent(Telegram *t)
{
    // Unfortunately, the Techem FHKV data ii/iii is mostly a proprieatary protocol
    // simple wrapped inside a wmbus telegram since the ci-field is 0xa0.
    // Which means that the entire payload is manufacturer specific.

    vector<uchar> frame;
    t->extractPayload(&frame);
}
```

after that, I change my directory to the place where I cloned the program and executed
`make DEBUG=TRUE HOST=arm`
which worked flawlessly. 

Now is the point where I'm starting to get problems. When I try to execute the following:
```
pi@raspberrypi:~/Repos/********.Microservice.WMBus/wmbusmeters $ ./build_arm_debug/wmbusmeters simulation_mymeter.txt
==3776==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
```
I thought maybe I have to cd into build_arm_debug, so I tried the following:
```
pi@raspberrypi:~/Repos/********.Microservice.WMBus/wmbusmeters/build_arm_debug $ wmbusmeters /home/pi/Repos/********.Microservice.WMBus/wmbusmeters/simulation_mymeter.txt
No meters configured. Printing id:s of all telegrams heard!
Received telegram from: 14542076
          manufacturer: (TCH) Techem Service (0x5068)
                  type: Heat Cost Allocator (0x08)
                   ver: 0x94
                driver: unknown!
```

Still, the driver is unknown, what did I do wrong? Shouldn't it have changed now?

Thank you in advance for your help!

Best regards,
Oliver

**Comment by weetmuts** [comment]
It seems like I acted a bit quickly when adding 0x08,0x94 as a lookup for fhkvdataiii, this was done after
a report by @Marooned-MB in issue: https://github.com/weetmuts/wmbusmeters/issues/191

We noticed in that issue that the fhkvdataiv HCA sent two types of telegrams from the same HCA meter, with the same id,
but different versions/types. The old non-wmbus-compliant fhkvdataiii (which I belive was reverse engineered by @cinemarene) which maps to 0x80,0x94 in the driver lookup.

Thanks to your telegram and key @KeelOli , I could add the new kind of telegram with 0x08,0x94 which is a proper fully wmbus-compliant teletram. 0x08 is the right type as well, aka Heat Cost Allocator. 

My guess is that Techem made the fhkvdataiv backwards compatible with their old collection systems by having
it transmit a fhkvdataiii telegram (probably only if so configured) as well as the new wmbus-compliant telegram....

I had never seen this kind of behaviour before, it sort of clashes with wmbusmeters existing assumptions, id+driver is enough decode the telegram. Actually the driver should be possible to auto-lookup, so only the id is necessary.

Now we have to choose between two drivers for a single id. If you do not have the AES key, you might 
want to use the fhkdataiii driver, but if you do have the key you might want to use the fhkdataiv driver.
If only one type of telegram is transmitted, then all is easy, but if you have to chose, then
you will get one telegram ok and the other with a warning (wrong driver and/or wrong key)

So, I could have added an extension to the  selection of the meter 12345678:0x5068:0x80:0x94 which
would pick up the exact telegram type. But it felt a bit early to do that, it might be needed in the future.

I could also have inserted the detection of the telegram inside the fhkvdataiii driver, but that did not feel
good either since that is indeed a reverse-engineered proprietary protocol, whereas fhkvdataiv is a nice
wmbus-compatible telegram.

So I opted to add a new fhkvdataiv driver, mapped it to 0x08,0x94 and then prevented
the warnings for wrong driver and wrong key, to be printed more than once!

This way, you see the correct recommended driver fhkvdataiv or fhkvdataiii when listening to the telegrams.
Either of them will work, fhkvdataiii without a key, or fhkvdataiv with a key. The warnings for the other telegram
will not take up the log output, since they are only printed once.

Please test the drivers! This is a bit confusing, but I think it should work now. :-)

**Comment by KeelOli** [comment]
I just tested it! Works perfectly!

When we ordered the components from Techem they ask us if we want to have it in the OMS Standart or proprietary and we opted for OMS. 

I still have the water and heat meter, but I wasn't able to receive a message so far from those devices. As soon as I have them and I get similar problems I will post it here. 

Thanks for the great support!

**Comment by KeelOli** [comment]
So I tried to receive the messages from the multical 302. According to the manual of it, the device sends the OMS messages in T1 mode every 15 min. So I wrote the following into my terminal:

`wmbusmeters /dev/ttyUSB0:im871a:t1`

but nothing would happen, therefore I wasn't sure if the device is broken. So I plugged the im871a into my laptop and listened to messages with the wireless M-Bus studio. As expected I received messages from the device every 15 minutes. I copied the message into simulation_mymeter.txt and got the following:

```
pi@raspberrypi:~/Documents $ wmbusmeters --debug simulation_mymeter.txt test multical302:t1 68080468 508A1C4091D7D14D860459FCD361C30A
```
it seems to me that the multical302 driver is not able to work with T1 mode, because when i change it to C1 it works:
```
(cmdline) cannot set link modes to: t1 because meter multical302 only transmits on: c1
pi@raspberrypi:~/Documents $ wmbusmeters --debug simulation_mymeter.txt test multical302:c1 68080468 508A1C4091D7D14D860459FCD361C30A
(wmbusmeters) version: 1.0.4-28-gcff3eb5
(config) using device: simulation_mymeter.txt:any 
(config) number of meters: 1
(main) configured "test" "multical302" "68080468" encrypted
(lookup) with file "simulation_mymeter.txt"
(lookup) driver: simulation file
(main) opening simulation_mymeter.txt:any
Started config simulation on simulation_mymeter.txt listening on any
(simulation) in simulation_mymeter.txt
(main) regular reset of simulation  on simulation_mymeter.txt will happen every 82800 seconds
(main) added simulation_mymeter.txt to files
(wmbus) no alarm (expected activity) for simulation
(main) simulation_mymeter.txt already configured as simulation
(serial) registered regular callback HOT_PLUG_DETECTOR(0) every 2 seconds
(simulation) from file "4E442D2C6804086830047A93104025DDCE925E360AF5052F78A73AC33827A880281AC23739FC530F58414662DD2337C07D5C85F2BE23BAD207254890853B1BDDDB27D79D8DC43330FE279D206A8AF8"
(wmbus) parseDLL @0 79
(meter) test: for me? 68080468
(meter) test: yes for me
(meter) test multical302 handling telegram from 68080468
(meter) test 68080468 "4E442D2C6804086830047A93104025DDCE925E360AF5052F78A73AC33827A880281AC23739FC530F58414662DD2337C07D5C85F2BE23BAD207254890853B1BDDDB27D79D8DC43330FE279D206A8AF8"
(wmbus) parseDLL @0 79
(telegram) DLL L=4e C=44 (from meter SND_NR) M=2c2d (KAM) A=68080468 VER=30 TYPE=04 (Heat meter) (driver multical302) DEV= RSSI=0
(wmbus) parseELL @10 69
(wmbus) parseAFL @10 69
(wmbus) parseTPL @10 69
(TPL) decrypting "DDCE925E360AF5052F78A73AC33827A880281AC23739FC530F58414662DD2337C07D5C85F2BE23BAD207254890853B1BDDDB27D79D8DC43330FE279D206A8AF8"
(TPL) num encrypted blocks 4 (64 bytes and remaining unencrypted 0 bytes)
(TPL) IV 2D2C6804086830049393939393939393
(TPL) decrypted  "2F2F040600000000440600000000426C9F2C041400000000441400000000022D00000259AC08025DDB08023B00000322250A00026CA72101FF21102F2F2F2F2F"
(dvparser) found new format "04064406426C04144414022D0259025D023B0322026C01FF21" with hash 262a, remembering!
(telegram) TPL CI=7a ACC=93 STS=10 CFG=2540 (synchronous AES_CBC_IV nb=4 cntn=0 ra=0 hc=0)
telegram=|4E442D2C6804086830047A931040252F2F|040600000000440600000000426C9F2C041400000000441400000000022D00000259AC08025DDB08023B00000322250A00026CA72101FF21102F2F2F2F2F|+0
(multical302) 00: 4e length (78 bytes)
(multical302) 01: 44 dll-c (from meter SND_NR)
(multical302) 02: 2d2c dll-mfct (KAM)
(multical302) 04: 68040868 dll-id (68080468)
(multical302) 08: 30 dll-version
(multical302) 09: 04 dll-type (Heat meter)
(multical302) 0a: 7a tpl-ci-field (EN 13757-3 Application Layer (short tplh))
(multical302) 0b: 93 tpl-acc-field
(multical302) 0c: 10 tpl-sts-field
(multical302) 0d: 4025 tpl-cfg 2540 (synchronous AES_CBC_IV nb=4 cntn=0 ra=0 hc=0 )
(multical302) 0f: 2f2f decrypt check bytes
(multical302) 11: 04 dif (32 Bit Integer/Binary Instantaneous value)
(multical302) 12: 06 vif (Energy kWh)
(multical302) 13: * 00000000 total energy consumption (0.000000 kWh)
(multical302) 17: 44 dif (32 Bit Integer/Binary Instantaneous value storagenr=1)
(multical302) 18: 06 vif (Energy kWh)
(multical302) 19: * 00000000 target energy consumption (0.000000 kWh)
(multical302) 1d: 42 dif (16 Bit Integer/Binary Instantaneous value storagenr=1)
(multical302) 1e: 6C vif (Date type G)
(multical302) 1f: * 9F2C target date (2020-12-31 00:00)
(multical302) 21: 04 dif (32 Bit Integer/Binary Instantaneous value)
(multical302) 22: 14 vif (Volume 10⁻² m³)
(multical302) 23: * 00000000 total volume (0.000000 m3)
(multical302) 27: 44 dif (32 Bit Integer/Binary Instantaneous value storagenr=1)
(multical302) 28: 14 vif (Volume 10⁻² m³)
(multical302) 29: 00000000
(multical302) 2d: 02 dif (16 Bit Integer/Binary Instantaneous value)
(multical302) 2e: 2D vif (Power 10² W)
(multical302) 2f: * 0000 current power consumption (0.000000 kW)
(multical302) 31: 02 dif (16 Bit Integer/Binary Instantaneous value)
(multical302) 32: 59 vif (Flow temperature 10⁻² °C)
(multical302) 33: AC08
(multical302) 35: 02 dif (16 Bit Integer/Binary Instantaneous value)
(multical302) 36: 5D vif (Return temperature 10⁻² °C)
(multical302) 37: DB08
(multical302) 39: 02 dif (16 Bit Integer/Binary Instantaneous value)
(multical302) 3a: 3B vif (Volume flow l/h)
(multical302) 3b: 0000
(multical302) 3d: 03 dif (24 Bit Integer/Binary Instantaneous value)
(multical302) 3e: 22 vif (On time hours)
(multical302) 3f: 250A00
(multical302) 42: 02 dif (16 Bit Integer/Binary Instantaneous value)
(multical302) 43: 6C vif (Date type G)
(multical302) 44: A721
(multical302) 46: 01 dif (8 Bit Integer/Binary Instantaneous value)
(multical302) 47: FF vif (Vendor extension)
(multical302) 48: 21 vife (per minute)
(multical302) 49: * 10 info codes (FLOW_SENSOR_WEAK_OR_AIR)
(multical302) 4a: 2F skip
(multical302) 4b: 2F skip
(multical302) 4c: 2F skip
(multical302) 4d: 2F skip
(multical302) 4e: 2F skip
test	68080468	0 kWh	0 kW	0 m3	FLOW_SENSOR_WEAK_OR_AIR	2021-01-07 12:01.35
(serial) stopping manager
(serial) waiting for stop
(serial) EVENT thread interrupted
(serial) event loop stopped!
(serial) TIMER thread interrupted
(wmbus) deleted simulation
```

Could that be the reason that I don't receive messages?

**Comment by weetmuts** [comment]
Yes, wmbusmeters did not know that multical302 can transmit t1 messages.
I have pushed a fix for this.

Lets close this issue now. If you have any more problems, please open new separate issues on 
the other techem/products and the multical302 in T1 mode.

**Comment by nanokatz** [comment]
Sorry to comment on an old issue But I cannot get this to work and am pulling out my hair. I have the radio 4 modules (but no keys since it is a rented apartment) from what I understand here I should see them as T mode messages with the same ID but type 0x80. I only the C mode 0x08 messages. have I mis understood?
Adding the ID with fhkvdataiii as a driver specified in a meter files just results in a complaint it is the wrong type and isn't processed.
