### ISSUE TITLE
A very basic question from a new beginner

### ISSUE THREAD

**Issue by vitto62** [weetmuts/wmbusmeters#212]
First of all, a heartfelt thanks for your great work. 

I have been using wmbusmeters for a few hours and am trying to follow the advice given in HowToAddaNewMeter.txt.   My aim is to decode Perry (SaveEnergy - An Italian maker ) HCA telegrams, but at the moment I am just making some exercises with Techem data.

I understand that the command acts differently (in the sense that it will output an "exended debug info") if invoked on input = file compared to input = device. I am wrong?
  So I provide a file that contains ONLY the following line (of course there's no newline in original data!)
` telegram = ||32446850487480126980A0119E28420020230C00AF0818090000000000000000050403000000000000000000141500010001|` 

 but the syntax appears to be incorrect singe I get: `no sensible telegram found, clearing buffer.`
What am I doing wrong?
Here is the complete output I get:

_(wmbusmeters) version: _
(config) using device: Techem-01.txt:any 
(config) number of meters: 1
(main) configured "owH2O" "fhkvdataiii" "12807448" encrypted
(serial) expecting devices to work
(lookup) with file "Techem-01.txt"
(lookup) driver: raw file
(main) opening Techem-01.txt:any
Started config rawtty on Techem-01.txt listening on any
(serial) override with devicefile: Techem-01.txt
(rawtty) on Techem-01.txt
(serialfile) reading from file Techem-01.txt (override Techem-01.txt)
(main) regular reset of rawtty  on Techem-01.txt will happen every 82800 seconds
(wmbus) no alarm (expected activity) for rawtty
(serial) registered regular callback HOT_PLUG_DETECTOR(0) every 2 seconds
(serial) waiting for stop
(serial) no more data on file fd=3
(serial) received binary "74656C656772616D3D7C7C3332343436383530343837343830313236393830413031313945323834323030323032333043303041463038313830393030303030303030303030303030303030353034303330303030303030303030303030303030303030303134313530303031303030317C0A0A"
(serialfile) closed Techem-01.txt -1 (override Techem-01.txt)
(wmbus) checkWMBUSFrame
 "74656C656772616D3D7C7C3332343436383530343837343830313236393830413031313945323834323030323032333043303041463038313830393030303030303030303030303030303030353034303330303030303030303030303030303030303030303134313530303031303030317C0A0A"
(wmbus) no sensible telegram found, clearing buffer.
(rawtty) protocol error in message received!
(rawtty) protocol error ""
(serial) no devices working emergency exit!
(serial) stopping manager
(serial) MAIN thread interrupted
(serial) event loop stopped!
(serial) TIMER thread interrupted
(wmbus) deleted rawtty
(serial) no devices working emergency exit!_

**Comment by weetmuts** [comment]
It does not like the whitespace. Try:
telegram=|......|
on a single line. Also such a simulation file must be named:
simulation_foobar.txt
I.e. it must start with simulation_

Then you can run:
wmbusmeters simulation_foobar.txt
and it will decode the telegrams.

**Comment by vitto62** [comment]
Perfect!    Solved!   Thank you so much!!!!

**Comment by vitto62** [comment]
Can you suggest other sources of information about your application or about newly added meters?  Maybe someone has already sorted out Perry's (SaveEnergy) HCA syntax, so I am wondering if my work may be useless.
THNX!!!

**Comment by weetmuts** [comment]
Is your meter 12807448 ? If so, then its already supported with the fhkvdataiii driver. :-)
If not, then you have to post some telegram=|...| lines here so that we can take a look.

**Comment by vitto62** [comment]
That was understood! :)  I wast exercising myself with wmbusmeters.   As I mentioned before I am currently "playing" with **Techem** HCAs.    And 12807448 is one of those!

**Comment by weetmuts** [comment]
Nope, never heard of it. But if it is wmbus compliant, then it should be easy to add it.

**Comment by vitto62** [comment]
Wonderful, I believe it is!    I'm eager to try.  :)

GRAZIE !!!
