### ISSUE TITLE
Siemens WHE542-D291S  Heat Cost Allocator 

### ISSUE THREAD

**Issue by merbanan** [weetmuts/wmbusmeters#219]
This turned up in the rtl_433 project.

https://github.com/merbanan/rtl_433/issues/1626

**Comment by weetmuts** [comment]
See this issue as well: https://github.com/weetmuts/wmbusmeters/issues/203

**Comment by weetmuts** [comment]
Driver added whe5x, but we need better telegrams since the one regression test we have, is probably truncated.
