### ISSUE TITLE
Diehl IZAR RC 868 i W R4

### ISSUE THREAD

**Issue by scroatamus** [weetmuts/wmbusmeters#270]
I receive this telegram info when i run 
wmbusmeters --nodeviceexit auto:c1
Started auto rtlwmbus[00000001] listening on c1
No meters configured. Printing id:s of all telegrams heard!
Received telegram from: a132257d
          manufacturer: (SAP) Sappel (0x4c30)
                  type: Water meter (0x07)
                   ver: 0x00
                device: rtlwmbus[00000001]
                  rssi: 24 dBm
                driver: izar

If I try reading to screen i get,
wmbusmeters auto:c1 MyTapWater auto a132257d 00112233445566778899AABBCCDDEEFF
Started auto rtlwmbus[00000001] listening on c1
(izar) Decoding PRIOS data failed. Ignoring telegram.
MyTapWater      a132257d                000000  0 m3    0 m3    0-00-00 0 y     no_alarm        no_alarm        0 s     0       2021-03-10 16:56.21
(izar) Decoding PRIOS data failed. Ignoring telegram.
MyTapWater      a132257d                000000  0 m3    0 m3    0-00-00 0 y     no_alarm        no_alarm        0 s     0       2021-03-10 16:56.46

Is my key wrong, or is my meter unsupported.?

says no meters configured though I have a definition
/etc/wmbusmeters.d/SWWMeter

name=SouthWestWater
id=a132257d
key=00112233445566778899AABBCCDDEEFF

packets from rtl-wmbus (oddly I only see T1) 
T1;1;1;2021-03-06 15:05:59.000;21;20;A132257D;0x1944304c7d2532a1b201a2111d001314c2f17ad726f0ea24f41d

**Comment by scroatamus** [comment]
thanks NOKEY works.
think the serial id is right, though I cant relate that to anything on meter.
How do I put NOKEY in a meter file & why isn't mine picked up?

wmbusmeters auto:c1 MyTapWater auto a132257d NOKEY
Started auto rtlwmbus[00000001] listening on c1
MyTapWater      a132257d        C20LU   063613  35.262 m3       33.623 m3       2021-02-28      14.5 y  no_alarm        no_alarm        8 s     2020  2021-03-10 17:40.18
MyTapWater      a132257d        C20LU   063613  35.262 m3       33.623 m3       2021-02-28      14.5 y  no_alarm        no_alarm        8 s     2020  2021-03-10 17:40.26

**Comment by weetmuts** [comment]
Use --format=json and you should see fields that show the serial nrs that are printed on your meter.
Use: key=
to set an empty key (ie NOKEY) in the meter file.

**Comment by pswiatki** [comment]
Look for **prefix** and **serial_number** fields in JSON. They match the physical numbers on the meter. See #271

**Comment by scroatamus** [comment]
I'm now struggling to get the config files to be read. so I can move on to run a daemon & publish MQTT to node red.
I have /etc/wmbusmeters.conf
loglevel=normal
device=auto:c1
logtelegrams=false
format=json
meterfiles=/var/log/wmbusmeters/meter_readings
meterfilesaction=overwrite
logfile=/var/log/wmbusmeters/wmbusmeters.log
shell=/usr/bin/mosquitto_pub -h 192.168.1.119 -t wmbusmeters/$METER_ID -m "$MET$
AND
/etc/wmbusmeters.d/MyTapWater
name=MyTapWater
id=a132257d
key=

When I run command line
wmbusmeters auto
Started auto rtlwmbus[00000001] listening on none
No meters configured. Printing id:s of all telegrams heard!
Received telegram from: a132257d
          manufacturer: (SAP) Sappel (0x4c30)
                  type: Water meter (0x07)
                   ver: 0x00
                device: rtlwmbus[00000001]
                  rssi: 19 dBm
                driver: izar

does not pickup at least the meter config.
permissions issue?

**Comment by scroatamus** [comment]
Still no further on sadly.
Permissions...
I think this is the Realtek RTL28
ls -l /dev/bus/usb/001/006
crw-rw---- 1 root plugdev 189, 5 Mar 12 09:34 /dev/bus/usb/001/006

I've added myself to wmbusmeters group
 groups
pi adm dialout cdrom sudo audio video plugdev games users input netdev gpio i2c spi wmbusmeters

when I run this something is still not right.
sudo wmbusmeters --verbose --useconfig=/ --meterfiles=/
Warning: Unable to locate configuration directory, default config not loaded.
Warning: Unable to locate configuration directory, default config not loaded.

a verbose log
sudo wmbusmeters --logtelegrams --debug --verbose --format=json rtlwmbus MyTapWater izar:t1 a132257d NOKEY
(wmbusmeters) version: 1.2.0-10-g948064a
(config) using device: rtlwmbus
(config) number of meters: 1
(shell) exec (capture output) "/bin/sh"
(shell) arg "-c"
(shell) arg "rtl_sdr < /dev/null"
(shell) output: >>>rtl_sdr, an I/Q recorder for RTL2832 based DVB-T receivers

Usage:   -f frequency_to_tune_to [Hz]
        [-s samplerate (default: 2048000 Hz)]
        [-d device_index (default: 0)]
        [-g gain (default: 0 for auto)]
        [-p ppm_error (default: 0)]
        [-b output_block_size (default: 16 * 16384)]
        [-n number of samples to read (default: 0, infinite)]
        [-S force sync output (default: async)]
        filename (a '-' dumps samples to stdout)

<<<
(serial) EVENT thread interrupted
(shell) return code 1
(shell) 13295 exited
(main) rtl_srd found in path
(shell) exec (capture output) "/bin/sh"
(shell) arg "-c"
(shell) arg "rtl_wmbus < /dev/null"
(shell) output: >>><<<
(shell) return code 0
(shell) 13297 exited
(main) rtl_wmbus found in path
(serial) EVENT thread interrupted
(main) rtlsdr device 00000001 not currently used.
(main) found specified device (rtlwmbus) that matches detected device (:rtlwmbus[00000001]:0/0)
(main) opening rtlwmbus
Started config rtlwmbus[00000001] listening on none
(rtlwmbus) using command: /usr/bin/rtl_sdr  -d 0 -f 868.625M -s 1.6e6 - 2>/dev/null | /usr/bin/rtl_wmbus -s
(rtlwmbus) opening 00000001
(bgshell) exec background "/bin/sh"
(bgshell) arg "-c"
(bgshell) arg "/usr/bin/rtl_sdr  -d 0 -f 868.625M -s 1.6e6 - 2>/dev/null | /usr/bin/rtl_wmbus -s"
(serial) EVENT thread interrupted
(serialcmd) opened /bin/sh pid 13303 fd 5 (rtlwmbus)
(main) regular reset of rtlwmbus  will happen every 82800 seconds
(wmbus) no alarm (expected activity) for rtlwmbus
(serial) registered regular callback HOT_PLUG_DETECTOR(0) every 2 seconds
(serial) waiting for stop
(serial) received ascii "T1;1;1;2021-03-12 09:21:03.000;20;17;A132257D;0x1944304c7d2532a1b201a2211d001314708da02a44848049df1a<0A>"
(rtlwmbus) checkRTLWMBusFrame "T1;1;1;2021-03-12 09:21:03.000;20;17;A132257D;0x1944304c7d2532a1b201a2211d001314708da02a44848049df1a<0A>"
(rtlwmbus) received full frame
(meter) no meter handled  checking 1 templates.
(diehl) Pre-processing: setting device type to water meter for SAP PRIOS
(wmbus) parseDLL @0 26
(wmbus) parseELL @10 16
(wmbus) parseAFL @10 16
(wmbus) parseTPL @10 16
(meter) MyTapWater: for me? a132257d
(meter) MyTapWater: yes for me
(meter) created "MyTapWater" "izar" "a132257d" not-encrypted
(meter) used meter template MyTapWater a132257d izar to match a132257d
(meter) started meter 1 (MyTapWater a132257d izar)
(diehl) Pre-processing: setting device type to water meter for SAP PRIOS
(wmbus) parseDLL @0 26
(wmbus) parseELL @10 16
(wmbus) parseAFL @10 16
(wmbus) parseTPL @10 16
(meter) MyTapWater: for me? a132257d
(meter) MyTapWater: yes for me
(meter) MyTapWater izar handling telegram from a132257d
(meter) MyTapWater a132257d "1944304C7D2532A1B201A2211D001314708DA02A44848049DF1A"
(diehl) Pre-processing: setting device type to water meter for SAP PRIOS
(wmbus) parseDLL @0 26
(telegram) DLL L=19 C=44 (from meter SND_NR) M=4c30 (SAP) A=a132257d VER=00 TYPE=07 (Water meter) (driver izar) DEV=rtlwmbus[00000001] RSSI=20
(wmbus) parseELL @10 16
(wmbus) parseAFL @10 16
(wmbus) parseTPL @10 16
(telegram) TPL CI=a2
telegram=|1944304C7D2532A1B201A2|211D001314708DA02A44848049DF1A|+20
(izar) Decoded PRIOS data: 4BA78A000057830000BC22
(izar) 00: 19 length (25 bytes)
(izar) 01: 44 dll-c (from meter SND_NR)
(izar) 02: 304c dll-mfct (SAP)
(izar) 04: 7d2532a1 dll-id (a132257d)
(izar) 08: 00 dll-version
(izar) 09: 07 dll-type (Water meter)
(izar) 0a: a2 tpl-ci-field (Mfct specific)
{"media":"water","meter":"izar","name":"MyTapWater","id":"a132257d","prefix":"C20LU","serial_number":"063613","total_m3":35.495,"last_month_total_m3":33.623,"last_month_measure_date":"2021-02-28","remaining_battery_life_y":14.5,"current_alarms":"no_alarm","previous_alarms":"no_alarm","transmit_period_s":8,"manufacture_year":"2020","timestamp":"2021-03-12T09:21:03Z","device":"rtlwmbus[00000001]","rssi_dbm":20}

**Comment by pswiatki** [comment]
The log indicates you are getting some telegrams, no?

**Comment by scroatamus** [comment]
oh yes I get telegrams & decoded readings. If I run on the command line in test mode.
I cant run using configs, or as a daemon.

**Comment by scroatamus** [comment]
Why do I get this error?
wmbusmeters --verbose --useconfig=/ --meterfiles=/
Could not open log file.

**Comment by weetmuts** [comment]
How have you installed wmbusmeters? 

You /etc/wmbusmeters.conf contains the setting:
logfile=/var/log/wmbusmeters/wmbusmeters.log
And the directory /var/log/wmbusmeters does not exist or is not writeable.

**Comment by scroatamus** [comment]
git clone https://github.com/weetmuts/wmbusmeters
cd wmbusmeters/
sudo make install

yes config has 
logfile=/var/log/wmbusmeters/wmbusmeters.log

ls -l /var/log/wmbusmeters
total 8
drwxr-xr-x 2 wmbusmeters wmbusmeters 4096 Mar 10 19:17 meter_readings
-rw-r--r-- 1 wmbusmeters wmbusmeters 2103 Mar 12 09:30 wmbusmeters.log

**Comment by scroatamus** [comment]
but i run & get error
wmbusmeters  --verbose --debug --useconfig=/ --meterfiles=/
Could not open log file.

**Comment by weetmuts** [comment]
The "sudo make install" should have added your user to the wmbusmeters group.
Run "groups" does it say wmbusmeters?
If not, add your user to the wmbusmeters group, like this:
 sudo usermod -a -G wmbusmeters yourusername

**Comment by weetmuts** [comment]
You might have to logout and login again to have the group setup properly.

**Comment by scroatamus** [comment]
I had to add myself to groups, & logged out & in 
groups
pi adm dialout cdrom sudo audio video plugdev games users input netdev gp

**Comment by weetmuts** [comment]
Well, does it work now?

**Comment by scroatamus** [comment]
the groups change I did this morning, so no nothing has changed. is this the right command line?
 wmbusmeters  --verbose --debug --useconfig=/ --meterfiles=/
Could not open log file.

**Comment by weetmuts** [comment]
When you use --useconfig=/ all other options are ignored.
Can you print your /etc/wmbusmeter.conf file here?


Den fre 12 mars 2021 kl 21:08 skrev MrBiscuit ***@***.***>:

**Comment by scroatamus** [comment]
loglevel=normal
device=auto:c1
logtelegrams=false
format=json
meterfiles=/var/log/wmbusmeters/meter_readings
meterfilesaction=overwrite
logfile=/var/log/wmbusmeters/wmbusmeters.log
shell=/usr/bin/mosquitto_pub -h 192.168.1.119 -t wmbusmeters/$METER_ID -m "$METER_JSON"

**Comment by weetmuts** [comment]
What happens if you do: touch /var/log/wmbusmeters/wmbusmeters.log
What happens if you do: echo >  /var/log/wmbusmeters/wmbusmeters.log

Remove the two lines with meterfiles...
Change logfile=/home/youruser/the.log
Can you change to loglevel=debug 

Now run the command
wmbusmeters --useconfig=/
again.

What happens? 
What is printed in the.log?

**Comment by scroatamus** [comment]
touch: cannot touch '/var/log/wmbusmeters/wmbusmeters.log': Permission denied
-bash: /var/log/wmbusmeters/wmbusmeters.log: Permission denied

**Comment by scroatamus** [comment]
wmbusmeters   --useconfig=/
(config) "device" "auto:c1"
(config) "logtelegrams" "false"
(config) "format" "json"
(config) "logfile" "/home/pi/the.log"
(config) "shell" "/usr/bin/mosquitto_pub -h 192.168.1.119 -t wmbusmeters/$METER_ID -m "$METER_JSON""
(config) "" ""
(config) loading meter file /etc/wmbusmeters.d/MyTapWater
(config) name=MyTapWater
(config) id=a132257d
(config) key=<notprinted>
(wmbusmeters) using log file /home/pi/the.log
Warning: Unable to locate configuration directory, default config not loaded.

**Comment by scroatamus** [comment]
looks better. except the last warning?

**Comment by weetmuts** [comment]
The permission bits on your files are wrong:
drwxr-xr-x 2 wmbusmeters wmbusmeters 4096 Mar 10 19:17 meter_readings
-rw-r--r-- 1 wmbusmeters wmbusmeters 2103 Mar 12 09:30 wmbusmeters.log
These are not group writeable.
Do this:
sudo chmod -R g+w /var/log/wmbusmeters
and restore the location of the logfile and re-add the meterfiles.
Now it should work with:
wmbusmeters --useconfig=/

What is your linux distribution? It seems like the install has failed
to setup the permission bits right.

**Comment by scroatamus** [comment]
rasbian pi3
Linux version 5.4.51-v7+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1333 SMP Mon Aug 10 16:45:19 BST 2020

**Comment by scroatamus** [comment]
yes that is better.
thank you for your help. You are a patient man.

**Comment by scroatamus** [comment]
I will try running daemon tomorrow, & onto  MQTT and Node red.

**Comment by scroatamus** [comment]
I do get this on the console. not sure what it means
(wmbusmeters) using log file /var/log/wmbusmeters/wmbusmeters.log
Warning: Unable to locate configuration directory, default config not loaded.
Warning: Unable to locate configuration directory, default config not loaded.
Warning: Unable to locate configuration directory, default config not loaded.
Warning: Unable to locate configuration directory, default config not loaded.
Warning: Unable to locate configuration directory, default config not loaded.
Warning: Unable to locate configuration directory, default config not loaded.

**Comment by weetmuts** [comment]
Its mosquitto_pub complaining. Try prefixing the command with HOME=...
like this:
shell=HOME=/home/yourusername /usr/bin/mosquitto_pub .....

**Comment by scroatamus** [comment]
shell=HOME=/home/pi /usr/bin/mosquitto_pub -h localhost -t wmbusmeters/$METER_$
That does remove that warning.
However I seem to get only one meter reading written in /meter_readings, & I cant see any MQTT messages.
If I comment out the mqtt config line, meter readings come in every 8s.
Something is wrong with my MQTT configuration.
I will investigate further this afternoon.
would the topic be MyTapWater OR wmbusmeters/MyTapWater 
and the payload I guess is the whole json construct.

**Comment by weetmuts** [comment]
If you have: meterfilesaction=overwrite
then there is only a single file for each meter. 
Its contents is overwritten with the latest telegram.
Use: meterfilesaction=append
if you want all telegrams collected in the file.

**Comment by scroatamus** [comment]
I have it all working now. Running as a daemon & publishing MQTT.
Do you know anything about SMETS electricity meters? Secure Liberty 100?
would like to read these too. but dont see any packets, perhaps not wmbus.
thank you for your help.

**Comment by scroatamus** [comment]
I get gaps in reporting but the log file shows frames received but skipped for like 30mins or more
the telegrams all have a different time stamp, but are skipped.
(rtlwmbus) received full frame
(wmbus) skipping already handled telegram.

**Comment by weetmuts** [comment]
It skips telegrams that are identical. Try to consume some water, it should send a new telegram. 
Try adding ignoreduplicates=false if you want multiple copies of the same telegram.
How often does it send the telegram?

The ignoreduplicates is primarily to skip telegrams received through different repeaters/antennas/receivers so all duplicates are received within a second or so. Perhaps we should add a time check, if the duplicate
arrives after more than 10 seconds, then it should not be ignored.

Other meters with real security send encrypted telegrams that change with every telegram, even if there is no consumption change.

**Comment by scroatamus** [comment]
telegrams are every 8s. I just happen to be developing the node red interface, & didnt see any data.
I'll try the ignoreduplicates switch

**Comment by scroatamus** [comment]
seemed to improve reporting, but still periods of inactivity & skipped duplicate frames.
run some water & it reports.
thanks I can work with this.

**Comment by weetmuts** [comment]
Well, if you are some distance from the meter, radio signals can get lost.
The radio band is free and many other devices can transmit there.

**Comment by scroatamus** [comment]
Yes I agree. RSSI seems pretty good 11 to 15, but yes 8s reporting intervals there can be local collisions. it is a free radio band as you say.

**Comment by scroatamus** [comment]
Moved antenna. RSSI of 50 is much better. 11-15 is marginal. Now get readings mostly  every 8s.

**Comment by pswiatki** [comment]
Yes, I have to tell you I get over 120 on the "rssi_dbm" from my electrical power meter (amiplus) which is some 4-5 meters away, directly down in the basement. So, the signal must get through a very thick floor between the basement and the ground floor (+ another ~2.5 meters).

Then, I have a water meter (izar, I think exactly like yours) that is buried ~3 meters underground at the very edge of the front yard next to the fence (so that the water company people can pick up the signal nicely, I presume).  That location is ~17 meters away from the receiver. It was absolutely impossible to get any telegrams from that meter and I believe it has a broken TX. Neighbours' meters are easily receivable and some of them are much further away. Anyhow, when I used a 10-element yagi antenna with my RTL-SDR I could finally get telegrams from my own meter, but the signal level (rssi_dbm) is highly dependent on the weather. Sometimes only 2-4 and at this time better, 8-12. Weak, but I get what I am interested in.

**Comment by scroatamus** [comment]
just changed antenna to a home made 1/4 wave, now get RSSI 135. (meter is only 3m away 0.5m underground thru house wall)

**Comment by scroatamus** [comment]
would like to read my electrical meter but think its  zigbee

**Comment by pswiatki** [comment]
> just changed antenna to a home made 1/4 wave, now get RSSI 135. (meter is only 3m away 0.5m underground thru house wall)
Exactly. I wasn't sure if the value could go above 127, but I think I have seen similar values (130+) from my electrical meter.
Also: I have a suspicion the antenna I use is not tuned properly for 868 MHz. Must make my own 1/4 wave and try. If I could only get a more stable signal (and a bit stronger) I would be happy. Sadly. I might also have a lot of collisions as my receiver can "see" many devices in the area.

**Comment by weetmuts** [comment]
I have updated the wiki with my personal experience of the best setup (so far) for receiving using rtl_wmbus.
https://weetmuts.github.io/wmbusmeterswiki/ANTENNA.html

**Comment by scroatamus** [comment]
A not so pretty 1/4 wave diplole solution. Must move that network cable.
![image](https://user-images.githubusercontent.com/68326434/114206186-fdd69a80-9952-11eb-83dc-09e6e64f9037.png)

**Comment by weetmuts** [comment]
Nice @scroatamus ! Can you add the picture and some text to the wiki to explain how one makes such a dipole?

**Comment by scroatamus** [comment]
Sure, will do, this afternoon.

**Comment by scroatamus** [comment]
I couldn't work out how to do the mark up editing of the wiki, failed miserably. so see below...

**Comment by scroatamus** [comment]
You can make a simple 1/4 wave antenna, from a short length of co-axial cable.
 
![image](https://user-images.githubusercontent.com/68326434/114272458-2b344e80-9a0e-11eb-8e97-1d7013865bb4.png)


TV Arial or satellite dish cable is suitable and the impedance 75ohm is probably correct for most SDR dongles.
Start with a length of say 15cm, make one end to the connector required by your SDR radio. (F type in my case).
Trim back the insulation, to just short of the connector 
Remove the copper foil if present underneath.
Then separate the copper braid, from the inner conductor & its dielectric insulator.
If there is another foil layer underneath remove this.
Twist the braid together so it forms a stiff wire, bend thru 90deg.
Bend the inner conductor & its insualtor also thru 90deg in the other direction.
Now trim the length of each wire to 82mm.
 
![image](https://user-images.githubusercontent.com/68326434/114272466-37b8a700-9a0e-11eb-80f0-5a656ee45526.png)

There are a few websites with calculators  for 1/4 wave antennas if other frquencies are required.

**Comment by scroatamus** [comment]
Ok added to wiki on my fork.
Cant remember if I need to do anything next?

**Comment by weetmuts** [comment]
Thanks! I have now pulled it into the wiki! https://weetmuts.github.io/wmbusmeterswiki/

**Comment by don-vip** [comment]
> still don't see a match. but as meter is 6 months old & reading about right, I'm confident its mine.
> "prefix":"C20LU","serial_number":"063613"
> Meter s/n 04511048 this is writen on the clipon. cant see the meter underneath. wonder what the QR is? ( its just all the numbers on label)
> ![image](https://user-images.githubusercontent.com/68326434/110759371-71e32d00-8245-11eb-9082-556fc0e958e8.png)

I think the picture you took is the radio module. The radio frames contain the identifiers from the physical meter itself, not those from the radio module. See #249 and #271 for pictures where the id match.

**Comment by scroatamus** [comment]
Yes I guessed that was the case. 
The meter underneath is now obscured by condensation.
Ah, found a photo I took when the meter was installed.
![image](https://user-images.githubusercontent.com/68326434/115144912-0dd33600-a047-11eb-95dc-e76f4179b9e7.png)

**Comment by don-vip** [comment]
bingo :)

**Comment by weetmuts** [comment]
Can we close this thread?  @scroatamus 
It contains a lot of useful information that will be beneficial to other users having problems in the future!

**Comment by scroatamus** [comment]
I think this can be closed.
I have another problem of wmbusmeters  not restarting after a power cycle, but I haven't fully investigated that yet.( I dont get many power cuts)
systemctl seems to suggest all is ok, 
but I then run wmbusmeters   --useconfig=/ and it starts working. ( close terminal, & it keeps working)

**Comment by weetmuts** [comment]
@scroatamus Good. Please open a new issue if you still have problems with wmbusmeters not starting automatically.

I assume that you have run "sudo systemctl enable wmbusmeters" to make sure it starts on reboot.

**Comment by alecsandes** [comment]
Hello @weetmuts, thank you for such an amazing job!
As the information out there is quite limited with this tool, i revive this thread maybe someone will be able to clarify me
I have this type  of the meter plus the radio module:
![image](https://user-images.githubusercontent.com/19631942/204155722-9746eb5f-ce6b-455d-bda6-2f8f57cf0a21.png)

When I run  wmbusmeters --format=json auto:t1 MyWater izar '*' NOKEY
 i get a lot of 
 
 (izar) Decoding PRIOS data failed. Ignoring telegram.
{"media":"water","meter":"izar","name":"MyWater","id":"2150a86c","prefix":"","serial_number":"000000","total_m3":0,"last_month_total_m3":0,"last_month_measure_date":"128-00-29","remaining_battery_life_y":0,"current_alarms":"meter_blocked,mechanical_fraud","previous_alarms":"leakage","transmit_period_s":0,"manufacture_year":"0","timestamp":"2022-11-27T19:20:33Z","device":"rtlwmbus[00000001]","rssi_dbm":105}

The ID is changing, I am living in a block of apartments.

Is the stuff I have supported?
Do I need some encryption keys to be able to decode the info?
TIA!

**Comment by weetmuts** [comment]
Your meter is probably encrypted with a key other than the default keys.

**Comment by alecsandes** [comment]
Thank you for your quick reply!
Do you know if the keys may be known, or found out by the company that is reading the flowmeters?
Is it easy to add these keys to the program?

**Comment by alecsandes** [comment]
I found this article
https://zewaren.net/wmbus-izar-meter.html
There, the author states that there is a way to decode the key:

How do we find the key?

Easy: we gather a bunch of frames and we brute-force it.

We know the first byte is always 0x4B, the next 4 bytes and the next 4 bytes represent a monotonically increasing value (the second being lower or equal than the first), and the next 2 bytes encode a proper date.

But how long is this cracking going to be, you ask?

Well, if you look at the code, the first thing the key is used for is to create another key, with half the length of the original one:

uint32_t preparePRIOSKey(uint8_t *bytes) {
    uint32_t key1 = read_uint32_be(bytes, 0);
    uint32_t key2 = read_uint32_be(bytes, 4);
    uint32_t key = key1 ^ key2;
    return key;
}
Since the final key is only the first part of the 64 bit original key, XORed with the second part, we should be able to find a working 32 bit key out of the first 32 bits of our choice.

Here is a quick and dirty bunch of C for loops than can be used to find a key:

Here is the key originally used by my meter:

{0x39, 0xBC, 0x8A, 0x10, 0xE6, 0x6D, 0x83, 0xF8}
Here are a bunch of keys that work just as well, that I cracked from a list of captured frames:

{0xdf, 0xd1, 0x09, 0xe8, 0x00, 0x00, 0x00,0x00}
{0x01, 0x7c, 0xb7, 0x47, 0xde, 0xad, 0xbe, 0xaf}
{0x20, 0x2e, 0xf6, 0x17, 0xff, 0xff, 0xff, 0xff}
Each of them took a few minutes to find on modern PC computer.

Is this already included in your program?

I would like to try my best to get they key, can it be added by me in some file?

I am not a programmist but I have some basic knowledge and I need to be guided

**Comment by weetmuts** [comment]
I do not have the time to help you decode your key, or write a program to decode it. 
Please open another issue (this one is closed) and ping ZeWaren to see if he has the time to help you.

**Comment by alvaromemo** [comment]
@weetmuts is the default key is only 8Bytes (For Izar), when using AES128, how i complete the AES key?

this way? 39BC8A10E66D83F839BC8A10E66D83F8

#define PRIOS_DEFAULT_KEY1 "39BC8A10E66D83F8"
#define PRIOS_DEFAULT_KEY2 "51728910E66D83F8"

**Comment by weetmuts** [comment]
@alvaromemo Correction, it seems that we have a function addDefaultManufacturerKeyIfAny that adds KEY2+KEY2 as a default key for certain OMS 128bit AES key meters. You could try that.

**Comment by kmlZ** [comment]
@alecsandes 
Hi, have you managed to crack the key?

**Comment by alecsandes** [comment]
Hi,

Unfortunately not.
I have ran the cracking program from zewaren but it was taking too much to
process.

În joi, 2 ian. 2025 la 15:10, Kamil Hamerlak ***@***.***> a
scris:
