### ISSUE TITLE
Very nice real-world S/N decoding for Diehl IZAR water meter

### ISSUE THREAD

**Issue by pswiatki** [weetmuts/wmbusmeters#271]
Not an issue, but materials can be used to update the Wiki page, or another place which could be helpful to users.
Getting telegrams and seeing in the resulting JSON:

{"media":"water","meter":"izar","name":"wasser/P15_Main","id":"12345678","prefix":"**C19SB**","serial_number":"**053746**","total_m3":251.887,"last_month_total_m3":249.493,"last_month_measure_date":"2021-02-28","remaining_battery_life_y":13.5,"current_alarms":"no_alarm","previous_alarms":"no_alarm","transmit_period_s":8,"manufacture_year":"2019","timestamp":"2021-03-10T16:15:13Z","device":"rtlwmbus[0000616]","rssi_dbm":11}

Perfect match:

![2020-07-29_20 41 16](https://user-images.githubusercontent.com/7026139/110685808-f6e72b80-81de-11eb-85a7-053771f1f4f6.png)

Thank you much for this decent werk.

**Comment by weetmuts** [comment]
Thanks I have added your material to the wiki!
https://weetmuts.github.io/wmbusmeterswiki/IZAR.html

**Comment by don-vip** [comment]
Glad to see it works for other people!

**Comment by VPMateev18** [comment]
can someone help me
