### ISSUE TITLE
Is this dongle supported?

### ISSUE THREAD

**Issue by fsutter** [weetmuts/wmbusmeters#292]
Hi,
I bought this dongle from Alibaba: https://www.alibaba.com/product-detail/868MHz-Wireless-M-Bus-modules-s_62137389990.html?spm=a2700.galleryofferlist.normal_offer.d_image.21302d18P47iCh
Do you know if it is supported?

Many thanks in advance and kind regards
fsutter

**Comment by weetmuts** [comment]
It is not supported. I have one, but I never got it working. The serial communication stops working within a few minutes of having it configured, if it even gets that far.

**Comment by fsutter** [comment]
Thanks.
I thought it was better that my current SDR dongle.
So I lost 30$ (+26€ custom taxes) for nothing :(

**Comment by weetmuts** [comment]
Too bad. Otherwise the im871a is a great dongle.

**Comment by fsutter** [comment]
Thanks for the advice.
Do you know if it exists with a SMA connector?

**Comment by fsutter** [comment]
Do you recommend me a vendor to buy the im871?

**Comment by jupiter9595** [comment]
@fsutter - yes there is im871a adapter with SMA connector. It is proprietary design, Send me a private message to my github account. I will provide you with the details.

**Comment by fsutter** [comment]
@jupiter9595 I haven't found a way to send a private message to your github account.

**Comment by jupiter9595** [comment]
@fsutter - well, yes for some reason it is still unavailable. I've unchecked [Keep my email addresses private] this in account setting > emails section. But yes it did not work. Any suggestions? To avoid this off topic here.

**Comment by fsutter** [comment]
Hi,

are you on twitter with the same nickname?

regards,

fsutter

________________________________

**Comment by jupiter9595** [comment]
Ok, you can now see my email in github front overview page. Send me an email and we'll start from there

**Comment by weetmuts** [comment]
Closing this issue for now!
