### ISSUE TITLE
(wmbusmeters) shutting down

### ISSUE THREAD

**Issue by Horndrup** [weetmuts/wmbusmeters#296]
After a new installation on a RPI the installation of wmbusmeters stops working after a few hours.

Why does this happen?

(shell) waiting for child 6367 to complete.
(shell) /bin/sh: return code 0
(serial) stopping manager
(serial) MAIN thread interrupted
(serial) closing 1 devices
(serial) TIMER thread interrupted
(wmbus) disconnected /dev/ttyUSB0 im871a
(serialtty) closed /dev/ttyUSB0 (im871a)
(serial) EVENT thread interrupted
(serial) event loop stopped!
(wmbusmeters) shutting down
(wmbus) deleted im871a
(serial) closing 1 devices

**Comment by weetmuts** [comment]
Need more logs to debug this post your syslog and your wmbusmeters log.

**Comment by Horndrup** [comment]
I found the problem. I had something in crontab restarting my RPI. Problem solved.

**Comment by weetmuts** [comment]
Great!
