### ISSUE TITLE
IZAR CP R3.5 868MHz

### ISSUE THREAD

**Issue by krzbor** [weetmuts/wmbusmeters#298]
Is wmbusmeters compatible with IZAR CP R3.5 868MHz?

**Comment by krzbor** [comment]
I bought nanoCUL and started testing.
I can confirm that wmbusmeters correctly decodes data from IZAR CP R3.5 868MHz. It is recognized as "izar".

**Comment by weetmuts** [comment]
Nice! Closing this then! :-)
