### ISSUE TITLE
No meters configured. Printing id:s of all telegrams heard!

### ISSUE THREAD

**Issue by ptorrent** [weetmuts/wmbusmeters#307]
Hello there !

I m trying to use wmbusmeters.

I create a directory with meters informations inside
```
name=device1
id=74885803
key=B8DA913940EA648291F7BA97A94D095D
```

then I execute the commande:

```
wmbusmeters --meterfiles=[my directory] auto:c1 /dev/ttyUSB0
```

I receive some data:

![image](https://user-images.githubusercontent.com/6083644/124785433-2288e100-df47-11eb-8c01-eb319812c66f.png)

1. Why I have this error "No meters configured. Printing id:s of all telegrams heard!" ?
2. Where can I find the instantaneous value?
3. Is there a way to get this kind of format in the stdout of the command ? (already try --format=json)
```
{
    "media": "heat cost allocation",
    "meter": "whe5x",
    "name": "zaehler_94025228",
    "id": "94025228",
    "current_consumption_hca": 251,
    "set_date": "2020-12-31",
    "consumption_at_set_date_hca": 287,
    "set_date_1": "2020-12-31",
    "consumption_at_set_date_1_hca": 287,
    "error_date": "2127-15-31",
    "device_date_time": "2021-07-04 12:07",
    "timestamp": "2021-07-04T10:59:10Z",
    "device": "rtlwmbus[00000001]",
    "rssi_dbm": 15
}
```

Thanks for your help !

**Comment by weetmuts** [comment]
From commandline:
wmbusmeters  --format=json auto:c1 device1 auto 74885803 B8DA913940EA648291F7BA97A94D095D

**Comment by ptorrent** [comment]
oh much better, is there a way to get those values with meter file config ?

**Comment by weetmuts** [comment]
Sure is. Read the part of the README that is titled: Build from source and run as a daemon
There are examples of how to write the /etc/wmbusmeters.conf 
and how to add /etc/wmbusmeters.d/MyMeter 
files with meter configs.

**Comment by weetmuts** [comment]
When the config is written. You can either run as a daemon or run this command line:
wmbusmeters --useconfig=/
To pickup the settings you have put in place in /etc/....

**Comment by ptorrent** [comment]
this is not what I do with meterfiles  options ?

```
wmbusmeters --meterfiles=[my directory] auto:c1 /dev/ttyUSB0
```

**Comment by weetmuts** [comment]
Nope, read the README.
--meterfiles=<dir> specifies that wmbusmeters should write each received meter measurement as a file in this <dir>.

**Comment by ptorrent** [comment]
Ok thanks ! So if I understand well, there is no way to get metter value juste in stdout or stderr of the command line ? We've to read the file  for each meter ?

**Comment by weetmuts** [comment]
Just do not use --meterfiles and it will output all meters on stdout.

**Comment by ptorrent** [comment]
Thanks ! Its works. Last question (I hope:)

Is there a way to add meter infomations in the json ?


![SmartSelect_20210708-003842_Samsung Internet](https://user-images.githubusercontent.com/6083644/124837476-318e8400-df85-11eb-9260-57ed1534b2eb.jpg)

**Comment by weetmuts** [comment]
Sure can. Again in the README it says add:
--json_xxx=yyy
This will put "xxx":"yyy" into the generated json. You can do this multiple times.
You can have per meter unique settings assuming you have
/etc/wmbusmeters.d/MyMeterFloor1
you can add
json_floor=1
to that file, thus adding "floor":"1"
only to telegrams coming from that meter.

The manufacturer is not actually available right now in the telegram json.
No-one has had any need for that, but it is easy to add.

For historical, slightly random reasons:
The type is called media in the json.
The driver is called meter in the json.
