### ISSUE TITLE
bmeters help

### ISSUE THREAD

**Issue by spiri439** [weetmuts/wmbusmeters#308]
(meter) bmt: meter detection could not find driver for id: 21221796 mfct: (BMT) BMETERS, Italy (0x9b4) type: Warm Water (30°C-90°C) meter (0x06) ver: 0x13
(meter) please consider opening an issue at https://github.com/weetmuts/wmbusmeters/
(meter) to add support for this unknown mfct,media,version combination
telegram=|3044B4099617222113067A190020052F2F|0C1315000000046D0136A7270F050B000000002F2F2F2F2F2F2F2F2F2F2F69E5|+124
bmt     21221796                2021-07-07 22:01.57

telegram=|2344B4099517222113077A1A000000|0C1323000000046D0336A7270F050B0000000036EA|+235
bmt     21221795        0.023 m3        2021-07-07 22:03        2021-07-07 22:03.48

Hello, I have 2 bmeter water meter one in encrypted and I have the key and one not.
The encrypted one looks like it is not decoding the telgram corectly can you please help?

**Comment by weetmuts** [comment]
Fix merged, please test!
