### ISSUE TITLE
Apator AT-WMBUS-17-2 

### ISSUE THREAD

**Issue by Merangle** [weetmuts/wmbusmeters#316]
Hello
Thanks for the tool.

I've got a meter with an Apator-AT-WMBUS-17-2. 
Which driver can I use ? apator172? apator162 ?

When listening with this command "wmbusmeters  auto;c1", I can see many meters with different drivers (izar, mkradio3, unknown).
 When listening with this command "wmbusmeters --logtelegrams --format==json auto:c1 watermeter name_of_driver, serial_number NOKEY), I receive informations about all the meters identified but no one with the right value of the meter. 

Is there an issue with driver ?
Will the driver adaptor172 implemented ? 
Many thanks for your help

**Comment by BIBOLV** [comment]
Hi,
From Apator currently only at-wmbus-08 and at-wmbus-16-2 are somewhat supported as Apator uses non-standard protocol. To check and see if support for at-wmbus-17-2 can be added you should log decrypted telegrams and post here.
Check serial number on module and try to find that serial in received telegrams. You should also have decryption key in order to decode telegrams, as they, most probably, are encrypted.

**Comment by Merangle** [comment]
Hello 
Thanks for your answer. 

Please find attached two files:

- search.log with the result of the command = wmbusmeters --debug auto:c1 rtlwmbus to check what can be heard
- meters.log with the result of the command =   wmbusmeters --logtelegrams --logfile=/home/pi/meters.log auto:c1 watermeter auto 001143ca,001146d3 NOKEY to gather telegrams received from my two meters
- I have two meters with protocol apator-AT-Wmbus 17-2 identified with number 1131466 (1143ca in hexa) and 1132243 (1146d3 in hexa)

The question is how to get the encryption key ?
The radio module has been installed by a company which collect all meters for the landlord to invoice the water consumption. 
I'm would like to follow my consumption trough Home Assistant with  leakage notification. 

All your comments will be welcome. 
regards
[meters.log](https://github.com/weetmuts/wmbusmeters/files/6872753/meters.log)
[search.log](https://github.com/weetmuts/wmbusmeters/files/6872754/search.log)

**Comment by BIBOLV** [comment]
You should ask company that installed them to provide key for each meter, without it nothing can be done.

**Comment by weetmuts** [comment]
Hi @Merangle!

Your meter 1132243 (1146d3 in hexa) seems to output a readable telegram, that is not encrypted.
telegram=|1C441486D34611000411A0|0DAC04000040030000000005FF06C3980400|

However it is mostly proprietary data. But fortunately the telegram is short. :-)

Do this:
wmbusmeters --logtelegrams auto:t1 Apa apator162 001146d3 NOKEY
and then collect a lot of telegrams when you send water through the meter and manually read the actual
meter values when the log starts getting collected and when the loging is stopped.
Post the data here.

Then it should be possible to figure out which bytes represent the total_m3.

Please have a go at decoding the values yourself, if you can!

**Comment by weetmuts** [comment]
I temporarily use the apator162 driver, but it produces the wrong values, as expected. With the information you collect we can create an apator172 driver.

**Comment by Merangle** [comment]
Hello
thanks for the suggestion.
I won't be able to do the test before mid september.
I will let you know as soon as I am able to collect the data.
Best regards

-- 

Le dim. 8 août 2021 à 17:38, Fredrik Öhrström ***@***.***> a
écrit :

**Comment by Merangle** [comment]
Hello

Sorry för thé delay

Please find attached several files with the result of thé suggested query.
În thé name of thé file, you will find thé volume  meters-mmmlll.log
contains the result when thé meter read mmm m and lll liters

Ï hope this helps.
How can Ï help you more ?
best regards

Le dim. 8 août 2021 à 17:38, Fredrik Öhrström ***@***.***> a
écrit :

**Comment by weetmuts** [comment]
Sorry, I cannot see any attached files? Can be re-attach them or email them to me? Thanks!

**Comment by akanegally** [comment]
Hello, I have the same water meter apator at-wmbus-17-2. 
Actually since the 15 of march, all residents have the same water meter.

I managed to capture all the telegrams I recieved throught this command (cf[ all_telegrams.log](https://www.amazon.fr/clouddrive/share/X3esewS3sJCBQJL2MbFZxUdo1xoj4M48KVfVPGtNt4F))
I hope it will helps.
wmbusmeters --debug --t1 auto


On my meter (cf [my_meter.jpg](https://www.amazon.fr/clouddrive/share/Rp80OYVayyr4ZXKlkdpTd5M17xFtcn6ENczHMmk1dDj)), the serial is 1353735.
So I think the id of my telegram is 0014A807.

 I have also captured all the telegram ([my_meter.log](https://www.amazon.fr/clouddrive/share/cLRgC5BqblpGeVRAIzv4S5UpoeZDW3iWtcZzEkHtA05)) with this command :
 ./wmbusmeters --debug auto:t1 watermeter apator162 0014a807 NOKEY

It doesn't seems to work. I think those telegrams are crypted.

I tried to ask for the encryption key but the hotline of my provider was clueless.
Is there a way to get my consuption from an apator172 ?

**Comment by weetmuts** [comment]
Hi @akanegally ! Thank you for the log, the meters do not seem to be encrypted.
However it is a proprietary format, but there are so few bytes that this should be easy to figure out.
However, you need to collect a number of telegrams from your own meter. 

Are you using an rtlsdr? Can you remove the antenna, or  wrap parts of the antenna in aluminium foil
or some other metal. Place the rtlsdr/crippled antenna really close to your own meter. If you tweak it enough you 
should only receive your own meter telegrams!

Now collect telegrams over a few hours and take notice of the meter readings at the times you collect
and consume some water so that the readings go up.
So that we know approximately what the meter was sending when you received the telegram.

Use:
wmbusmeters --logtelegrams --t1 auto 2>&1 | tee thelog

Now thelog contains lines like these:
telegram=|_1c44148606ac14000411a03b0600000800030000000005ff027d01000|+1231

Post the log here. :-)

You can now start analysing this yourself if you like. The content that can containg the reading starts after a0
telegram=|_1c44148606ac14000411a0 >>>3b0600000800030000000005ff027d01000<<< |+1231
it should be pretty easy to see which values are increasing over time.

**Comment by weetmuts** [comment]
If your meter is indeed 0014A807, then you can first try

wmbusmeters --logtelegrams --t1 auto 2>&1 | grep telegram  | grep 07A81400

and collect some telegrams, then use some water and see how the telegrams change.

**Comment by akanegally** [comment]
Hi, I managed to capture new telegrams this sunday.
I tried to use water but my consumption went only from 4.056m3 to 4.320m3
You can find the log [here](https://www.amazon.fr/clouddrive/share/2naAzF63A8XUniMGdW66usKtI4lv1dKBqpwW4qPYPGx)

I'm not sure if it's enough so let me know. 

I will also try to capture some new data today.

**Comment by akanegally** [comment]
Hello, I captured some telegram of my meter
it goes from 7033m3 to 7179m3
./wmbusmeters --logtelegrams --t1 auto 2>&1 | grep telegram | grep 07A81400 | tee mon_compteur_now.log
telegram=|_1C44148607A814000411A0BD5200000800030000000005FF05D83D0000|+39
telegram=|_1C44148607A814000411A0BD5200000800030000000005FF05D83D0000|+114
telegram=|_1C44148607A814000411A0BC5200000800030000000005FF05D83D0000|+140
telegram=|_1C44148607A814000411A0BE5200000800030000000005FF05D83D0000|+180
telegram=|_1C44148607A814000411A0C65200000800030000000005FF05D83D0000|+209
telegram=|_1C44148607A814000411A0D85200000800030000000005FF05D83D0000|+277
telegram=|_1C44148607A814000411A0DC5200000800030000000005FF05D83D0000|+317
telegram=|_1C44148607A814000411A0DD5200000800030000000005FF05D83D0000|+359
telegram=|_1C44148607A814000411A0DC5200000800030000000005FF05D83D0000|+415
telegram=|_1C44148607A814000411A0DF5200000800030000000005FF05D83D0000|+455
telegram=|_1C44148607A814000411A0EC5200000800030000000005FF05D83D0000|+495
telegram=|_1C44148607A814000411A0FD5200000800030000000005FF05D83D0000|+546
telegram=|_1C44148607A814000411A0025300000800030000000005FF05D83D0000|+586
telegram=|_1C44148607A814000411A0025300000800030000000005FF05D83D0000|+647
telegram=|_1C44148607A814000411A0025300000800030000000005FF05D83D0000|+756
telegram=|_1C44148607A814000411A0025300000800030000000005FF05D83D0000|+841
telegram=|_1C44148607A814000411A0035300000800030000000005FF05D83D0000|+870
telegram=|_1C44148607A814000411A0025300000800030000000005FF05D83D0000|+939
telegram=|_1C44148607A814000411A0035300000800030000000005FF05D83D0000|+984
telegram=|_1C44148607A814000411A0035300000800030000000005FF05D83D0000|+1068
telegram=|_1C44148607A814000411A0035300000800030000000005FF05D83D0000|+1125
telegram=|_1C44148607A814000411A0025300000800030000000005FF05D83D0000|+1199
telegram=|_1C44148607A814000411A0025300000800030000000005FF05D83D0000|+1264
telegram=|_1C44148607A814000411A0035300000800030000000005FF05D83D0000|+1319
telegram=|_1C44148607A814000411A0035300000800030000000005FF05D83D0000|+1371
telegram=|_1C44148607A814000411A0045300000800030000000005FF05D83D0000|+1411
telegram=|_1C44148607A814000411A0045300000800030000000005FF05D83D0000|+1469
telegram=|_1C44148607A814000411A0055300000800030000000005FF05D83D0000|+1518
telegram=|_1C44148607A814000411A0055300000800030000000005FF05D83D0000|+1598
telegram=|_1C44148607A814000411A0065300000800030000000005FF05D83D0000|+1703
telegram=|_1C44148607A814000411A0065300000800030000000005FF05D83D0000|+1786
telegram=|_1C44148607A814000411A0075300000800030000000005FF05D83D0000|+1826
telegram=|_1C44148607A814000411A0075300000800030000000005FF05D83D0000|+1909
telegram=|_1C44148607A814000411A0075300000800030000000005FF05D83D0000|+1959
telegram=|_1C44148607A814000411A0085300000800030000000005FF05D83D0000|+1986
telegram=|_1C44148607A814000411A0085300000800030000000005FF05D83D0000|+2066
telegram=|_1C44148607A814000411A0095300000800030000000005FF05D83D0000|+2154
telegram=|_1C44148607A814000411A00A5300000800030000000005FF05D83D0000|+2230
telegram=|_1C44148607A814000411A00B5300000800030000000005FF05D83D0000|+2327
telegram=|_1C44148607A814000411A00A5300000800030000000005FF05D83D0000|+2389
telegram=|_1C44148607A814000411A00B5300000800030000000005FF05D83D0000|+2405
telegram=|_1C44148607A814000411A00C5300000800030000000005FF05D83D0000|+2505
telegram=|_1C44148607A814000411A00D5300000800030000000005FF05D83D0000|+2598
telegram=|_1C44148607A814000411A00D5300000800030000000005FF05D83D0000|+2678
telegram=|_1C44148607A814000411A00E5300000800030000000005FF05D83D0000|+2757
telegram=|_1C44148607A814000411A00E5300000800030000000005FF05D83D0000|+2871
telegram=|_1C44148607A814000411A00F5300000800030000000005FF05D83D0000|+2981
telegram=|_1C44148607A814000411A0105300000800030000000005FF05D83D0000|+3067
telegram=|_1C44148607A814000411A0105300000800030000000005FF05D83D0000|+3155
telegram=|_1C44148607A814000411A0105300000800030000000005FF05D83D0000|+3213
telegram=|_1C44148607A814000411A0115300000800030000000005FF05D83D0000|+3253
telegram=|_1C44148607A814000411A0115300000800030000000005FF05D83D0000|+3351
telegram=|_1C44148607A814000411A0125300000800030000000005FF05D83D0000|+3386
telegram=|_1C44148607A814000411A0135300000800030000000005FF05D83D0000|+3451
telegram=|_1C44148607A814000411A0135300000800030000000005FF05D83D0000|+3544
telegram=|_1C44148607A814000411A0145300000800030000000005FF05D83D0000|+3636
telegram=|_1C44148607A814000411A0145300000800030000000005FF05D83D0000|+3711
telegram=|_1C44148607A814000411A0155300000800030000000005FF05D83D0000|+3751
telegram=|_1C44148607A814000411A0155300000800030000000005FF05D83D0000|+3803
telegram=|_1C44148607A814000411A0165300000800030000000005FF05D83D0000|+3888
telegram=|_1C44148607A814000411A0165300000800030000000005FF05D83D0000|+3952
telegram=|_1C44148607A814000411A0175300000800030000000005FF05D83D0000|+3988
telegram=|_1C44148607A814000411A0175300000800030000000005FF05D83D0000|+4070
telegram=|_1C44148607A814000411A0175300000800030000000005FF05D83D0000|+4161
telegram=|_1C44148607A814000411A0185300000800030000000005FF05D83D0000|+4201
telegram=|_1C44148607A814000411A0185300000800030000000005FF05D83D0000|+4241
telegram=|_1C44148607A814000411A0195300000800030000000005FF05D83D0000|+4257
telegram=|_1C44148607A814000411A0195300000800030000000005FF05D83D0000|+4303
telegram=|_1C44148607A814000411A0195300000800030000000005FF05D83D0000|+4379
telegram=|_1C44148607A814000411A01A5300000800030000000005FF05D83D0000|+4479
telegram=|_1C44148607A814000411A01A5300000800030000000005FF05D83D0000|+4575
telegram=|_1C44148607A814000411A01B5300000840030000000005FF05D83D0000|+4630
telegram=|_1C44148607A814000411A01C5300000840030000000005FF05D83D0000|+4673
telegram=|_1C44148607A814000411A01C5300000840030000000005FF05D83D0000|+4751
telegram=|_1C44148607A814000411A01C5300000840030000000005FF05D83D0000|+4811
telegram=|_1C44148607A814000411A01D5300000840030000000005FF05D83D0000|+4841
telegram=|_1C44148607A814000411A01D5300000840030000000005FF05D83D0000|+4949
telegram=|_1C44148607A814000411A01E5300000840030000000005FF05D83D0000|+5038
telegram=|_1C44148607A814000411A01F5300000840030000000005FF05D83D0000|+5078
telegram=|_1C44148607A814000411A01F5300000840030000000005FF05D83D0000|+5120
telegram=|_1C44148607A814000411A01F5300000840030000000005FF05D83D0000|+5159
telegram=|_1C44148607A814000411A0205300000840030000000005FF05D83D0000|+5212
telegram=|_1C44148607A814000411A0205300000840030000000005FF05D83D0000|+5301
telegram=|_1C44148607A814000411A0205300000840030000000005FF05D83D0000|+5355
telegram=|_1C44148607A814000411A0205300000840030000000005FF05D83D0000|+5419
telegram=|_1C44148607A814000411A0215300000840030000000005FF05D83D0000|+5459
telegram=|_1C44148607A814000411A0225300000840030000000005FF05D83D0000|+5498
telegram=|_1C44148607A814000411A0225300000840030000000005FF05D83D0000|+5538
telegram=|_1C44148607A814000411A0225300000840030000000005FF05D83D0000|+5597
telegram=|_1C44148607A814000411A0235300000840030000000005FF05D83D0000|+5681
telegram=|_1C44148607A814000411A0235300000840030000000005FF05D83D0000|+5721
telegram=|_1C44148607A814000411A0245300000840030000000005FF05D83D0000|+5798
telegram=|_1C44148607A814000411A0235300000840030000000005FF05D83D0000|+5823
telegram=|_1C44148607A814000411A0245300000840030000000005FF05D83D0000|+5863
telegram=|_1C44148607A814000411A0255300000840030000000005FF05D83D0000|+5903
telegram=|_1C44148607A814000411A0255300000840030000000005FF05D83D0000|+5999
telegram=|_1C44148607A814000411A0265300000840030000000005FF05D83D0000|+6077
telegram=|_1C44148607A814000411A0265300000840030000000005FF05D83D0000|+6156
telegram=|_1C44148607A814000411A0265300000840030000000005FF05D83D0000|+6196
telegram=|_1C44148607A814000411A0275300000840030000000005FF05D83D0000|+6229
telegram=|_1C44148607A814000411A0275300000840030000000005FF05D83D0000|+6309
telegram=|_1C44148607A814000411A0285300000840030000000005FF05D83D0000|+6348
telegram=|_1C44148607A814000411A0285300000840030000000005FF05D83D0000|+6432
telegram=|_1C44148607A814000411A0285300000840030000000005FF05D83D0000|+6493
telegram=|_1C44148607A814000411A0295300000840030000000005FF05D83D0000|+6561
telegram=|_1C44148607A814000411A0295300000840030000000005FF05D83D0000|+6641
telegram=|_1C44148607A814000411A02A5300000840030000000005FF05D83D0000|+6712
telegram=|_1C44148607A814000411A02B5300000840030000000005FF05D83D0000|+6793
telegram=|_1C44148607A814000411A02B5300000840030000000005FF05D83D0000|+6897
telegram=|_1C44148607A814000411A02C5300000840030000000005FF05D83D0000|+6952
telegram=|_1C44148607A814000411A02C5300000840030000000005FF05D83D0000|+7071
telegram=|_1C44148607A814000411A02D5300000840030000000005FF05D83D0000|+7111
telegram=|_1C44148607A814000411A02E5300000840030000000005FF05D83D0000|+7141
telegram=|_1C44148607A814000411A02E5300000840030000000005FF05D83D0000|+7221
telegram=|_1C44148607A814000411A02E5300000840030000000005FF05D83D0000|+7311
telegram=|_1C44148607A814000411A02F5300000840030000000005FF05D83D0000|+7385
telegram=|_1C44148607A814000411A02F5300000840030000000005FF05D83D0000|+7433
telegram=|_1C44148607A814000411A0305300000840030000000005FF05D83D0000|+7473
telegram=|_1C44148607A814000411A0305300000840030000000005FF05D83D0000|+7513
telegram=|_1C44148607A814000411A0305300000840030000000005FF05D83D0000|+7597
telegram=|_1C44148607A814000411A0315300000840030000000005FF05D83D0000|+7603
telegram=|_1C44148607A814000411A0315300000840030000000005FF05D83D0000|+7684
telegram=|_1C44148607A814000411A0325300000840030000000005FF05D83D0000|+7750
telegram=|_1C44148607A814000411A0315300000840030000000005FF05D83D0000|+7761
telegram=|_1C44148607A814000411A0325300000840030000000005FF05D83D0000|+7835
telegram=|_1C44148607A814000411A0325300000840030000000005FF05D83D0000|+7875
telegram=|_1C44148607A814000411A0335300000840030000000005FF05D83D0000|+7912
telegram=|_1C44148607A814000411A0335300000840030000000005FF05D83D0000|+7996
telegram=|_1C44148607A814000411A0345300000840030000000005FF05D83D0000|+8036
telegram=|_1C44148607A814000411A0345300000840030000000005FF05D83D0000|+8095
telegram=|_1C44148607A814000411A0355300000840030000000005FF05D83D0000|+8129
telegram=|_1C44148607A814000411A0355300000840030000000005FF05D83D0000|+8185
telegram=|_1C44148607A814000411A0355300000840030000000005FF05D83D0000|+8225
telegram=|_1C44148607A814000411A0365300000840030000000005FF05D83D0000|+8278
telegram=|_1C44148607A814000411A0365300000840030000000005FF05D83D0000|+8342
telegram=|_1C44148607A814000411A0375300000840030000000005FF05D83D0000|+8399
telegram=|_1C44148607A814000411A0365300000840030000000005FF05D83D0000|+8427
telegram=|_1C44148607A814000411A0375300000840030000000005FF05D83D0000|+8445
telegram=|_1C44148607A814000411A0375300000840030000000005FF05D83D0000|+8530
telegram=|_1C44148607A814000411A0375300000840030000000005FF05D83D0000|+8569
telegram=|_1C44148607A814000411A0385300000840030000000005FF05D83D0000|+8609
telegram=|_1C44148607A814000411A0385300000840030000000005FF05D83D0000|+8678
telegram=|_1C44148607A814000411A0395300000840030000000005FF05D83D0000|+8718
telegram=|_1C44148607A814000411A03A5300000840030000000005FF05D83D0000|+8810
telegram=|_1C44148607A814000411A03B5300000840030000000005FF05D83D0000|+8988
telegram=|_1C44148607A814000411A03B5300000840030000000005FF05D83D0000|+9099
telegram=|_1C44148607A814000411A03D5300000840030000000005FF05D83D0000|+9298
telegram=|_1C44148607A814000411A03E5300000840030000000005FF05D83D0000|+9362
telegram=|_1C44148607A814000411A03E5300000840030000000005FF05D83D0000|+9456
telegram=|_1C44148607A814000411A03E5300000840030000000005FF05D83D0000|+9570
telegram=|_1C44148607A814000411A03F5300000840030000000005FF05D83D0000|+9620
telegram=|_1C44148607A814000411A0415300000840030000000005FF05D83D0000|+9780
telegram=|_1C44148607A814000411A0425300000840030000000005FF05D83D0000|+9970
telegram=|_1C44148607A814000411A0435300000840030000000005FF05D83D0000|+10056
telegram=|_1C44148607A814000411A0445300000840030000000005FF05D83D0000|+10198
telegram=|_1C44148607A814000411A0455300000840030000000005FF05D83D0000|+10365
telegram=|_1C44148607A814000411A0465300000840030000000005FF05D83D0000|+10466
telegram=|_1C44148607A814000411A0465300000840030000000005FF05D83D0000|+10599
telegram=|_1C44148607A814000411A0475300000840030000000005FF05D83D0000|+10691
telegram=|_1C44148607A814000411A0485300000840030000000005FF05D83D0000|+10832
telegram=|_1C44148607A814000411A0495300000840030000000005FF05D83D0000|+11073
telegram=|_1C44148607A814000411A04A5300000840030000000005FF05D83D0000|+11174
telegram=|_1C44148607A814000411A04C5300000840030000000005FF05D83D0000|+11340
telegram=|_1C44148607A814000411A04D5300000840030000000005FF05D83D0000|+11568
telegram=|_1C44148607A814000411A04E5300000840030000000005FF05D83D0000|+11645
telegram=|_1C44148607A814000411A04F5300000840030000000005FF05D83D0000|+11766
telegram=|_1C44148607A814000411A0505300000840030000000005FF05D83D0000|+11988
telegram=|_1C44148607A814000411A0525300000840030000000005FF05D83D0000|+12159
telegram=|_1C44148607A814000411A0535300000840030000000005FF05D83D0000|+12309
telegram=|_1C44148607A814000411A0545300000840030000000005FF05D83D0000|+12495
telegram=|_1C44148607A814000411A0555300000840030000000005FF05D83D0000|+12591
telegram=|_1C44148607A814000411A0555300000840030000000005FF05D83D0000|+12690
telegram=|_1C44148607A814000411A0565300000840030000000005FF05D83D0000|+12789
telegram=|_1C44148607A814000411A0585300000840030000000005FF05D83D0000|+12998
telegram=|_1C44148607A814000411A0585300000840030000000005FF05D83D0000|+13081
telegram=|_1C44148607A814000411A0595300000840030000000005FF05D83D0000|+13185
telegram=|_1C44148607A814000411A05A5300000840030000000005FF05D83D0000|+13345
telegram=|_1C44148607A814000411A05B5300000840030000000005FF05D83D0000|+13445
telegram=|_1C44148607A814000411A05C5300000840030000000005FF05D83D0000|+13600
telegram=|_1C44148607A814000411A05D5300000840030000000005FF05D83D0000|+13674
telegram=|_1C44148607A814000411A05D5300000840030000000005FF05D83D0000|+13794
telegram=|_1C44148607A814000411A05E5300000840030000000005FF05D83D0000|+13856
telegram=|_1C44148607A814000411A05E5300000840030000000005FF05D83D0000|+13955
telegram=|_1C44148607A814000411A05F5300000840030000000005FF05D83D0000|+14046
telegram=|_1C44148607A814000411A0605300000840030000000005FF05D83D0000|+14135
telegram=|_1C44148607A814000411A0615300000840030000000005FF05D83D0000|+14300
telegram=|_1C44148607A814000411A0625300000840030000000005FF05D83D0000|+14468
telegram=|_1C44148607A814000411A0635300000840030000000005FF05D83D0000|+14592
telegram=|_1C44148607A814000411A0645300000840030000000005FF05D83D0000|+14668
telegram=|_1C44148607A814000411A0655300000840030000000005FF05D83D0000|+14822
telegram=|_1C44148607A814000411A0665300000840030000000005FF05D83D0000|+14999
telegram=|_1C44148607A814000411A0675300000840030000000005FF05D83D0000|+15094
telegram=|_1C44148607A814000411A0685300000840030000000005FF05D83D0000|+15295
telegram=|_1C44148607A814000411A0695300000840030000000005FF05D83D0000|+15397
telegram=|_1C44148607A814000411A06A5300000840030000000005FF05D83D0000|+15456
telegram=|_1C44148607A814000411A06B5300000840030000000005FF05D83D0000|+15588
telegram=|_1C44148607A814000411A06A5300000840030000000005FF05D83D0000|+15603
telegram=|_1C44148607A814000411A06C5300000840030000000005FF05D83D0000|+15773
telegram=|_1C44148607A814000411A06D5300000840030000000005FF05D83D0000|+15867
telegram=|_1C44148607A814000411A06E5300000840030000000005FF05D83D0000|+16094
telegram=|_1C44148607A814000411A06F5300000840030000000005FF05D83D0000|+16192
telegram=|_1C44148607A814000411A06F5300000840030000000005FF05D83D0000|+16271
telegram=|_1C44148607A814000411A0705300000840030000000005FF05D83D0000|+16394
telegram=|_1C44148607A814000411A0715300000840030000000005FF05D83D0000|+16544
telegram=|_1C44148607A814000411A0725300000840030000000005FF05D83D0000|+16655
telegram=|_1C44148607A814000411A0735300000840030000000005FF05D83D0000|+16729
telegram=|_1C44148607A814000411A0735300000840030000000005FF05D83D0000|+16905
telegram=|_1C44148607A814000411A0755300000840030000000005FF05D83D0000|+17088
telegram=|_1C44148607A814000411A0765300000840030000000005FF05D83D0000|+17174
telegram=|_1C44148607A814000411A0775300000840030000000005FF05D83D0000|+17361
telegram=|_1C44148607A814000411A0785300000840030000000005FF05D83D0000|+17477
telegram=|_1C44148607A814000411A0795300000840030000000005FF05D83D0000|+17568
telegram=|_1C44148607A814000411A0795300000840030000000005FF05D83D0000|+17699
telegram=|_1C44148607A814000411A07A5300000840030000000005FF05D83D0000|+17762
telegram=|_1C44148607A814000411A07B5300000840030000000005FF05D83D0000|+17896
telegram=|_1C44148607A814000411A07C5300000840030000000005FF05D83D0000|+17979
telegram=|_1C44148607A814000411A07D5300000840030000000005FF05D83D0000|+18156
telegram=|_1C44148607A814000411A07E5300000840030000000005FF05D83D0000|+18281
telegram=|_1C44148607A814000411A07F5300000840030000000005FF05D83D0000|+18486
telegram=|_1C44148607A814000411A0805300000840030000000005FF05D83D0000|+18579
telegram=|_1C44148607A814000411A0815300000840030000000005FF05D83D0000|+18710
telegram=|_1C44148607A814000411A0825300000840030000000005FF05D83D0000|+18897
telegram=|_1C44148607A814000411A0835300000840030000000005FF05D83D0000|+18951
telegram=|_1C44148607A814000411A0835300000840030000000005FF05D83D0000|+19024
telegram=|_1C44148607A814000411A0845300000840030000000005FF05D83D0000|+19159
telegram=|_1C44148607A814000411A0855300000840030000000005FF05D83D0000|+19298
telegram=|_1C44148607A814000411A0865300000840030000000005FF05D83D0000|+19368
telegram=|_1C44148607A814000411A0875300000840030000000005FF05D83D0000|+19488
telegram=|_1C44148607A814000411A0885300000840030000000005FF05D83D0000|+19584
telegram=|_1C44148607A814000411A0885300000840030000000005FF05D83D0000|+19699
telegram=|_1C44148607A814000411A0895300000840030000000005FF05D83D0000|+19837
telegram=|_1C44148607A814000411A08A5300000840030000000005FF05D83D0000|+19968
telegram=|_1C44148607A814000411A08B5300000840030000000005FF05D83D0000|+20074
telegram=|_1C44148607A814000411A08B5300000840030000000005FF05D83D0000|+20192
telegram=|_1C44148607A814000411A08C5300000840030000000005FF05D83D0000|+20276
telegram=|_1C44148607A814000411A08D5300000840030000000005FF05D83D0000|+20332
telegram=|_1C44148607A814000411A08F5300000840030000000005FF05D83D0000|+20561
telegram=|_1C44148607A814000411A0905300000840030000000005FF05D83D0000|+20776
telegram=|_1C44148607A814000411A0915300000840030000000005FF05D83D0000|+20957
telegram=|_1C44148607A814000411A0925300000840030000000005FF05D83D0000|+21094
telegram=|_1C44148607A814000411A0935300000840030000000005FF05D83D0000|+21195
telegram=|_1C44148607A814000411A0945300000840030000000005FF05D83D0000|+21363
telegram=|_1C44148607A814000411A0955300000840030000000005FF05D83D0000|+21493
telegram=|_1C44148607A814000411A0955300000840030000000005FF05D83D0000|+21606
telegram=|_1C44148607A814000411A0975300000840030000000005FF05D83D0000|+21707
telegram=|_1C44148607A814000411A0975300000840030000000005FF05D83D0000|+21862
telegram=|_1C44148607A814000411A0975300000840030000000005FF05D83D0000|+21977
telegram=|_1C44148607A814000411A0A45300000840030000000005FF05D83D0000|+22157
telegram=|_1C44148607A814000411A0B15300000840030000000005FF05D83D0000|+22252
telegram=|_1C44148607A814000411A0B15300000840030000000005FF05D83D0000|+22382
telegram=|_1C44148607A814000411A0B05300000840030000000005FF05D83D0000|+22501
telegram=|_1C44148607A814000411A0B15300000840030000000005FF05D83D0000|+22513
telegram=|_1C44148607A814000411A0B15300000840030000000005FF05D83D0000|+22670
telegram=|_1C44148607A814000411A0C75300000840030000000005FF05D83D0000|+22770
telegram=|_1C44148607A814000411A0E25300000840030000000005FF05D83D0000|+22875
telegram=|_1C44148607A814000411A0F35300000840030000000005FF05D83D0000|+22957
telegram=|_1C44148607A814000411A0015400000840030000000005FF05D83D0000|+23018
telegram=|_1C44148607A814000411A01C5400000840030000000005FF05D83D0000|+23194
telegram=|_1C44148607A814000411A01D5400000840030000000005FF05D83D0000|+23242
telegram=|_1C44148607A814000411A0215400000840030000000005FF05D83D0000|+23370
telegram=|_1C44148607A814000411A0215400000840030000000005FF05D83D0000|+23499
telegram=|_1C44148607A814000411A0215400000840030000000005FF05D83D0000|+23684
telegram=|_1C44148607A814000411A0215400000840030000000005FF05D83D0000|+23811
telegram=|_1C44148607A814000411A0215400000840030000000005FF05D83D0000|+23927
telegram=|_1C44148607A814000411A0215400000840030000000005FF05D83D0000|+24095
telegram=|_1C44148607A814000411A0215400000840030000000005FF05D83D0000|+24361
telegram=|_1C44148607A814000411A0215400000840030000000005FF05D83D0000|+24490

Tell me if it's enough.

**Comment by weetmuts** [comment]
Many thanks! It seems like the first 8 hex bytes in reverse order count 1/3 of a m3.
Pushed new driver apator172 please test!

**Comment by akanegally** [comment]
Hi, I just tried the new driver and it works perfecly

 ./wmbusmeters auto:t1 watermeter apator172 0014a807 NOKEY
Started auto rtlwmbus[00000001] listening on t1
watermeter      0014a807        7265 m3 2022-06-24 21:56.21


Congratulation!

Thank you for all the hard work you guys are doing.

**Comment by weetmuts** [comment]
Yay! Glad to hear that it works!

**Comment by Emmanuel-FR** [comment]
Thank you so much, I was looking very hard to decode these signals and I discovered your work. The most difficult for me was to find the signal because I tried from Windows with my HackRF. Amazing what you can do with a little bit of signal processing !

Cheers
