### ISSUE TITLE
Ha- Addon Link wont work

### ISSUE THREAD

**Issue by niklas007** [weetmuts/wmbusmeters#335]
Navigate to Supervisor > Add-on Store > Repositories
1. Add **https://github.com/weetmuts/wmbusmeters/tree/master/ha-addon**

trying to add the link but it says:

Invalid Add-on repository!

**Comment by asdfghjkai** [comment]
Try https://github.com/weetmuts/wmbusmeters/

Worked for me :)

**Comment by niklas007** [comment]
Thank U :)

su 12. syysk. 2021 klo 22.40 Kai Chance ***@***.***)
kirjoitti:
