### ISSUE TITLE
HA-addon mqtt not working?Pi 4 

### ISSUE THREAD

**Issue by djmalin** [weetmuts/wmbusmeters#337]
Hello, I have a problem with mqtt, it seems the plugin is not sending information to the server,in the folder meter_readings i have 2 files (licznik_ciepła_woda and licznik_zimna_woda)

here is my configuration:

- [Home Assistant OS 6.4
- supervisor-2021.09.0
- core-2021.9.6
- rpi4
- dongle chipset RTL2838 Realteka DVB-T+FM+DAB 820T2 &SDR

config snsors:
`  - platform: "mqtt"
    state_topic: "wmbusmeters/licznik_ciepła_woda"
    json_attributes_topic: "wmbusmeters/licznik_ciepła_woda"
    unit_of_measurement: "m3"
    value_template: "{{ value_json.total_m3 }}"
    name: "czujnik ciepła woda"
    icon: "mdi:gauge"
    
  - platform: "mqtt"
    state_topic: "wmbusmeters/licznik_zimna_woda"
    json_attributes_topic: "wmbusmeters/licznik_zimna_woda"
    unit_of_measurement: "m3"
    value_template: "{{ value_json.total_m3 }}"
    name: "czujnik zimna woda"
    icon: "mdi:gauge" `

config wmbusmeters:
data_path: /config/wmbusmeters
conf: |-
  loglevel=normal
  device=auto
  donotprobe=/dev/ttyAMA0
  listento=c1,t1,s1
  meterfiles=/config/wmbusmeters/logs/meter_readings/
  meterfilesaction=overwrite
  logtelegrams=true
  format=json
  logfile=/config/wmbusmeters/wmbusmeters.log
  shell=/wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"
meters:
  - |-
    name=licznik_ciepła_woda
    driver=auto
    id=00238332
    key=00000000000000000000000000000000
  - |-
    name=licznik_zimna_woda
    driver=auto
    id=00233274
    key=00000000000000000000000000000000
mqtt:
  host: mqtt://core-mosquitto
  port: 1883
  user: xxx
  password: xxxx

**Comment by weetmuts** [comment]
Can you look inside /config/wmbusmeters/wmbusmeters.log and post it here?

@to-masz

**Comment by to-masz** [comment]
@djmalin 
1. I would like to ask you to fix the formatting of your config 😉 
2. I really recommend a tool like MQTT Explorer to debug where the data goes
3. What do you see in the add-on logs?

**Comment by weetmuts** [comment]
Closing stale issue.
