### ISSUE TITLE
Please add Support

### ISSUE THREAD

**Issue by wiesel24** [weetmuts/wmbusmeters#340]
Hi all,
sorry to bother you. I've tried to add my water meter into HA with wmbusmeters add-on but he is telling me in the log files that the Water meter has unknown driver?
It's a Diehl Water Meter so I don't why it isn't the izar driver? In the logs it shows me following lines:
(meter) Water: meter detection could not find driver for id: 1800**** mfct: (HYD) Hydrometer (0x2324) type: Water meter (0x07) ver: 0x85
(meter) please consider opening an issue at https://github.com/weetmuts/wmbusmeters/
(meter) to add support for this unknown mfct,media,version combination
Pictures of the meter
![IMG_20210919_210749__01](https://user-images.githubusercontent.com/18354209/133939937-00ab47dc-6a04-40cf-a354-9907dbcc0a95.jpg)
![IMG_20210919_210814](https://user-images.githubusercontent.com/18354209/133939943-60f07fbe-79b2-46b9-b808-56c6f6c4e9b2.jpg)
:
Here is also one Telegram Message from the log ->
What I've maybe forgot to paste is the Telegram Message
Received telegram from: ********
manufacturer: (HYD) Hydrometer (0x2324)
type: Water meter (0x07)
ver: 0x85
device: rtlwmbus[00000001]
rssi: 29 dBm
driver: unknown!
telegram=||19442423850798160018A2410100133EBBD44081053F243A82A3|+37

Also got now the debug message for the Telegrams that this Meter sends:

./wmbusmeters --debug 19442423850798160018A2510100133EEFFA092A24ECFDE19BA1
(wmbusmeters) version: 1.4.1-25-g0788ad7
(config) using device: <19442423850798160018A2510100133EEFFA092A24ECFDE19BA1>:any 
(config) number of meters: 0
(lookup) with file/hex "19442423850798160018A2510100133EEFFA092A24ECFDE19BA1"
(lookup) driver: simulation hex
(main) opening <19442423850798160018A2510100133EEFFA092A24ECFDE19BA1>:any
Started config simulation listening on any
(simulation) in 
(main) regular reset of simulation  will happen every 82800 seconds
(main) added  to files
(wmbus) no alarm (expected activity) for simulation
(lookup) with file/hex "19442423850798160018A2510100133EEFFA092A24ECFDE19BA1"
(lookup) driver: simulation hex
(main) opening <19442423850798160018A2510100133EEFFA092A24ECFDE19BA1>:any
Started config simulation listening on any
(simulation) in 
(main) regular reset of simulation  will happen every 82800 seconds
(main) added  to files
(wmbus) no alarm (expected activity) for simulation
(serial) registered regular callback HOT_PLUG_DETECTOR(0) every 2 seconds
No meters configured. Printing id:s of all telegrams heard!
(simulation) from file "19442423850798160018A2510100133EEFFA092A24ECFDE19BA1"
(diehl) preprocess necessary SWAPPING
(diehl) Pre-processing: swapping address field
(wmbus) parseDLL @0 26
(telegram) DLL L=19 C=44 (from meter SND_NR) M=2324 (HYD) A=****** VER=85 TYPE=07 (Water meter) (driver unknown!) DEV= RSSI=0
(wmbus) parseELL @10 16
(wmbus) parseAFL @10 16
(wmbus) parseTPL @10 16
(telegram) TPL CI=a2
Received telegram from: *******
          manufacturer: (HYD) Hydrometer (0x2324)
                  type: Water meter (0x07)
                   ver: 0x85
                driver: unknown!
(wmbus) 00: 19 length (25 bytes)
(wmbus) 01: 44 dll-c (from meter SND_NR)
(wmbus) 02: 2423 dll-mfct (HYD)
(wmbus) 04: 98160018 dll-id (*******)
(wmbus) 08: 85 dll-version
(wmbus) 09: 07 dll-type (Water meter)
(wmbus) 0a: a2 tpl-ci-field (Mfct specific)
telegram=||19442423850798160018A2510100133EEFFA092A24ECFDE19BA1|+0
(serial) stopping manager
(simulation) from file "19442423850798160018A2510100133EEFFA092A24ECFDE19BA1"
(wmbus) skipping already handled telegram.
(serial) waiting for stop
(serial) event loop stopped!
(wmbus) deleted simulation
(wmbus) deleted simulation

Maybe you can add this to the HA add-on.
Thank you in advance!
Regards 
Wiesel

**Comment by wiesel24** [comment]
What I've maybe forgot to paste is the Telegram Message
Received telegram from: ********
          manufacturer: (HYD) Hydrometer (0x2324)
                  type: Water meter (0x07)
                   ver: 0x85
                device: rtlwmbus[00000001]
                  rssi: 29 dBm
                driver: unknown!
telegram=||19442423850798160018A2410100133EBBD44081053F243A82A3|+37

**Comment by weetmuts** [comment]
Thanks for the report! Your telegram decodes nicely with the izar driver. 
I have added your meters particular mfct/type/version combo to the detection table for izar.

Please test!

**Comment by wiesel24** [comment]
Wow! Thank you! You've some contribution Button? Buy me a coffee?
Regards

**Comment by weetmuts** [comment]
@wiesel24 Thanks! I might add a sponsor button in future!
