### ISSUE TITLE
Detect Raspberry PI and avoid probing /dev/ttyAMA0

### ISSUE THREAD

**Issue by weetmuts** [weetmuts/wmbusmeters#345]
Some raspberry PIs goes into high CPU usage everything stops when wmbusmeters
sends some probe bytes to /dev/ttyAMA0. 

Add code to wmbusmeters to detect raspberry pi and avoid probing /dev/ttyAMA0

**Comment by BIBOLV** [comment]
`donotprobe` was implemented and added information in readme to use it on raspi's. IMO it is sufficient, or you want to continue to develop this topic? @weetmuts

**Comment by weetmuts** [comment]
I think we can close this one.
