### ISSUE TITLE
Dongle freezes after few readings

### ISSUE THREAD

**Issue by tomasz8w** [weetmuts/wmbusmeters#359]
Hi, 
First of all, thank you for this great project.

I decided to open an issue because I'm facing weird problem. wmbusmeters is properly decoding 9 telegrams then in debug log I see lines like this below:

```
(serial) received ascii "Tuned to 868.950MHz.<0A>Allocating 15 zero-copy buffers<0A>"
(rtl433) checkRTL433Frame "Tuned to 868.950MHz.<0A>Allocating 15 zero-copy buffers<0A>"
(rtl433) checkRTL433Frame "Allocating 15 zero-copy buffers<0A>"
```

After that for 10 minutes nothing is happenning. And then again, I'm receiving 9 telegrams. It is pretty accurate.

I found that resetting service solves the issue (no need to wait 10 minutes to start receiving telegrams again).
But also I found, that resetting it too frequently will hang the dongle and only reattaching it will bring it back to life.

My config is simple: 
device=rtl433:t1

and in rtl433.conf:

sample_rate   1.6e6
frequency     868.41M

Dongle: LV5T Deluxe with Fitipower fc0013 tuner

**Comment by weetmuts** [comment]
@tomasz8w If you run with --debug you should be able to see the exact command line used to spawn rtl_433.

**Comment by merbanan** [comment]
It is the 2 frequency parameters that cause this. Remove the config file and use the frequency that worked for you.
