### ISSUE TITLE
meter amiplus return `nan` in json

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [weetmuts/wmbusmeters#361]
My `amiplus` electricity meter has been improved by reporting voltages at phases (commits e2acfe88fa65384495888a6be06444031c30993c, 0368a70fbd283aeae6c66da6f4add4309c8b43b1, 3baeb3b2438af3bc6ec43e7a2c34609e10a2c13d, 9b6638d6dc01ed52ea5bcad203b93dcfd5be9204)

Unfortunately, this leads to invalid json:  
`{"media":"electricity","meter":"amiplus","name":"myhome","id":"12345678","total_energy_consumption_kwh":8803.554,"current_power_consumption_kw":0.239,"total_energy_production_kwh":2.291,"current_power_production_kw":0,"voltage_at_phase_1_v":231,"voltage_at_phase_2_v":nan,"voltage_at_phase_3_v":nan,"device_date_time":"2021-10-12 22:49","timestamp":"2021-10-12T20:49:03Z","device":"rtl433[00000001]","rssi_dbm":999}`  
According to https://jsonlint.com error is around `nan` values:
```
Error: Parse error on line 11:
...tage_at_phase_2_v": nan,	"voltage_at_ph
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

In my opinion, we should return `NULL`, `0` or something, that is actually both valid and consistent with previously returned values (so other tools won't be confused why data format changed in published message)

**Comment by weetmuts** [comment]
Yes, we should generate proper json. Either we should not print the "key":"values" for things
that do not exist in the telegram, or we should print 0 or some other improbable value.

I suggest 0, for now. There is no support right now for >not< printing the values specified with addPrint.

Can you fix both drivers @DeDragonSlayer  ?
