### ISSUE TITLE
Send shell telegram

### ISSUE THREAD

**Issue by spiri439** [weetmuts/wmbusmeters#365]
Is there a possibility to send the telegram through shell? Or can this be added?

Thanks

**Comment by pswiatki** [comment]
Hmmm..... how about using rtl_wmbus and (perhaps) some shell wizardry, such as tee?

**Comment by weetmuts** [comment]
You can send the rtl_wmbus telegrams using UDP over the network to wmbusmeters, like this:

rtl_sdr -f 868.95M -s 1600000 - 2>/dev/null | rtl_wmbus -p s -a | nc -u localhost 4444

wmbusmeters 'rtlwmbus:CMD(nc -lku 4444)'

**Comment by spiri439** [comment]
> > thanks, it perfect for what I need
> 
> Perhaps a star could be in order? ;-)

of course :)
