### ISSUE TITLE
Support for Qundis Q heat 5.5 heat meter

### ISSUE THREAD

**Issue by maha858** [weetmuts/wmbusmeters#369]
I have a Qundis Q heat 5.5 heat meter with attached radio converter https://qundis.de/wp-content/uploads/2019/12/DST3-QHEA-DE0-HMx_051219_V5_FINAL.pdf which I assume is currently not supported?

Log file entries read

[2021-10-19_23:56:38] (meter) Heizung: meter detection could not find driver for id: 67227964 mfct: (QDS) Qundis, Germany (0x4493) type: Heat meter (0x04) ver: 0x23

I have also captured a telegram like

Received telegram from: 37027095
          manufacturer: (QDS) Qundis, Germany (0x4493)
                  type: Radio converter (meter side) (0x37)
                   ver: 0x23
      Concerning meter: 67228058
          manufacturer: (QDS) Qundis, Germany (0x4493)
                  type: Heat meter (0x04)
                   ver: 0x23
                device: im871a[00101904]
                  rssi: -79 dBm
                driver: unknown!
telegram=||3C449344957002372337725880226793442304DC0000200C05043900004C0500000000426C9F2CCC080551070000C2086CBE29326CFFFF046D280DB62A|+210

Is there anything eles I need to capture for potential support for this device?

Thanks & regards
Marcus

**Comment by ewoks** [comment]
any guidance how to read data from it? I see device has [Funkaufsatz module](https://qundis.de/download/29625/) but no idea is it possible to read it for tracking my data regulary. Thanks
