### ISSUE TITLE
Receiving telegram from iperl water meter but no data

### ISSUE THREAD

**Issue by matkor** [weetmuts/wmbusmeters#370]
I am able to receive telegrams from my iperl water meter like:
```
telegram=||1E44AE4C9465232168077A1200100544FA9D402576E578E71D3C548783B8F9|+19017
(telegram) DLL L=1e C=44 (from meter SND_NR) M=4cae (SEN) A=21236589 VER=68 TYPE=07 (Water meter) (driver iperl) DEV=rtlwmbus[00000001] RSSI=136
(telegram) TPL CI=7a ACC=12 STS=00 CFG=0510 (AES_CBC_IV nb=1 cntn=0 ra=0 hc=0)
Received telegram from: 21236589
          manufacturer: (SEN) Sensus Metering Systems, Germany (0x4cae)
                  type: Water meter (0x07)
                   ver: 0x68
                device: rtlwmbus[00000001]
                  rssi: 136 dBm
                driver: iperl

```
but seems there is no data (like flow/ m³ counter)?
Does it mean readings are encrypted? If so, how decryption key should look like, I will try to get it from my water provider :)
21236589 is printed on my meter so I assume that it is S/N.

Sorry for asking there, but seems there is no relevant FAQ entry nor forum.

**Comment by weetmuts** [comment]
From the README under Usage Examples with your meter id:
```
wmbusmeters auto:c1 MyTapWater auto 21236589 00112233445566778899AABBCCDDEEFF
```
Your key is a 32 char hex string like 0011....EEFF above.

Good luck!
