### ISSUE TITLE
How can I test it with RTL2838 ?

### ISSUE THREAD

**Issue by koansoftware** [weetmuts/wmbusmeters#372]
I am using an USB adapter from Amaz0n
Nooelec NESDR Mini 2 USB RTL-SDR and Receiver ADS-B Set, Synto RTL2832U e R820T2

```
$ lsusb
Bus 001 Device 008: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
```

It works with **rtl_433**

```
$ ./src/rtl_433 -F json -s 1600k
rtl_433 version 21.05-115-gb4c5711c branch master at 202110241007 inputs file rtl_tcp RTL-SDR with TLS
Registered 169 out of 199 device decoding protocols [ 1-4 8 11-12 15-17 19-23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 151-161 163-168 170-175 177-197 199 ]
Detached kernel driver
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Sample rate set to 1600000 S/s.
Tuner gain set to Auto.
Tuned to 433.920MHz.
baseband_demod_FM: low pass filter for 1600000 Hz at cutoff 160000 Hz, 6.2 us
{"time" : "2021-10-25 17:56:00", "model" : "Renault", "type" : "TPMS", "id" : "c280ea", "flags" : "30", "pressure_kPa" : 260.250, "temperature_C" : 23.000, "mic" : "CRC"}
{"time" : "2021-10-25 17:56:03", "model" : "AmbientWeather-TX8300", "id" : 59, "channel" : 3, "battery" : 2, "temperature_C" : 14.100, "mic" : "CHECKSUM"}
{"time" : "2021-10-25 17:56:04", "model" : "Renault", "type" : "TPMS", "id" : "c37b21", "flags" : "30", "pressure_kPa" : 268.500, "temperature_C" : 39.000, "mic" : "CRC"}
```

It doesn't work with **wmbusmeters**
(commit d1d9e732831274291ec8cf6888cc60232bb57596)

```
wmbusmeters auto:t1
Started auto rtlwmbus[00000001] listening on t1
No meters configured. Printing id:s of all telegrams heard!
Lost 00000001 closing rtlwmbus[00000001]
Started auto rtlwmbus[00000001] listening on t1
Lost 00000001 closing rtlwmbus[00000001]
Started auto rtlwmbus[00000001] listening on t1
```

I'm not sure to set the proper device.
How can I test it with **wmbusmeters** ?
Thanks

**Comment by thecem** [comment]
I have the same problem with the HA Addon (RPI3B) with Nooelec NESDR SMArt v4 with RTL2832U Demodulator/USB interface IC and
R820T2 tuner IC  :

Device:
```
BUSNUM: '001'
DEVNAME: /dev/bus/usb/001/004
DEVNUM: '004'
DEVPATH: /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3
DEVTYPE: usb_device
DRIVER: usb
ID_BUS: usb
ID_FOR_SEAT: usb-platform-3f980000_usb-usb-0_1_3
ID_MODEL: RTL2838UHIDIR
ID_MODEL_ENC: RTL2838UHIDIR
ID_MODEL_ID: '2838'
ID_PATH: platform-3f980000.usb-usb-0:1.3
ID_PATH_TAG: platform-3f980000_usb-usb-0_1_3
ID_REVISION: '0100'
ID_SERIAL: Realtek_RTL2838UHIDIR_00000001
ID_SERIAL_SHORT: '00000001'
ID_USB_INTERFACES: ':ffffff:'
ID_VENDOR: Realtek
ID_VENDOR_ENC: Realtek
ID_VENDOR_ID: 0bda
MAJOR: '189'
MINOR: '3'
PRODUCT: bda/2838/100
SUBSYSTEM: usb
TAGS: ':seat:'
TYPE: 0/0/0
USEC_INITIALIZED: '7967660'
```
HA-Addon-Log:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Syncing wmbusmeters configuration ...
Registering meters ...
Generating MQTT configuration ... 
Broker 192.168.76.100 will be used.
Running wmbusmeters ...
No such log level: "normaldevice=auto:t1logtelegrams=falseformat=jsonlogfile=/dev/stdoutshell=/wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON""
No wmbus device detected, waiting for a device to be plugged in.
No meters configured. Printing id:s of all telegrams heard!
```
Config:

`loglevel=normaldevice=auto:t1logtelegrams=falseformat=jsonlogfile=/dev/stdoutshell=/wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"`

Is the rtl_wmbus in HA-Addon installed?
Do I have to install something else?
Is the config line correct?
Meters will be two 303 Kamstrup (heat meter, thermal energy meter, calorimeter).

**Comment by silkyclouds** [comment]
I have the same 'rafael' dongle and here is the output :

root@DietPi:/opt/rtl-wmbus/build# wmbusmeters rtl433:t1
Started config rtl433[00000001] listening on t1
No meters configured. Printing id:s of all telegrams heard!
Lost 00000001 closing rtl433[00000001]
Started config rtl433[00000001] listening on t1
Lost 00000001 closing rtl433[00000001]
Started config rtl433[00000001] listening on t1
Lost 00000001 closing rtl433[00000001]
Started config rtl433[00000001] listening on t1
Lost 00000001 closing rtl433[00000001]
Started config rtl433[00000001] listening on t1
Lost 00000001 closing rtl433[00000001]
Started config rtl433[00000001] listening on t1
Lost 00000001 closing rtl433[00000001]
Started config rtl433[00000001] listening on t1
Lost 00000001 closing rtl433[00000001]
Started config rtl433[00000001] listening on t1
Lost 00000001 closing rtl433[00000001]
Started config rtl433[00000001] listening on t1


what can I do to solve this ?

**Comment by rmoriz** [comment]
having the same issues with the Neolec and HAOS.  /usr/bin/rtl_wmbus is present, so is the USB device.

UPDATE: okay the issue is solved. I entered the docker container on HAOS and tried to use supplied wmbusmeters but the wmbusmetersd daemon is already running and receiving telegrams. hence the CLI fails. `docker logs -f` shows the detected telegrams
