### ISSUE TITLE
Watermeter Cyble HRF 868MHz v5.2

### ISSUE THREAD

**Issue by Anas92230** [weetmuts/wmbusmeters#375]
Hi :-) I have a watermeter based on itron watermeter. When I launch wmbusmeter I can't detect any informations. My hardware :
Ubuntu 20.04
Nooelec NESDR SMArt v4
Command: rtl_sdr -f 868.95M -s 1.6e6 - | rtl_wmbus
Thanks for help

**Comment by weetmuts** [comment]
Does it say that the meter is wmbus compatible or an OMS meter? Otherwise it might use their own protocol, 
just on the 868 MHz frequency? http://www.lamaisonsimon.fr/wiki/doku.php?id=maison2:compteur_d_eau:compteur_d_eau

What happens if you use run "rtl_433 -f 868.95M" instead?

**Comment by weetmuts** [comment]
It could also be a two way protocol, like this Itron meter: https://github.com/weetmuts/wmbusmeters/issues/346

**Comment by Anas92230** [comment]
Thank you for your help. I just launch rtl_433 -f 868.95M -s 1.6e6. If I catch anything i'll tell you

**Comment by Anas92230** [comment]
Hello
I don't detect any telegram. When I launch sharp I can see lot of signal bêtement 867 and 900MHz.

**Comment by weetmuts** [comment]
Is this tool the right tool for you? https://github.com/bemasher/rtlamr

**Comment by Anas92230** [comment]
Thanks i'm going to test it
