### ISSUE TITLE
Warning! Auto scan has found an rtl_sdr dongle, but you have no rtl_wmbus in the path!

### ISSUE THREAD

**Issue by charugaa** [weetmuts/wmbusmeters#380]
Warning! Auto scan has found an rtl_sdr dongle, but you have no rtl_wmbus in the path!

**Comment by weetmuts** [comment]
Please read the README.  Compile and install rtl_wmbus https://github.com/xaelsouth/rtl-wmbus

**Comment by chrigabr** [comment]
Hello, I have same Problem too. I don't undestand. 

"Warning! Auto scan has found an rtl_sdr dongle, but you have no rtl_wmbus in the path!" What can I do? 

And when I do sudo wmbusmeters --debug --t1 rtlwmbus, I have this:

_(shell) return code 1
(shell) 1538 exited
(serial) EVENT thread interrupted
(main) rtl_srd found in path
(shell) exec (capture output) "/bin/sh"
(shell) arg "-c"
(shell) arg "rtl_wmbus < /dev/null"
(shell) output: >>>/bin/sh: 1: rtl_wmbus: Permission denied
<<<
(shell) return code 127
(shell) 1540 exited
(main) rtl_wmbus NOT found in path
Warning! Auto scan has found an rtl_sdr dongle, but you have no rtl_wmbus in the path!
(serial) EVENT thread interrupted_
 
Many thanks
Christian GABRIEL

**Comment by franciozzy** [comment]
> (shell) output: >>>/bin/sh: 1: rtl_wmbus: Permission denied

This means you do not have permissions to execute rtl_wmbus. That could have happened if you didn't install it properly.
Try: `sudo chmod 755 $(which rtl_wmbus)`

**Comment by juergen908** [comment]
> Hello, I have same Problem too. I don't undestand.
> 
> "Warning! Auto scan has found an rtl_sdr dongle, but you have no rtl_wmbus in the path!" What can I do?
> 
> And when I do sudo wmbusmeters --debug --t1 rtlwmbus, I have this:
> 
> (shell) return code 1 
> (shell) 1538 exited 
> (serial) EVENT thread interrupted 
> (main) rtl_srd found in path 
> (shell) exec (capture output) "/bin/sh" 
> (shell) arg "-c" 
> (shell) arg "rtl_wmbus < /dev/null" 
> (shell) output: >>>/bin/sh: 1: rtl_wmbus: Permission denied <<< 
> (shell) return code 127 
> (shell) 1540 exited 
> (main) rtl_wmbus NOT found in path Warning! Auto scan has found an rtl_sdr dongle, but you have no rtl_wmbus in the path! 
> (serial) EVENT thread interrupted_
> 
> Many thanks Christian GABRIEL

Something makes me wondering:
Sometimes it is written "SDR" and sometimes "SRD".
Whats wrong with it ?

But i have still the Problem:
"Warning! Auto scan has found an rtl_sdr dongle, but you have no rtl_wmbus in the path! "
on Raspi4b.
Can someone help me ? 
I have not much experience on Raspi...
Maybe someone in German ?
