### ISSUE TITLE
ITRON Water: driver unknown

### ISSUE THREAD

**Issue by docbobo** [weetmuts/wmbusmeters#396]
Not sure if you are interested in this, but I am receiving telegrams from lots of devices, the majority not being mine ;) Here's an item I noticed this morning:

> Received telegram from: 10048844
          manufacturer: (ITW) ITRON Water, France (0x2697)
                  type: Heat Cost Allocator (0x08)
                   ver: 0x01
                device: rtlwmbus[00000001]
                  rssi: 34 dBm
                driver: unknown!
telegram=||2E4497264488041001087AD80320A51B90A9D00C333D5812196B8F2F1BC82455B8F29CB356AF8CC8B1EE5C97653379|+25438

**Comment by weetmuts** [comment]
Thanks! But since the content is encrypted, we cannot do much about this right now.
