### ISSUE TITLE
amb8465: No wmbus device detected

### ISSUE THREAD

**Issue by docbobo** [weetmuts/wmbusmeters#408]
Just bought an AMB8456 device, which lists as  `0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC`. When starting wmbusmeter, the log says

`No wmbus device detected, waiting for a device to be plugged id`

This happens with both auto as well as using the /dev/* link. Some help would be appreciated.

**Comment by weetmuts** [comment]
Lets merge this into this issue. https://github.com/weetmuts/wmbusmeters/issues/388 
Please repost your issue there. Thanks!
