### ISSUE TITLE
wmbusmeters stdin:rtlwmbus not fully working?

### ISSUE THREAD

**Issue by MaxPeal** [weetmuts/wmbusmeters#423]
i captured 15m signals with rtl_sdr
`timeout --preserve-status 15m rtl_sdr -f 868.625M -s 1600000 - 2>/dev/null | tee rtl_wmbus-samples_2021-12-29-14.bin | rtl_wmbus -s | tee rtl_wmbus-samples_2021-12-29-14.bin.decode`

and get 2741 telegrams, 2705 unic
`cat rtl_wmbus-samples_2021-12-29-14.bin.decode | sort -u| wc -l`

but i get only this  
```
$ cat rtl_wmbus-samples_2021-12-29-14.bin.decode | $wmbusmeters stdin:rtlwmbus 
Started config rtlwmbus on stdin listening on any
No meters configured. Printing id:s of all telegrams heard!
Received telegram from: 80391788
          manufacturer: (KAM) Kamstrup Energi (0x2c2d)
                  type: Heat meter (0x04) encrypted
                   ver: 0x35
                device: rtlwmbus[]
                  rssi: 73 dBm
                driver: multical603
Received telegram from: 72172368
          manufacturer: (DME) DIEHL Metering, Germany (0x11a5)
                  type: Water meter (0x07) encrypted
                   ver: 0x76
                device: rtlwmbus[]
                  rssi: 16 dBm
                driver: unknown!
Received telegram from: 93843999
          manufacturer: (TCH) Techem Service (0x5068)
                  type: Smoke detector (0xf0)
                   ver: 0x76
                device: rtlwmbus[]
                  rssi: 124 dBm
                driver: tsd2
$
```
```
wmbusmeters --version
wmbusmeters: 1.5.0-35-g6a4266e
6a4266ead640272757d21005ab4faa5aecce5d93
```

**Comment by weetmuts** [comment]
What do the lines in rtl_wmbus-samples_2021-12-29-14.bin.decode start with?

If they start with T1;0 or C1;0 or S1:0 then a signal was received but the crc failed,
so wmbusmeters ignores them, rightly so, since they are corrupt.

Only lines with T1;1 or C1;1 or S1;1 are used.

**Comment by weetmuts** [comment]
Ah, you have created two issues.... check the https://github.com/weetmuts/wmbusmeters/issues/424
for the solution. I think we can close this as a duplicate.

**Comment by MaxPeal** [comment]
closing in favor of https://github.com/weetmuts/wmbusmeters/issues/426
