### ISSUE TITLE
Range of Cul (vs iM871A-USB)

### ISSUE THREAD

**Issue by SWAT9119** [weetmuts/wmbusmeters#475]
Hello,

I know it´s no origin wmbusmeters thema, but I wanted to know if someone has expirience with the range of cul vs iM871A-USB.

I have a cul with an external antenna (https://www.smart-home-komponente.de/nano-cul/nano-cul-868-extern/) but the range is very very bad, I can´t get the messages over 2 floors. Has the iM871A-USB a better range?

Can the range of the cul be extended (by setting more power?)

Thank you in advance!

**Comment by weetmuts** [comment]
That is indeed my experience as well. https://weetmuts.github.io/wmbusmeterswiki/ANTENNA.html
