### ISSUE TITLE
Decoding telegrams  from WebDyn Gateway

### ISSUE THREAD

**Issue by joergwulf** [weetmuts/wmbusmeters#488]
We use a commercial gateway (WebDyn) to receive WMBus meter data and transfer the results to an FTP server.
The data is stored as BSON files. These can be converted into JSON. The result is:
![image](https://user-images.githubusercontent.com/75932520/156526705-951520be-d380-40b3-86b1-d18acd5ceff3.png)
Now we pass the coded part of the meter as parameter:
`/snap/wmbusmeters/current/usr/bin/wmbusmeters 077983561523934433060dff5f3500829700005f0107c113ffff08990000bf2c55860000df21508900000500260049004c00640027006a00c1006900000062001e002f046d1c10dc22`
The result is
![image](https://user-images.githubusercontent.com/75932520/156527263-b5481607-b386-47f2-8f96-916ff2dd58c7.png)
We assume that wmbusmeters needs the whole coded telegram and when passing the payload of the meter the meta data is missing.
Is there any way to decode this telegram?

**Comment by joergwulf** [comment]
The problem has been solved. The tool from Webdyn already does more than necessary for this issue. We have to use the data from the JSON output
![image](https://user-images.githubusercontent.com/75932520/156545579-20d82121-7fa0-4e58-8c78-b102be0cfa92.png)
converting Base64 to Hex
`4e44a5116160316170077a1f3040050d7ede5f0e1ec9dc6226ee3c13469e4f59832d4681833960f039e707971b1570555eb6fe11f955e99eea5ea03f37954f05f33cb5edc08348fe7c838ded5a605e`
and put it into wmbusmeters
![image](https://user-images.githubusercontent.com/75932520/156545992-cbabee32-8b9f-4cf8-94a7-fd970f917df7.png)
..then get the id from the output and get the consumption data
![image](https://user-images.githubusercontent.com/75932520/156546411-d22045ce-d045-40f0-9c27-2859bbdd3519.png)
Great tool !
Ist ist possible to get the consumption data with one call (without determining the ID from the first call) ?

**Comment by rattinca** [comment]
usually you have the id of your meters beforehand. Its also in the telegram, that part is never encoded.

**Comment by Germar** [comment]
You can use wildcard `"*"` for the meter_id
```
wmbusmeters --format=json 4e44a5116160316170077a1f3040050d7ede5f0e1ec9dc6226ee3c13469e4f59832d4681833960f039e707971b1570555eb6fe11f955e99eea5ea03f37954f05f33cb5edc08348fe7c838ded5a605e MyMeter auto "*" NOKEY
{"media":"water","meter":"hydrus","name":"MyMeter","id":"61316061","total_m3":50.813,"total_tariff1_m3":0,"total_tariff2_m3":0,"max_flow_m3h":0,"flow_temperature_c":24.3,"external_temperature_c":0,"current_date":"","total_at_date_m3":50.813,"total_tariff1_at_date_m3":0,"total_tariff2_at_date_m3":50.813,"at_date":"2021-12-31 00:00","actuality_duration_s":0,"operating_time_h":0,"remaining_battery_life_y":10.080767,"status":"TEMPORARY_ERROR AIR_IN_PIPE","timestamp":"2022-03-05T20:47:29Z"}
```

**Comment by weetmuts** [comment]
Or ANYID which was introduced since * can be difficult to quote in shells inside shells etc...

**Comment by joergwulf** [comment]
"*" works, but ANYID or anyid not:
![image](https://user-images.githubusercontent.com/75932520/157038576-34073a49-dc8c-485f-96a2-8a2f80bd9b92.png)
Version is 1.6.0

**Comment by weetmuts** [comment]
@joergwulf Great that you like wmbusmeters!

Now you can run "wmbusmeters --analyze <telegram> on the web.
https://wmbusmeters.org

It is the same output as from the command line, but it is more convient when
you just want to check the content of the telegram.

You can jump directly to your telegram like this:
https://wmbusmeters.org/analyze/4e44a5116160316170077a1f3040050d7ede5f0e1ec9dc6226ee3c13469e4f59832d4681833960f039e707971b1570555eb6fe11f955e99eea5ea03f37954f05f33cb5edc08348fe7c838ded5a605e

As you can see the hydrus driver misses four fields (marked as red) if you can explain the contents of these fields (well the first is obvious), then we can add them to the json as well.
