### ISSUE TITLE
Missing device mfct: (TCH) - 0x5068 type Heat meter (0x4) ver: 0x17 vario 4 Typ 4.5.1 

### ISSUE THREAD

**Issue by JensHoRi** [weetmuts/wmbusmeters#500]
Here the debug, sadly with snap-Version I have no idea how to create a source on my own:

`(meter) HeizungDG: for me? 94430412 in 94430412
(meter) HeizungDG: meter detection did not match the selected driver vario451! correct driver is: unknown!
(meter) Not printing this warning again for id: 94430412 mfct: (TCH) Techem Service (0x5068) type: Heat meter (0x04) ver: 0x17
(meter) please consider opening an issue at https://github.com/weetmuts/wmbusmeters/
(meter) to add support for this unknown mfct,media,version combination
(meter) HeizungDG: yes for me
(meter) HeizungDG vario451 handling telegram from 94430412
(meter) HeizungDG 94430412 "734468501204439417048C0084900F002C2536700000B767B64527C50AC67A3300500710555E337738056E1340D0919703C0DE6C786C316C7C2406D0782E6FA6ACE55372E55E984F4679DF8D3C23AB88C303E21C34420D0CD080E75C4CE936E714D38CBCFE333EA01EF5C9F982006E352199ED68"
(wmbus) parseDLL @0 116
(telegram) DLL L=73 C=44 (from meter SND_NR) M=5068 (TCH) A=94430412 VER=17 TYPE=04 (Heat meter) (driver unknown!) DEV=amb8465[00000000] RSSI=-22
(wmbus) parseELL @10 106
(telegram) ELL CI=8c CC=00 (slow_resp) ACC=84
(wmbus) parseNWL @13 103
(wmbus) parseAFL @13 103
(telegram) AFL CI=90
(wmbus) parseTPL @30 86
(wmbus) input to kdf for enc "00367000001204439407070707070707"
(wmbus) ephemereal Kenc 1147F6EDA055BB8133E949490B390902
(wmbus) input to kdf for mac "01367000001204439407070707070707"
(wmbus) ephemereal Kmac 7D3DA4E4B5C096ACF40996FB6AC4897B
(wmbus) input to mac 25367000007A3300500710555E337738056E1340D0919703C0DE6C786C316C7C2406D0782E6FA6ACE55372E55E984F4679DF8D3C23AB88C303E21C34420D0CD080E75C4CE936E714D38CBCFE333EA01EF5C9F982006E352199ED68
(wmbus) calculated mac B767B64527C50AC6E8D031F34AF6E934
(wmbus) received   mac B767B64527C50AC6
(wmbus) mac ok!
(TPL) AES CBC NO IV decrypting "555E337738056E1340D0919703C0DE6C786C316C7C2406D0782E6FA6ACE55372E55E984F4679DF8D3C23AB88C303E21C34420D0CD080E75C4CE936E714D38CBCFE333EA01EF5C9F982006E352199ED68"
(TPL) num encrypted blocks 5 (80 bytes and remaining unencrypted 0 bytes)
(TPL) IV 00000000000000000000000000000000
(TPL) decrypted  "2F2F8404062846000082046C9F2C8D04861F1E72FE00000000000000000000000000000000000000000000000000000000440600000000426CFFFF0406C94700002F2F2F2F2F2F2F2F2F2F2F2F2F2F2F"
(telegram) TPL CI=7a ACC=33 STS=00 CFG=0750 (AES_CBC_NO_IV)
telegram=|73 44 6850 12044394 17 04 8C 00 84 90 0F002C2536700000B767B64527C50AC67A33005007102F2F|8404062846000082046C9F2C8D04861F1E72FE00000000000000000000000000000000000000000000000000000000440600000000426CFFFF0406C94700002F2F2F2F2F2F2F2F2F2F2F2F2F2F2F|+144
(vario451) 000   : 73 length (115 bytes)
(vario451) 001   : 44 dll-c (from meter SND_NR)
(vario451) 002   : 6850 dll-mfct (TCH)
(vario451) 004   : 12044394 dll-id (94430412)
(vario451) 008   : 17 dll-version
(vario451) 009   : 04 dll-type (Heat meter)
(vario451) 010   : 8c ell-ci-field (ELL: Extended Link Layer I (2 Byte))
(vario451) 011   : 00 ell-cc (slow_resp)
(vario451) 012   : 84 ell-acc
(vario451) 013   : 90 afl-ci-field (AFL: Authentication and Fragmentation Sublayer)
(vario451) 014   : 0f afl-len (15)
(vario451) 015   : 002c afl-fc (0 MACInFragment MessCounterInFragment MessControlInFragment LastFragment)
(vario451) 017   : 25 afl-mcl (AES_CMAC_128_8 MessCounter)
(vario451) 018   : 36700000 afl-counter (28726)
(vario451) 022   : B767B64527C50AC6 afl-mac 8 bytes
(vario451) 030   : 7a tpl-ci-field (EN 13757-3 Application Layer (short tplh))
(vario451) 031   : 33 tpl-acc-field
(vario451) 032   : 00 tpl-sts-field (OK)
(vario451) 033   : 5007 tpl-cfg 0750 (AES_CBC_NO_IV )
(vario451) 035   : 10 tpl-cfg-ext (KDFS=1)
(vario451) 036   : 2f2f decrypt check bytes
(vario451) 038   : 84 dif (32 Bit Integer/Binary Instantaneous value)
(vario451) 039   : 04 dife (subunit=0 tariff=0 storagenr=8)
(vario451) 040   : 06 vif (Energy kWh)
(vario451) 041 C?: 28460000
(vario451) 045   : 82 dif (16 Bit Integer/Binary Instantaneous value)
(vario451) 046   : 04 dife (subunit=0 tariff=0 storagenr=8)
(vario451) 047   : 6C vif (Date type G)
(vario451) 048 C?: 9F2C
(vario451) 050   : 8D dif (variable length Instantaneous value)
(vario451) 051   : 04 dife (subunit=0 tariff=0 storagenr=8)
(vario451) 052   : 86 vif (Energy kWh)
(vario451) 053   : 1F vife (Compact profile without register)
(vario451) 054   : 1E varlen=30
(vario451) 055 C?: 72FE00000000000000000000000000000000000000000000000000000000
(vario451) 085   : 44 dif (32 Bit Integer/Binary Instantaneous value storagenr=1)
(vario451) 086   : 06 vif (Energy kWh)
(vario451) 087 C?: 00000000
(vario451) 091   : 42 dif (16 Bit Integer/Binary Instantaneous value storagenr=1)
(vario451) 092   : 6C vif (Date type G)
(vario451) 093 C?: FFFF
(vario451) 095   : 04 dif (32 Bit Integer/Binary Instantaneous value)
(vario451) 096   : 06 vif (Energy kWh)
(vario451) 097 C?: C9470000
(vario451) 101   : 2F skip
(vario451) 102   : 2F skip
(vario451) 103   : 2F skip
(vario451) 104   : 2F skip
(vario451) 105   : 2F skip
(vario451) 106   : 2F skip
(vario451) 107   : 2F skip
(vario451) 108   : 2F skip
(vario451) 109   : 2F skip
(vario451) 110   : 2F skip
(vario451) 111   : 2F skip
(vario451) 112   : 2F skip
(vario451) 113   : 2F skip
(vario451) 114   : 2F skip
(vario451) 115   : 2F skip
(vario451) 119 C!: 2846 energy used in previous billing period (17.960000 GJ)
(vario451) 123 C!: 8204 energy used in current billing period (1.154000 GJ)
`

One additional information: Until now I have no idea if those values shown for energy are correct. I have three devices all showing the exact same current billing value, so this is wrong with driver vario451

The shown energy previous billing period values look to have same relation to each other as the physically shown kwh-values, but I didn't see any change until yet, need to have a longer view on it. e.g. this device has shows (nearly) same time physically 18,384.00 kwh

**Comment by weetmuts** [comment]
It seems like the driver c5isf is better and give good results:
Check here: https://wmbusmeters.org/analyze/734468501204439417048C0084900F002C2536700000B767B64527C50AC67A33005007102F2F8404062846000082046C9F2C8D04861F1E72FE00000000000000000000000000000000000000000000000000000000440600000000426CFFFF0406C94700002F2F2F2F2F2F2F2F2F2F2F2F2F2F2F

Please confirm that the values are good, then I will add the data to the lookup table for the driver.

**Comment by JensHoRi** [comment]
Here I got checked values with multical302

Total_energy_consumption is correct with multical (works live, so right during the day too)

**Comment by weetmuts** [comment]
Do you have a name/model/version for this heat meter? Perhaps a link to a web page describing it with tech documents etc?

**Comment by JensHoRi** [comment]
It’s a special Techem version of Sensorstar I think. Here the Techem manual http://techem-downloads.at/wp-content/uploads/2020/10/Montageanleitung-Messkapsel-Wa%CC%88rmeza%CC%88hler-Typ-4.5.1.pdf

**Comment by weetmuts** [comment]
Thanks! Ok, so it is a Techem vario451, but it uses a standardized wmbus protocol, nice!
So I pushed a new driver vario451mid which decodes the values. (The old vario451 seems to be som proprietary protocol.)

However, it stores two older readings. In slot 8 it says the reading from 2020-12-31, is this telegram from january?
If so slot 8 might mean end of last month, which is a common date for billing. But this is usually in slot 1....

And slot one, is not yet used. Is this a new meter?

**Comment by weetmuts** [comment]
You can follow the link I gave above, and it will decode using the new driver. We need to figure out the exact meaning of storage 1 and 8 so that we can give better names to the fields.

**Comment by weetmuts** [comment]
Also, the number of values in this telegram are pretty few. No flow, no volume, no temperatures.
Can you collect some more telegrams? Perhaps it send multiple types of telegrams with different values.

**Comment by JensHoRi** [comment]
I can do maybe next days. Very interesting, I got two keys from techem. Maybe additional stuff is encrypted with other key? Is this possible?

**Comment by weetmuts** [comment]
I released 1.7.0 and I think I have promoted the build to latest/stable on snap. Please confirm if it got propagated to your system.

**Comment by JensHoRi** [comment]
I just tried, but no wmbusmeters doesn't work for me anymore?!?

`(wmbusmeters) version: 1.7.0
(config) store meter files in: "/var/snap/wmbusmeters/common/logs/meter_readings"
(config) using device: /dev/ttyUSB1:c1
(config) number of meters: 14
(lookup) with file/hex "/dev/ttyUSB1" unknown
(serial) check if /dev/ttyUSB1 can be accessed
(serial) tty /dev/ttyUSB1 can be accessed
(verbose) ignoring device /dev/ttyUSB1:c1
No wmbus device detected, waiting for a device to be plugged in.
(shell) exec (capture output) "/bin/pidof"
(shell) arg "wmbusmetersd"
(shell) output: >>><<<
(shell) return code 1
(shell) 9757 exited
(shell) exec (capture output) "/bin/pidof"
(serial) EVENT thread interrupted
(shell) arg "wmbusmeters"
(shell) output: >>>9735
<<<
(serial) EVENT thread interrupted
(shell) return code 0
(shell) 9758 exited
(serial) registered regular callback HOT_PLUG_DETECTOR(0) every 2 seconds
(serial) waiting for stop
(serial) EVENT thread interrupted
(serial) TIMER thread interrupted
(serial) stopping manager
(serial) EVENT thread interrupted
(serial) TIMER thread interrupted
(serial) event loop stopped!
`

**Comment by weetmuts** [comment]
Hmm, it works for me.  Just tested this.

/snap/wmbusmeters/current/usr/bin/wmbusmeters --version

wmbusmeters: 1.7.0
a345e57b5103467d340d68ef27be886462dcd794

/snap/wmbusmeters/current/usr/bin/wmbusmeters auto:c1

Started auto im871a[00102759] on /dev/ttyUSB0 listening on c1
No meters configured. Printing id:s of all telegrams heard!
Received telegram from: 76348799
          manufacturer: (KAM) Kamstrup Energi (0x2c2d)
                  type: Cold water meter (0x16) encrypted
                   ver: 0x1b
                device: im871a[00123456]
                  rssi: -44 dBm
                driver: multical21

**Comment by JensHoRi** [comment]
Got it run again, device configuration in conf file changed from syntax. Had earlier /dev/ttyUSB1:c1 need to be /dev/ttyUSB1:AMB8465:c1 now.

will look for the rest later. :)

**Comment by JensHoRi** [comment]
I‘m home now and can have a look at the weekend. Just an information: I got 2 keys from techem, but as they said, the standard device telegram is untouched. I will have a physical look tomorrow evening and then compare with the telegram

**Comment by JensHoRi** [comment]
To your questions:
It is a device in the house 2-3 years i believe. So not a new one. 31.12.2021 could be historic value because of end of period (maybe preconfigured)

**Comment by JensHoRi** [comment]
Just had a look, but the telegram not fully shown in the log? Doesn't work with analyse or I do some mistake:

(meter) HeizungDG: for me? 94430412 in 94430412
(meter) HeizungDG: yes for me
(meter) HeizungDG multical302 handling telegram from 94430412
(meter) HeizungDG 94430412 "734468501204439417048C004F900F002C25E7C80000531B0669C77C87857AE40050071086DAD44938B0363A827C21887A2EEFC4DFE55B583C976D525650BEBD1D56FB4CC88079E301FA53C31759DE33B0845708E94378AEAF31C72DEDD65D0D1AEFD209AAEB49B65034F0087BBB7C26BC0EB113"
(wmbus) parseDLL @0 116
(telegram) DLL L=73 C=44 (from meter SND_NR) M=5068 (TCH) A=94430412 VER=17 TYPE=04 (Heat meter) (driver vario451mid) DEV=amb8465[00000000] RSSI=-65
(wmbus) parseELL @10 106
(telegram) ELL CI=8c CC=00 (slow_resp) ACC=4f
(wmbus) parseNWL @13 103
(wmbus) parseAFL @13 103
(telegram) AFL CI=90
(wmbus) parseTPL @30 86
(wmbus) input to kdf for enc "00E7C800001204439407070707070707"
(wmbus) ephemereal Kenc 42B63B733C1C2837125CED9195ECD17A
(wmbus) input to kdf for mac "01E7C800001204439407070707070707"
(wmbus) ephemereal Kmac EE3B9ACF43926FD0B559B3DC2012D4E0
(wmbus) input to mac 25E7C800007AE40050071086DAD44938B0363A827C21887A2EEFC4DFE55B583C976D525650BEBD1D56FB4CC88079E301FA53C31759DE33B0845708E94378AEAF31C72DEDD65D0D1AEFD209AAEB49B65034F0087BBB7C26BC0EB113
(wmbus) calculated mac 531B0669C77C87852FB36D38C4BC8EB8
(wmbus) received   mac 531B0669C77C8785
(wmbus) mac ok!
(TPL) num encrypted blocks 5 (80 bytes and remaining unencrypted 0 bytes)
(TPL) IV 00000000000000000000000000000000
(TPL) decrypted  "2F2F8404062846000082046CBF218D04861F1E72FE00000000000000000000000000000000000000000000000000005C02440600000000426CFFFF0406E04800002F2F2F2F2F2F2F2F2F2F2F2F2F2F2F"
(telegram) TPL CI=7a ACC=e4 STS=00 CFG=0750 (AES_CBC_NO_IV)
telegram=|734468501204439417048C004F900F002C25E7C80000531B0669C77C87857AE4005007102F2F_8404062846000082046CBF218D04861F1E72FE00000000000000000000000000000000000000000000000000005C02440600000000426CFFFF0406E04800002F2F2F2F2F2F2F2F2F2F2F2F2F2F2F|+1587
(dvparser) warning: cannot extract uint8 from non-existant key "01FF21"
(wmbus) warning: cannot find offset -1 to add more explanation " info codes ()"
(multical302) 000   : 73 length (115 bytes)
(multical302) 001   : 44 dll-c (from meter SND_NR)
(multical302) 002   : 6850 dll-mfct (TCH)
(multical302) 004   : 12044394 dll-id (94430412)
(multical302) 008   : 17 dll-version
(multical302) 009   : 04 dll-type (Heat meter)
(multical302) 010   : 8c ell-ci-field (ELL: Extended Link Layer I (2 Byte))
(multical302) 011   : 00 ell-cc (slow_resp)
(multical302) 012   : 4f ell-acc
(multical302) 013   : 90 afl-ci-field (AFL: Authentication and Fragmentation Sublayer)
(multical302) 014   : 0f afl-len (15)
(multical302) 015   : 002c afl-fc (0 MACInFragment MessCounterInFragment MessControlInFragment LastFragment)
(multical302) 017   : 25 afl-mcl (AES_CMAC_128_8 MessCounter)
(multical302) 018   : e7c80000 afl-counter (51431)
(multical302) 022   : 531B0669C77C8785 afl-mac 8 bytes
(multical302) 030   : 7a tpl-ci-field (EN 13757-3 Application Layer (short tplh))
(multical302) 031   : e4 tpl-acc-field
(multical302) 032   : 00 tpl-sts-field (OK)
(multical302) 033   : 5007 tpl-cfg 0750 (AES_CBC_NO_IV )
(multical302) 035   : 10 tpl-cfg-ext (KDFS=1)
(multical302) 036   : 2f2f decrypt check bytes (OK)
(multical302) 038   : 84 dif (32 Bit Integer/Binary Instantaneous value)
(multical302) 039   : 04 dife (subunit=0 tariff=0 storagenr=8)
(multical302) 040   : 06 vif (Energy kWh)
(multical302) 041 C?: 28460000
(multical302) 045   : 82 dif (16 Bit Integer/Binary Instantaneous value)
(multical302) 046   : 04 dife (subunit=0 tariff=0 storagenr=8)
(multical302) 047   : 6C vif (Date type G)
(multical302) 048 C?: BF21
(multical302) 050   : 8D dif (variable length Instantaneous value)
(multical302) 051   : 04 dife (subunit=0 tariff=0 storagenr=8)
(multical302) 052   : 86 vif (Energy kWh)
(multical302) 053   : 1F vife (Compact profile without register)
(multical302) 054   : 1E varlen=30
(multical302) 055 C?: 72FE00000000000000000000000000000000000000000000000000005C02
(multical302) 085   : 44 dif (32 Bit Integer/Binary Instantaneous value storagenr=1)
(multical302) 086   : 06 vif (Energy kWh)
(multical302) 087 C!: 00000000 target energy consumption (0.000000 kWh)
(multical302) 091   : 42 dif (16 Bit Integer/Binary Instantaneous value storagenr=1)
(multical302) 092   : 6C vif (Date type G)
(multical302) 093 C!: FFFF target date (2127-15-31 00:00)
(multical302) 095   : 04 dif (32 Bit Integer/Binary Instantaneous value)
(multical302) 096   : 06 vif (Energy kWh)
(multical302) 097 C!: E0480000 total energy consumption (18656.000000 kWh)
(multical302) 101   : 2F skip
(multical302) 102   : 2F skip
(multical302) 103   : 2F skip
(multical302) 104   : 2F skip
(multical302) 105   : 2F skip
(multical302) 106   : 2F skip
(multical302) 107   : 2F skip
(multical302) 108   : 2F skip
(multical302) 109   : 2F skip
(multical302) 110   : 2F skip
(multical302) 111   : 2F skip
(multical302) 112   : 2F skip
(multical302) 113   : 2F skip
(multical302) 114   : 2F skip
(multical302) 115   : 2F skip

**Comment by b4dboi** [comment]
Hi, I have Techem vario 4 Typ 4.5.1 (id 03631700) installed as well but I am struggling with message decoding. I am using rtlwmbus to listen to broadcasted messages. I did some research and I found out that the my heat meter always broadcasts at both C1 (first) and T1 (second). While at C1 it seems I am not able to obtain any decoded data as I do not know encryption key, the telegram from T1 can be successfully decoded using compact5 driver. 

My question is: am I able to force the wmbusmeters to use only compact5 driver and T1 telegrams for this heatmeter? My testing shows that although I define the driver at command line it is ignored and the vario451mid is used with no success. I suppose the best option would be to update the driver_compact5.cc with new Heat Meter (0x43) and version (0x17), but then there might be an overlap with driver_vario451mid.cc. Would you @weetmuts have any suggestions how to proceed? The session and analysis is captured in [vario_4_compact5_driver_analyze.txt](https://github.com/weetmuts/wmbusmeters/files/9732219/vario_4_compact5_driver_analyze.txt) and
[vario_4_verbose_telegrams.txt](https://github.com/weetmuts/wmbusmeters/files/9732220/vario_4_verbose_telegrams.txt).

The second thing I would like to read telegrams from a Techem water meter as well at T1. It seems that the water meter broadcasts at C1 (first) and T1 (second) as well as the heat-meter. And the situation is the same. The C1 telegrams are encrypted (I have no key), but the T1 telegram is decoded by mkradio4 driver successfully. The weird thing is that when I define water meter ID at command line (the one I see at water meter 68312165) there are actually two IDs obtained from the telegram for some reason. When I set the ID to 02617918, the telegram from T1 is decoded using the mkradio4 driver. The session is captured in [water_meter_techem_radio4.txt](https://github.com/weetmuts/wmbusmeters/files/9732278/water_meter_techem_radio4.txt). 

What is the reason there are two IDs?

```
(meter) MyTapWater: for me? 02617918, 68312165 in
(meter) MyTapWater: yes for me
```

**Comment by JensHoRi** [comment]
Interesting techem sends t1 without decoding, because that’s not allowed from gdpr.
I asked Techem for the keys and after some discussions I got it. The CEO promised to set a regular process on it, so why not ask Techem for the keys?

**Comment by b4dboi** [comment]
Good point about the GDPR. Actually the meters are installed at my apartment in utility box probably by local facility/utility company taking care of regular readings for billing purposes. Meters are not physically mine, they are property of local Homeowners association in the apartment building. The schema is not easy, but I was interested in those readings as I want to monitor all energy inputs, so I gave a try. Although the mind set about smart metering is changing and I can try to contact the facility management company, I think reading the T1telegrams seems like easier way to get what I want ;)

**Comment by JensHoRi** [comment]
In the configuration you are able to limit the reading on a protocol I believe. Here my config:
```
HeizungEG 
name=HeizungEG
id=xxxxxxxxxxxx
type=vario351mid:c1
driver=vario451mid
key=Key
```

look at type=driver:protocol

**Comment by b4dboi** [comment]
I overlooked the listento conf parameter (--listento=t1),  however it seems that it has no effect. I mean the C1 telegrams are still received and not ignored. The good thing is that using the approach with configuration files I can see that for the Cold water meter (ID 02617918) messages are decoded successfully. In case of the heat meter, the issue with unknown driver remains. I will do changes in the compact5 driver and build the wmbusmeters from source.

**Comment by JensHoRi** [comment]
Hm, i have the same Techem I believe and it works fine

**Comment by machinekoder** [comment]
@JensHoRi Who did you contact at Techem to receive the keys for your installation?

**Comment by machinekoder** [comment]
@JensHoRi Good to know, thanks.

However, first I need to get this into wmbusmeters:
```
Received telegram from: 90631234
          manufacturer: (TCH) Techem Service (0x5068)
                  type: Cooling load volume at outlet meter (0x0a) encrypted
                   ver: 0x27
                device: cul
                  rssi: -55 dBm
                driver: unknown!
```
tried the above config, but it doesn't handle the telegram. What is `type` doing exactly?

**Comment by JensHoRi** [comment]
Please show your configuration.

then you could try different driver looking for the best effort.

afterwards you can send the log from the reading try too. Not sure if debug mode needs to be activated to See telegram and bots and bites in log ;)
