### ISSUE TITLE
Add support for HYDRUS water meter.

### ISSUE THREAD

**Issue by bbradioactive** [weetmuts/wmbusmeters#51]
Hi, on the wmbusmeters.log file I get three lines repeating.

(meter) name: probably not for me since manufacturer differs
(meter) name: probably not for me since media does not match
(izar) Decoding PRIOS data failed. Ignoring telegram. 

However there is a log file created and updated on the meter_readings 

What could these problems be? @weetmuts

**Comment by weetmuts** [comment]
It would seem that you have specified a meter number/id that is transmitting and received, but which is not an izar meter. If you can post or email me the --debug log output, then I can take a better look at what kind of meter it is.

**Comment by weetmuts** [comment]
The meter_readings file is always created when a telegram is received with the desired number/id, but alas if the telegram fails decoding, then the previous values wil be written into the readings fle.
Values are 0 to start with.

**Comment by bbradioactive** [comment]
How can I email you the logs? @weetmuts . I am using a meter made by Diehl water meter called Hydrus meter. Doesnt it use izar?

**Comment by weetmuts** [comment]
Use oehrstroem@gmail.com 
I think Hydrus is different from the Izar water meter clipon. .

**Comment by weetmuts** [comment]
Thanks for the telegrams, I have now added support for the Hydrus water meter.
Please test!

**Comment by weetmuts** [comment]
Tested and working.
