### ISSUE TITLE
Add raw hex frames to json output

### ISSUE THREAD

**Issue by earsnot** [weetmuts/wmbusmeters#510]
Hi @weetmuts
Awesome project you have here. I am looking to use your library for debugging my implementation of the wmbus protocol on a meter. 
Can you point me in the direction of how to implement that the raw frames gets output to json aswell. Ideally encoded, decoded, encrypted, unencrypted.
Hope this is not too moronic of a question. 
br earsnot

**Comment by weetmuts** [comment]
Howdy @earsnot ! I do not intend to add raw hex output, also wmbusmeters is not a library. It is a standalone program.
But but can use for example rtl_wmbus to grab the raw telegrams.

If you want to check the wmbusmeters protocol decoding (I am not claiming it is complete nor correct)
vs your meters telegram. You can paste your telegrams here: https://wmbusmeters.org/
Or run wmbusmeters locally with --analyze.

What kind of meter are you developing?

**Comment by earsnot** [comment]
Hi again @weetmuts.
Thanks for your answer. It's a standalone program - of course :D - not a library.
I am developing on a meter, that is already on the market, but which is getting some improvements. 
All i need are the raw frames and we will do the decoding/parsing ourselves.

> But but can use for example rtl_wmbus to grab the raw telegrams.

Is that a command line option for your program or is it a different program?
Br earsnot :)

**Comment by weetmuts** [comment]
What do you need help with? :-)
Do you want to verify that you encrypt correctly and/or the contents of the telegram?
Do you have the telegrams on disk already, or do you want to capture them from radio?
Which wmbus dongle do you use?

**Comment by weetmuts** [comment]
You can also email me on oehrstroem@gmail.com
