### ISSUE TITLE
Engelmann Heat Cost Allocator HCAe2 

### ISSUE THREAD

**Issue by LukasACRIOS** [weetmuts/wmbusmeters#512]
When trying to decode the message from Engelmann HCAe2, I get only the following outcome. I have tried to parse the same data by a different parser starting on "LO...O" and it worked. However, I could not find the data description for the HCAe3. They claimed to have the OMS 4 mode 7:

![image](https://user-images.githubusercontent.com/95627411/162229115-3b3cdf58-fe19-4896-8b8d-06e461a1f6c5.png)

Parser outcome:
```
{
  "media": "heat cost allocation",
  "meter": "auto",
  "name": "WMBUS",
  "id": "73115685",
  "timestamp": "2022-04-07T14:11:13Z"
}
```

The data are not AES encrypted (2F2F). Does anyone has experience with this meter? I have checked the library for drivers but could not find the Engelmann or Maddalena Gradus. Also, this meter has a Maddalena branding - Maddalena ITN Gradus.

The different telegrams:
"wmbusId": "73115983", "data": "c944c5148359117325087a290000202f2f046d2130c724036e310000426c0000436e00000082016caf2183016e000000c2016e000082026e0000c2026e000082036e0000c2036e000082046e0000c2046e000082056e0000c2056e000082066e0000c2066e000082076e0000c2076e000082086e0000c2086e000082096e0000c2096e0000820a6e0000c20a6e0000820b6e0000c20b6e0000820c6e0000c20c6e0000820d6e0000c20d6e0b00820e6e0d00c20e6e1100820f6e0600c20f6e0100317f00346d00200000"

"wmbusId": "73115984", "data": "c944c5148459117325087a2c0000202f2f046d3330c724036e960000426c0000436e00000082016caf2183016e000000c2016e000082026e0000c2026e000082036e0000c2036e000082046e0000c2046e000082056e0000c2056e000082066e0000c2066e000082076e0000c2076e000082086e0000c2086e000082096e0000c2096e0000820a6e0000c20a6e0000820b6e0000c20b6e0000820c6e0000c20c6e0000820d6e0000c20d6e1500820e6e2f00c20e6e1e00820f6e1b00c20f6e1200317f00346d00200000"

"wmbusId": "73115968", "data": "c944c5146859117325087a3f0000202f2f046d2130c724036e000000426c0000436e00000082016caf2183016e000000c2016e000082026e0000c2026e000082036e0000c2036e000082046e0000c2046e000082056e0000c2056e000082066e0000c2066e000082076e0000c2076e000082086e0000c2086e000082096e0000c2096e0000820a6e0000c20a6e0000820b6e0000c20b6e0000820c6e0000c20c6e0000820d6e0000c20d6e0000820e6e0000c20e6e0000820f6e0000c20f6e0000317f00346d00200000"

"wmbusId": "73115970", "data": "c944c5147059117325087a1e0000202f2f046d2330c724036e020000426c0000436e00000082016caf2183016e000000c2016e000082026e0000c2026e000082036e0000c2036e000082046e0000c2046e000082056e0000c2056e000082066e0000c2066e000082076e0000c2076e000082086e0000c2086e000082096e0000c2096e0000820a6e0000c20a6e0000820b6e0000c20b6e0000820c6e0000c20c6e0000820d6e0000c20d6e0200820e6e0000c20e6e0000820f6e0000c20f6e0000317f00346d00200000"

"wmbusId": "73115998", "data": "c944c5149859117325087a3b0000202f2f046d2030c724036e220000426c0000436e00000082016caf2183016e000000c2016e000082026e0000c2026e000082036e0000c2036e000082046e0000c2046e000082056e0000c2056e000082066e0000c2066e000082076e0000c2076e000082086e0000c2086e000082096e0000c2096e0000820a6e0000c20a6e0000820b6e0000c20b6e0000820c6e0000c20c6e0000820d6e0000c20d6e0400820e6e0c00c20e6e0500820f6e0000c20f6e0100317f00346d00200000"

**Comment by BIBOLV** [comment]
Hi,
Looking at [--analyze](https://wmbusmeters.org/analyze/c944c5148459117325087a2c0000202f2f046d3330c724036e960000426c0000436e00000082016caf2183016e000000c2016e000082026e0000c2026e000082036e0000c2036e000082046e0000c2046e000082056e0000c2056e000082066e0000c2066e000082076e0000c2076e000082086e0000c2086e000082096e0000c2096e0000820a6e0000c20a6e0000820b6e0000c20b6e0000820c6e0000c20c6e0000820d6e0000c20d6e1500820e6e2f00c20e6e1e00820f6e1b00c20f6e1200317f00346d00200000) looks like eurisii driver decodes current consumption, you just need to confirm that reading is correct and you can use that driver.

**Comment by MarekNovakACRIOS** [comment]
Output with `--analyze` looks much more promissing.
We were using `./wmbusmeters --format=json $DATA WMBUS auto $ID $KEY"`

```
./wmbusmeters --analyze=json:: C944C5144705718129087A510000202F2F046D0B2FC724036E000000426C0000436E00000082016CAF2183016E000000C2016E000082026E0000C2026E000082036E0000C2036E000082046E0000C2046E000082056E0000C2056E000082066E0000C2066E000082076E0000C2076E000082086E0000
C2086E000082096E0000C2096E0000820A6E0000C20A6E0000820B6E0000C20B6E0000820C6E0000C20C6E0000820D6E0000C20D6E0000820E6E0000C20E6E0000820F6E0000C20F6E0000317F00346D00200000
Auto driver  : not found!
Best driver  : eurisii 41/80
Using driver : eurisii 41/80
{ "TODO": true }

{
    "media":"heat cost allocation",
    "meter":"eurisii",
    "name":"",
    "id":"81710547",
    "current_consumption_hca":0,
    "set_date":"2000-00-00",
    "consumption_at_set_date_hca":0,
    "consumption_at_set_date_1_hca":0,
    "consumption_at_set_date_2_hca":0,
    "consumption_at_set_date_3_hca":0,
    "consumption_at_set_date_4_hca":0,
    "consumption_at_set_date_5_hca":0,
    "consumption_at_set_date_6_hca":0,
    "consumption_at_set_date_7_hca":0,
    "consumption_at_set_date_8_hca":0,
    "consumption_at_set_date_9_hca":0,
    "consumption_at_set_date_10_hca":0,
    "consumption_at_set_date_11_hca":0,
    "consumption_at_set_date_12_hca":0,
    "consumption_at_set_date_13_hca":0,
    "consumption_at_set_date_14_hca":0,
    "consumption_at_set_date_15_hca":0,
    "consumption_at_set_date_16_hca":0,
    "consumption_at_set_date_17_hca":0,
    "error_flags":"",
    "timestamp":"2022-04-08T10:46:28Z"
}

```

**Comment by LukasACRIOS** [comment]
> 

Thank you, the --analyze approach seems to work well.
