### ISSUE TITLE
Compatible with "Neptune Mach 10" meter?

### ISSUE THREAD

**Issue by 42Network** [weetmuts/wmbusmeters#517]
Can anyone say if this code can read from a Neptune Mach 10" wireless water meter? According to the vendor website, it uses E-CoderPLUS protocol [manual](https://www.neptunetg.com/globalassets/products/literature/faq-mach-10-09.21.pdf) which is not mentioned in the documentation in this project. But the vendor says it is compatible with Itron 100W, Sensus RadioRead and FlexNet, Aclara MTUs, and Elster Energy Axis [link](https://www.normal.org/DocumentCenter/View/936/How-to-read-a-water-meter-and-FAQs?bidId=). I see Itron and Elster both mentioned here in this project as being compatible.

Can anyone comment?

Thanks/Nathan

**Comment by weetmuts** [comment]
It does not look compatible with wmbus. Ask the vendor if the meter is wmbus/EN13757/OMS compatible.
