### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8)

### ISSUE THREAD

**Issue by c64emulator** [weetmuts/wmbusmeters#530]
I get errormessage when I try to attach to the container on raspberry.
`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8).`

When looking at the docker repo [https://hub.docker.com/r/weetmuts/wmbusmeters/tags](https://hub.docker.com/r/weetmuts/wmbusmeters/tags) I see following:
![OS_arch](https://user-images.githubusercontent.com/3796947/166149436-a12db795-d461-4ecd-bc5d-d479ce03ef09.PNG)

Seems that the declaration of the OS/arch is wrong for the images "latest-arm64v8" and "latest-armhf"?

**Comment by BIBOLV** [comment]
For now, please, use previous version of working docker image, while I dig out my testing rig, find and fix the issues.

**Comment by BIBOLV** [comment]
Docker image tags were fixed. Closing issue.
