### ISSUE TITLE
Container image tag not created for 1.7

### ISSUE THREAD

**Issue by lazyoldbear** [weetmuts/wmbusmeters#539]
It seems that only `latest` tag is updated on [the hub](https://hub.docker.com/r/weetmuts/wmbusmeters).
It would be lovely to provide a `release-1.7.0` as well.
Thanks in advance.

**Comment by BIBOLV** [comment]
During 1.7 release docker building process was broken, but it is fixed now and on next release it will be created.

**Comment by lazyoldbear** [comment]
Splendid. Thank you.

**Comment by weetmuts** [comment]
A new release 1.8.0 should be released now including containers. Please verify!

**Comment by lazyoldbear** [comment]
Works. Thanks a lot!
Also convenient that amd64 is default now.

I will be closing it, but unfortunately, there is a new problem (#566).
