### ISSUE TITLE
Wired Meter not detected

### ISSUE THREAD

**Issue by Mk-arc** [weetmuts/wmbusmeters#543]
This is probably not a bug, but rather I use it wrong. But I have some problems connecting wired Mbus Meter. It works fine in with libmbus:

```
./mbus-serial-request-data-multi-reply -d -b 2400 /dev/ttyUSB1 254
init_slaves: debug: sending init frame #1
[2022-05-13 17:40:59Z] SEND (005): 10 40 FD 3D 16
init_slaves: debug: sending init frame #2
[2022-05-13 17:41:00Z] SEND (005): 10 40 FD 3D 16
[2022-05-13 17:41:00Z] SEND (005): 10 7B FE 79 16
[2022-05-13 17:41:00Z] RECV (053): 68 2F 2F 68 08 01 72 01 12 09 18 AC 48 42 00 1E 00 00 00 0C 00 00 00 00 00 04 6D 29 04 D5 24 42 6C 00 00 4C 00 00 00 00 00 42 EC 7E E1 21 0F 40 01 01 00 9F 16
mbus_frame_print: Dumping M-Bus frame [type 4, 53 bytes]: 68 2F 2F 68 08 01 72 01 12 09 18 AC 48 42 00 1E 00 00 00 0C 00 00 00 00 00 04 6D 29 04 D5 24 42 6C 00 00 4C 00 00 00 00 00 42 EC 7E E1 21 0F 40 01 01 00 9F 16 
<?xml version="1.0" encoding="ISO-8859-1"?>
<MBusData>

    <SlaveInformation>
        <Id>18091201</Id>
        <Manufacturer>REL</Manufacturer>
        <Version>66</Version>
        <ProductName></ProductName>
        <Medium>Other</Medium>
        <AccessNumber>30</AccessNumber>
        <Status>00</Status>
        <Signature>0000</Signature>
    </SlaveInformation>

    <DataRecord id="0">
        <Function>Instantaneous value</Function>
        <StorageNumber>0</StorageNumber>
        <Unit>Energy (mWh)</Unit>
        <Value>0</Value>
        <Timestamp>2022-05-13T17:41:00Z</Timestamp>
    </DataRecord>

    <DataRecord id="1">
        <Function>Instantaneous value</Function>
        <StorageNumber>0</StorageNumber>
        <Unit>Time Point (time &amp; date)</Unit>
        <Value>2022-04-21T04:41:00</Value>
        <Timestamp>2022-05-13T17:41:00Z</Timestamp>
    </DataRecord>

    <DataRecord id="2">
        <Function>Instantaneous value</Function>
        <StorageNumber>1</StorageNumber>
        <Unit>Time Point (date)</Unit>
        <Value>2000-00-00</Value>
        <Timestamp>2022-05-13T17:41:00Z</Timestamp>
    </DataRecord>

    <DataRecord id="3">
        <Function>Instantaneous value</Function>
        <StorageNumber>1</StorageNumber>
        <Unit>Energy (mWh)</Unit>
        <Value>0</Value>
        <Timestamp>2022-05-13T17:41:00Z</Timestamp>
    </DataRecord>

    <DataRecord id="4">
        <Function>Instantaneous value</Function>
        <StorageNumber>1</StorageNumber>
        <Unit>Time Point (date)</Unit>
        <Value>2023-01-01</Value>
        <Timestamp>2022-05-13T17:41:00Z</Timestamp>
    </DataRecord>

    <DataRecord id="5">
        <Function>Manufacturer specific</Function>
        <Value>40 01 01 00</Value>
        <Timestamp>2022-05-13T17:41:00Z</Timestamp>
    </DataRecord>

</MBusData>
```

From my understanding it should be possible to do the same with wmbusmeters? But its not clear to me what arguments to use and how it is supposed to work. 

```
wmbusmeters auto:t1 /dev/ttyUSB1 
No wmbus device detected, waiting for a device to be plugged in.
No meters configured. Printing id:s of all telegrams heard!
```

**Comment by weetmuts** [comment]
From the README with your meter.
wmbusmeters MAIN=/dev/ttyUSB1:mbus:2400 MyEnergyMeter qheat:MAIN:mbus 18091201 NOKEY

Your meter is not in the database, but qheat driver seems to decode parts of it. What is the meter model/version/mfct?

https://wmbusmeters.org/analyze/682f2f6808017201120918ac4842001e0000000c0000000000046d2904d524426c00004c000000000042ec7ee1210f400101009f16:qheat

**Comment by Mk-arc** [comment]
This looks already like something.

```
wmbusmeters --pollinterval=60s MAIN=/dev/ttyUSB1:mbus:2400 MyEnergyMeter qheat:MAIN:mbus 18091201 NOKEY
Started config MAIN=mbus on /dev/ttyUSB1
(meter) MyEnergyMeter: meter detection did not match the selected driver qheat! correct driver is: unknown!
(meter) Not printing this warning again for id: 00000000 mfct: (@@@) Unknown (0x00) type: Other (0x00) ver: 0x00
(meter) please consider opening an issue at https://github.com/weetmuts/wmbusmeters/
(meter) to add support for this unknown mfct,media,version combination
MyEnergyMeter	18091201	0 kWh		0 kWh	2022-05-13 20:25.21
```

I use this MBus to USB converter: https://www.relay.de/en/products/m-bus-master/mikro-master
and this MBus-device: https://www.relay.de/en/products/m-bus-slaves/padpuls-m2

I am pretty new to all of this mbus topic. Is it not easily possible to have some generic driver? I am only interested in actual measured values from various meters. 

> https://wmbusmeters.org/analyze/682f2f6808017201120918ac4842001e0000000c0000000000046d2904d524426c00004c000000000042ec7ee1210f400101009f16:qheat

wow this looks awesome. You are doing some really nice work here. And again thanks for the very quick help!

**Comment by weetmuts** [comment]
Yes, a more flexible approach to the driver system is coming. However it is very easy to write your own driver, check out:

driver_waterstarm.cc
driver_minomess.cc
driver_ultraheat.cc

These are the new style of drivers. Just make a copy of one of them, change the string for the name,
recompile and voila, you have a new driver. :-) The build system automatically detects and integrates your new driver.

You can test your new driver locally:
wmbusmeters --analyze <68...telegramhex>
 
Please let me know how it goes.

**Comment by Mk-arc** [comment]
I created a test-driver. It seems to work nicely like you described.

Maybe I could have one more strange question. I have some very old Diehl heat meter. I see the m-bus connector has three wires and not two. Any idea why is that?

In general the plan was that any mbus device could be read. But it seems this is not easily possible?

**Comment by weetmuts** [comment]
Sorry, no idea. If you just connect that meter to your mbus-controller, then you can perhaps
try out which wire is not needed. Hopefully nothing will burn. ;-)

**Comment by weetmuts** [comment]
Or maybe it is not an mbus connector at all.....

**Comment by weetmuts** [comment]
Perhaps it is a three wire modbus? https://pps2.com/smf/index.php?topic=30.0

**Comment by Mk-arc** [comment]
Hi,

thanks for your help! I did some try and error and some combiniations with 2 out of the three wires worked well. We can also close this issue. 

Thanks!
