### ISSUE TITLE
Can't start add-on after reinstall

### ISSUE THREAD

**Issue by piio** [weetmuts/wmbusmeters#544]
Hi,

I had to remove and add again wmbusmeters addon, but now I have problem with starting it:

s6-overlay-suexec: fatal: can only run as pid 1

**Comment by piio** [comment]
I found similar case:
https://community.home-assistant.io/t/latest-base-image-with-s6-overlay-v3-breaks-add-on/421570

It look's like there was some changes with base image:
https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

**Comment by bratmat** [comment]
Same problem

**Comment by weetmuts** [comment]
Thanks @piio I followed your second link and added "init" : false 
to the config.json and pushed. I checked that the run.sh is executable. Please test if this is enough.

**Comment by piio** [comment]
I have removed and installed addon and it runs correctly, so I think that this problem is resolved. Thanks.
