### ISSUE TITLE
Support for Kamstrup multical302 heat meter T1

### ISSUE THREAD

**Issue by ben3k1v** [weetmuts/wmbusmeters#55]
Good Morning Fredrik.

My energy supplier is coming today and may be able to switch my heat meter from C1 to T1. If you have all logs, would it be generally possible to implement T1 for Kamstrup Multical 302?
Then i can switch over from RTL-Stick to my im871a.

Thanks very much!
Ben

**Comment by weetmuts** [comment]
Yep, with the logs it should be easy to add the T1 mode for the 302.

**Comment by ben3k1v** [comment]
Hi,
In T1 the meter send only every 15 min and it is to long for the energy supplier.
So i go forward with 2 USB sticks next year (Water T1 + Heat C1).

Thanks!
Ben
