### ISSUE TITLE
Little help needed with "fields"

### ISSUE THREAD

**Issue by diddi68** [weetmuts/wmbusmeters#556]
Hi,
I'm using wmbusmeters since about 2 month and it works great. Thank you for that. From the beginning I used "wmbusmeter.conf" with "format=json". Now I wanted to switch to "format=fields", with some values defined in "selectfields=" but I don't know the right shell command for submitting.
I tried
`shell=/usr/bin/mosquitto_pub -h localhost -t wmbusmeters/$METER_ID -m "$METER_FIELDS"`
but without success. I still get the json-string.
What is the right command for submitting "fields"?

**Comment by almerindo** [comment]
Why not just use it?
shell=/usr/bin/mosquitto_pub -h localhost -t wmbusmeters/$METER_ID -m "field1=$METER_TIMESTAMP; field2=$METER_ID; field3=$METER_NAME; field4=$METER_TOTAL_M3"

**Comment by BIBOLV** [comment]
@diddi68 were you able to get it running as you want?

**Comment by diddi68** [comment]
Yes, but in a different way. I use one curl command for every single field.

**Comment by BIBOLV** [comment]
Great, closing issue for now. Please reopen if any other question/issue.
