### ISSUE TITLE
telegram received but incomplete or with errors, since rtl_wmbus reports that CRC checks failed.

### ISSUE THREAD

**Issue by wajo666** [weetmuts/wmbusmeters#558]
Hi,

can you check? I had smiliar issue in december 2021 / january 2022

meter) qcaloric27511360: not for me: not my id
(meter) cold_water: for me? 27511378 in 03772394
(meter) cold_water: not for me: not my id
(meter) hot_water: for me? 27511378 in 03750679
(meter) hot_water: not for me: not my id
(wmbus) telegram from 27511378 ignored by all configured meters!
(rtlwmbus) checkRTLWMBusFrame "C1;1;1;2022-01-04 16:29:20.000;57;60;27511378;0x314493447813512735087abf0000200b6e2200004b6e250200426cbf2ccb086e250200c2086cbf2c326cffff046d1f11c421<0A>"
(rtlwmbus) received full frame
(wmbus) skipping already handled telegram.
(serial) received ascii "T1;0;0;2022-01-04 16:29:20.000;30;25;03750617;0x6e4401061706750305077ab4006085273c5f4f5acae61d3dfbee5eda5dfff40f67e3ffda9639ad1633b1af822ef3e4ca6014a7f1c1330d7507a5e714e51bfdf437562dcb03b46e4941e271335cb8c9f0f79cffae7f5323a29c174916fcc26ba51a35bdc33fc6ac17c4569d283adafa<0A>T1;0;0;2022-01-04 16:29:20.000;25;25;03750617;0x6e4401061706750305077ab4006085273c5f4f5acae61d3dfbee5eda5dfff40f67e3ffda9639ad1633b1af822ef3e4ca6014a7f1c1330d7507a5e714e51bfdf437562dcb03b46e4941e271335cb8c9f0f79cffae7f5323a29c174916fcc26ba51a35bdc33fc6ac17c4569d283adafa<0A>"
(rtlwmbus) checkRTLWMBusFrame "T1;0;0;2022-01-04 16:29:20.000;30;25;03750617;0x6e4401061706750305077ab4006085273c5f4f5acae61d3dfbee5eda5dfff40f67e3ffda9639ad1633b1af822ef3e4ca6014a7f1c1330d7507a5e714e51bfdf437562dcb03b46e4941e271335cb8c9f0f79cffae7f5323a29c174916fcc26ba51a35bdc33fc6ac17c4569d283adafa<0A>T1;0;0;2022-01-04 16:29:20.000;25;25;03750617;0x6e4401061706750305077ab4006085273c5f4f5acae61d3dfbee5eda5dfff40f67e3ffda9639ad1633b1af822ef3e4ca6014a7f1c1330d7507a5e714e51bfdf437562dcb03b46e4941e271335cb8c9f0f79cffae7f5323a29c174916fcc26ba51a35bdc33fc6ac17c4569d283adafa<0A>"
(rtlwmbus) telegram received but incomplete or with errors, since rtl_wmbus reports that CRC checks failed.
(rtlwmbus) error in received message.
(rtlwmbus) checkRTLWMBusFrame "T1;0;0;2022-01-04 16:29:20.000;25;25;03750617;0x6e4401061706750305077ab4006085273c5f4f5acae61d3dfbee5eda5dfff40f67e3ffda9639ad1633b1af822ef3e4ca6014a7f1c1330d7507a5e714e51bfdf437562dcb03b46e4941e271335cb8c9f0f79cffae7f5323a29c174916fcc26ba51a35bdc33fc6ac17c4569d283adafa<0A>"
(rtlwmbus) telegram received but incomplete or with errors, since rtl_wmbus reports that CRC checks failed.
(rtlwmbus) error in received message.
(serial) received ascii "C1;0;1;2022-01-04 16:29:21.000;29;28;28719002;0x49449344029071283508780dff5f350082f50000100007304effff16000000bf2c00030000bf2c0003000000800080008000800100010000800080000000002800ff002f046d1d11c421<0A>C1;0;1;2022-01-04 16:29:21.000;36;39;28719002;0x49449344029071283508780dff5f350082f50000100007b06effff16000000bf2c00030000bf2c0003000000800080008000800080008000800080000000005a01fe005e08da3a238843<0A>"
(rtlwmbus) checkRTLWMBusFrame "C1;0;1;2022-01-04 16:29:21.000;29;28;28719002;0x49449344029071283508780dff5f350082f50000100007304effff16000000bf2c00030000bf2c0003000000800080008000800100010000800080000000002800ff002f046d1d11c421<0A>C1;0;1;2022-01-04 16:29:21.000;36;39;28719002;0x49449344029071283508780dff5f350082f50000100007b06effff16000000bf2c00030000bf2c0003000000800080008000800080008000800080000000005a01fe005e08da3a238843<0A>"
(rtlwmbus) telegram received but incomplete or with errors, since rtl_wmbus reports that CRC checks failed.
(rtlwmbus) error in received message.
(rtlwmbus) checkRTLWMBusFrame "C1;0;1;2022-01-04 16:29:21.000;36;39;28719002;0x49449344029071283508780dff5f350082f50000100007b06effff16000000bf2c00030000bf2c0003000000800080008000800080008000800080000000005a01fe005e08da3a238843<0A>"
(rtlwmbus) telegram received but incomplete or with errors, since rtl_wmbus reports that CRC checks failed.
(rtlwmbus) error in received message.
(serial) received ascii "C1;0;1;2022-01-04 16:29:21.000;143;134;27511389;0x49449344891351273508780dff5f350082060000600107b06effff00000000bf2c06000000bf96030000800000000000000000000000000000000000000000000003001782368e88e210<0A>C1;1;1;2022-01-04 16:29:21.000;142;148;27511389;0x49449344891351273508780dff5f350082060000600107b06effff00000000bf2c06000000bf2c060000000000000000000000000000000000000000000000000006002f046d1d11c421<0A>"
(rtlwmbus) checkRTLWMBusFrame "C1;0;1;2022-01-04 16:29:21.000;143;134;27511389;0x49449344891351273508780dff5f350082060000600107b06effff00000000bf2c06000000bf96030000800000000000000000000000000000000000000000000003001782368e88e210<0A>C1;1;1;2022-01-04 16:29:21.000;142;148;27511389;0x49449344891351273508780dff5f350082060000600107b06effff00000000bf2c06000000bf2c060000000000000000000000000000000000000000000000000006002f046d1d11c421<0A>"

**Comment by wajo666** [comment]
after replug stick is working correctly

**Comment by wajo666** [comment]
after replug stick Ive got this crc error

**Comment by weetmuts** [comment]
This is a problem with your radio reception and is related to rtl_wmbus, not wmbusmeters. 

Bigger antenna? https://weetmuts.github.io/wmbusmeterswiki/
Any machines producing radio noise at certain times around?

Thanks for reporting but please open an issue on https://github.com/xaelsouth/rtl-wmbus instead.
