### ISSUE TITLE
apator162 - new offset  ?

### ISSUE THREAD

**Issue by bdkacz** [weetmuts/wmbusmeters#56]
Hi.

Please look at this logile https://www.dropbox.com/s/9bazdi5p378yr96/wmbusmeters.log?dl=0 and meter id 01759628

It returns 0 where on meter is 77,761

**Comment by bdkacz** [comment]
The solution:

Add to meter_apator162.cc lines :

```
   else
 if ((t->content[13] & 0x01) == 0x01)
    {
       o = 11;
    }

```

**Comment by weetmuts** [comment]
Thanks, I added your fix!

**Comment by bdkacz** [comment]
No problem :)  You welcome :)
