### ISSUE TITLE
Problem with USB-Dongle by HA on Proxmox

### ISSUE THREAD

**Issue by MrLukson** [weetmuts/wmbusmeters#588]
Hello,

I add USB with RTL-SDR dongle to VM with HASS and I can see it in HASS, but the add-on doesn't't see the adapter and in log I have "No wmbus device detected, waiting for a device to be plugged in."
![Zrzut ekranu 2022-08-22 o 10 51 38](https://user-images.githubusercontent.com/65340460/185880840-2418c18c-f9f4-4f44-ac82-83446f491b59.png)

Could someone help me why I have trouble to run WMBUS as add-on?
Perhaps someone can share me config file.

Thanks in advance

**Comment by thecem** [comment]
could you post your addon config as YAML?

**Comment by MrLukson** [comment]
Config:
`data_path: /config/wmbusmeters
conf: >-
  loglevel=normal device=auto:t1 logtelegrams=false format=json
  logfile=/dev/stdout shell=/wmbusmeters/mosquitto_pub.sh
  wmbusmeters/$METER_NAME "$METER_JSON"
meters: []
mqtt: {}
`
LOG:
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Syncing wmbusmeters configuration ...
Registering meters ...
Generating MQTT configuration ... 
Broker core-mosquitto will be used.
Running wmbusmeters ...
No such log level: "normal device=auto:t1 logtelegrams=false format=json logfile=/dev/stdout shell=/wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON""
No wmbus device detected, waiting for a device to be plugged in.
No meters configured. Printing id:s of all telegrams heard!`

**Comment by thecem** [comment]
try first to see you receive telegrams:
```
data_path: /config/wmbusmeters
conf: |-
  loglevel=debug
  device=rtlwmbus
  logtelegrams=true
meters: []
mqtt: {}
```

**Comment by MrLukson** [comment]
@thecem is working. Should add logs and mqtt and meters?

**Comment by thecem** [comment]
to save some CPU usage and produce less heat on the rtl-sdr:

```
data_path: /config/wmbusmeters
conf: |-
  loglevel=normal
  device=rtlwmbus:CMD(rtl_sdr -f 868.95M -s 1600000 - 2>/dev/null | rtl_wmbus -p s -a)
  logtelegrams=true
  format=json
  logfile=/dev/stdout
  shell=/wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"
meters:
  - |-
    name=yourmetername
    driver=yourmeterdriverisworking
    id=meteridshowninlog
    key=nokey or hexstring
mqtt: {}
```

**Comment by MrLukson** [comment]
with multiple meters should I add under first meter second?

**Comment by thecem** [comment]
get the first working, if then add multi meters via:

data_path: /config/wmbusmeters
conf: |-
  loglevel=normal
  device=rtlwmbus:CMD(rtl_sdr -f 868.95M -s 1600000 - 2>/dev/null | rtl_wmbus -p s -a)
  logtelegrams=true
  format=json
  logfile=/dev/stdout
  shell=/wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"
meters:
  - |-
    name=yourmetername
    driver=yourmeterdriverisworking
    id=meteridshowninlog
    key=NOKEY or hexstring
 - |-
    name=yourmetername2
    driver=yourmeterdriverisworking
    id=meteridshowninlog
    key=NOKEY or hexstring
mqtt: {}

**Comment by MrLukson** [comment]
great it's working. Thank you very much. That was simple to configure wmbusmeters on docker but in VM was a little bit tricky.

**Comment by thecem** [comment]
yes, I had same problems! Happy to help and save time!
What kind of meter do you have and which driver do you use?

**Comment by MrLukson** [comment]
I have two meters: Izar and Amiplus

**Comment by MrLukson** [comment]
I moved from docker to Proxmox VM

**Comment by BIBOLV** [comment]
Closing as solution was provided.
