### ISSUE TITLE
im871a - multical21

### ISSUE THREAD

**Issue by tobang** [weetmuts/wmbusmeters#6]
Hi,
I have sucessfully connected a im871a to my raspberry pi, and now I want to read data from my water meter, a multical21. When running wmbusmeters I get this message

(multical21) warning: unknown frame a3 (did you use the correct encryption key?)

I have asked my provider for an AES key, and they send me an <serial of meter>.zip.kem file. I do not know how to get the AES key from this file. Should I use some piece of software to generate the key from this file?

Thanks
Torben

**Comment by weetmuts** [comment]
The KEM file is a zipped xml file. The xml-file the contains xml-encrypted data using the xml-enc standard. The aes-cbc key to decrypt the xml-encrypted data is either your Customer Id or something else selected by the person that created the KEM file for you.

I have always received help to extract the key from within the KEM file, so I cannot do it myself. But if the person who sent you the kem file can open it himself/herself, then ask them to do so, it looks like this:
Meter Name: MC21
Meter number: 76348822
Order Id: 
Program number: 
Serial number: 76348822
Type number: 02146C0K879
Config number: 0100200023533
Consumption type: VolumeCold
  Data Encryption Key: FD83029839F59A18AB3D49013E0B33ED
  General purpose Key 1: 
  General purpose Key 2: 
  General purpose Key 3: 
  General purpose Key 4: 
  Private Key 1: 
  Private Key 2: 
  Private Key 3: 

And ask them to simply email you the contents, or just the Data Encryption Key line.

**Comment by weetmuts** [comment]
The KEM file is a zipped xml file. The xml-file the contains xml-encrypted data using the xml-enc standard. The aes-cbc key to decrypt the xml-encrypted data is either your Customer Id or something else selected by the person that created the KEM file for you.

I have always received help to extract the key from within the KEM file, so I cannot do it myself. But if the person who sent you the kem file can open it himself/herself, then ask them to do so, it looks like this:
Meter Name: MC21
Meter number: 12345678
Order Id:
Program number:
Serial number: 12345678
Type number: 02146C0K879
Config number: 0100200023533
Consumption type: VolumeCold
Data Encryption Key: 0123456789ABCDEF0123456789ABCDEF
General purpose Key 1:
General purpose Key 2:
General purpose Key 3:
General purpose Key 4:
Private Key 1:
Private Key 2:
Private Key 3:

And ask them to simply email you the contents, or just the Data Encryption Key line.

**Comment by tobang** [comment]
Thank you for your swift reply. I will try to ask the water company if the can open the file and give me the key.

thank you

Torben

**Comment by weetmuts** [comment]
Did you solve it? If not, you can send me the KEM file now, since I have a tool that can open it now.

**Comment by tobang** [comment]
My water provider company has send me a csv file, which should contain the encryption key. I have not tried it yet. I really appreciate your help. Thank you.

**Comment by weetmuts** [comment]
Email the file to me. You can find the email address on my github page.

**Comment by weetmuts** [comment]
I just pushed my tool, it is called XMLExtract.java and can be used to extract the meter key from the KEM file. It works on your file, though you need to unzip your file first.

**Comment by weetmuts** [comment]
It seems like the tool is working properly. Closing this issue.
