### ISSUE TITLE
Lansen door/window sensor

### ISSUE THREAD

**Issue by merbanan** [weetmuts/wmbusmeters#65]
2e44333011260200071d7ab54800002f2f02fd1b110002fd971d01000efd3a2200000000008e40fd3a000000000000

Control Info: 0x7A       Access number: 0xB5       Device Type: 0x48         Configuration Word: 0x0000 Switch    : closed
Counter 0 : 34           Counter 1 : 0

fd1b11 = closed

2e44333011260200071d7ab66800002f2f02fd1b550002fd971d01000efd3a2300000000008e40fd3a000000000000

Control Info: 0x7A       Access number: 0xB6       Device Type: 0x68         Configuration Word: 0x0000 Switch    : open
Counter 0 : 35           Counter 1 : 0

fd1b55 = closed

**Comment by weetmuts** [comment]
Thanks for the telegrams! I have pushed support for the door/window sensor to master.
