### ISSUE TITLE
Add new gas meter, Driver unknown (Pipersberg BK-G4, Honeywell ACM 5.6)

### ISSUE THREAD

**Issue by kovu94** [weetmuts/wmbusmeters#662]
Hi all,

I tried to find information in the wiki to add a new driver but I don't find it there. So the tool recommends opening a ticket :)

We got a new gas meter a few weeks ago and I try to read it with my cul v3 and the new firmware. The key seems to be printed on the side of the meter.

After fireing the command, the following output appears:

root@bananapi:~# wmbusmeters --format=json auto:t1 test izar 00000816 XXXXX(key deleted)XXXX
Started auto cul on /dev/ttyACM0 listening on t1
(meter) test: meter detection did not match the selected driver izar! correct driver is: unknown!
(meter) Not printing this warning again for id: 00000816 mfct: (ELS) Elster, Germany (0x1593) type: Radio converter (meter side) (0x37) ver: 0x01
(meter) please consider opening an issue at https://github.com/weetmuts/wmbusmeters/
(meter) to add support for this unknown mfct,media,version combination
(izar) Decoding PRIOS data failed. Ignoring telegram.
{"media":"gas","meter":"izar","name":"test","id":"04361909","prefix":"","serial_number":"000000","total_m3":0,"last_month_total_m3":0,"last_month_measure_date":"1-00-00","remaining_battery_life_y":0,"current_alarms":"general_alarm","previous_alarms":"no_alarm","transmit_period_s":0,"manufacture_year":"0","timestamp":"2022-11-07T08:41:25Z","device":"cul","rssi_dbm":-82}
(izar) Decoding PRIOS data failed. Ignoring telegram.
{"media":"gas","meter":"izar","name":"test","id":"04361909","prefix":"","serial_number":"000000","total_m3":0,"last_month_total_m3":0,"last_month_measure_date":"1-00-00","remaining_battery_life_y":0,"current_alarms":"general_alarm","previous_alarms":"no_alarm","transmit_period_s":0,"manufacture_year":"0","timestamp":"2022-11-07T08:45:26Z","device":"cul","rssi_dbm":-83}
(izar) Decoding PRIOS data failed. Ignoring telegram.
{"media":"gas","meter":"izar","name":"test","id":"04361909","prefix":"","serial_number":"000000","total_m3":0,"last_month_total_m3":0,"last_month_measure_date":"1-00-00","remaining_battery_life_y":0,"current_alarms":"general_alarm","previous_alarms":"no_alarm","transmit_period_s":0,"manufacture_year":"0","timestamp":"2022-11-07T08:49:26Z","device":"cul","rssi_dbm":-82}
(izar) Decoding PRIOS data failed. Ignoring telegram.
{"media":"gas","meter":"izar","name":"test","id":"04361909","prefix":"","serial_number":"000000","total_m3":0,"last_month_total_m3":0,"last_month_measure_date":"1-00-00","remaining_battery_life_y":0,"current_alarms":"general_alarm","previous_alarms":"no_alarm","transmit_period_s":0,"manufacture_year":"0","timestamp":"2022-11-07T08:57:26Z","device":"cul","rssi_dbm":-82}
(izar) Decoding PRIOS data failed. Ignoring telegram.
{"media":"gas","meter":"izar","name":"test","id":"04361909","prefix":"","serial_number":"000000","total_m3":0,"last_month_total_m3":0,"last_month_measure_date":"1-00-00","remaining_battery_life_y":0,"current_alarms":"general_alarm","previous_alarms":"no_alarm","transmit_period_s":0,"manufacture_year":"0","timestamp":"2022-11-07T09:01:25Z","device":"cul","rssi_dbm":-82}

Logfile during scanning:
(serial) received binary "6233423434393331353136303830303030303133373145373138433230343739303046303032433235343937413030303037393132393037444437384630304336373030383732303931393336303433303431334130333933303031303731303430373130393641334242463233443935334633303943453542464339343536"
(cul) checkCULFrame "b3B4493151608000001371E718C2047900F002C25497A00007912907DD78F00C67008720919360430413A039300107104071096A3BBF23D953F309CE5BFC9456"
(cul) no eol found yet, partial frame
(serial) received binary "45394231393835373331384330383045440D0A"
(cul) checkCULFrame "b3B4493151608000001371E718C2047900F002C25497A00007912907DD78F00C67008720919360430413A039300107104071096A3BBF23D953F309CE5BFC9456E9B19857318C080ED<0D><0A>"
(cul) checkCULFrame RSSI_RAW=-19
(cul) checkCULFrame LQI=64
(wmbus) trimming frame A "3B4493151608000001371E718C2047900F002C25497A00007912907DD78F00C67008720919360430413A039300107104071096A3BBF23D953F309CE5BFC9456E9B19857318C0"
(wmbus) ff a dll crc 0-9 1e71 ok
(wmbus) ff a dll crc mid 12-27 d78f ok
(wmbus) ff a dll crc mid 30-45 7104 ok
(wmbus) ff a dll crc mid 48-63 9b19 ok
(wmbus) ff a dll crc final 66-67 18c0 ok
(wmbus) trimming frame A "3B4493151608000001371E718C2047900F002C25497A00007912907DD78F00C67008720919360430413A039300107104071096A3BBF23D953F309CE5BFC9456E9B19857318C0"
(wmbus) trimmed 10 dll crc bytes from frame a and ignored 0 suffix bytes.
(wmbus) trimmed frame A "3B4493151608000001378C2047900F002C25497A00007912907D00C67008720919360430413A03930010071096A3BBF23D953F309CE5BFC9456E8573"
(cul) received full T1 frame
(meter) no meter handled  checking 0 templates.
(wmbus) parseDLL @0 60
(wmbus) parseELL @10 50
(wmbus) parseNWL @13 47
(wmbus) parseAFL @13 47
(wmbus) parseTPL @30 30
(wmbus) input to kdf for enc "00497A00000919360407070707070707"
(wmbus) no key, thus cannot execute kdf.
(wmbus) parseDLL @0 60
(telegram) DLL L=3b C=44 (from meter SND_NR) M=1593 (ELS) A=00000816 VER=01 TYPE=37 (Radio converter (meter side)) (driver unknown!) DEV=cul RSSI=-83
(wmbus) parseELL @10 50
(telegram) ELL CI=8c CC=20 (slow_resp sync) ACC=47
(wmbus) parseNWL @13 47
(wmbus) parseAFL @13 47
(telegram) AFL CI=90
(wmbus) parseTPL @30 30
(wmbus) input to kdf for enc "00497A00000919360407070707070707"
(wmbus) no key, thus cannot execute kdf.
Received telegram from: 00000816
          manufacturer: (ELS) Elster, Germany (0x1593)
                  type: Radio converter (meter side) (0x37) encrypted
                   ver: 0x01
      Concerning meter: 04361909
          manufacturer: (PIP) Hermann Pipersberg jr, Germany (0x4130)
                  type: Gas meter (0x03) encrypted
                   ver: 0x3a
                device: cul
                  rssi: -83 dBm
                driver: unknown!
(wmbus) 000   : 3b length (59 bytes)
(wmbus) 001   : 44 dll-c (from meter SND_NR)
(wmbus) 002   : 9315 dll-mfct (ELS)
(wmbus) 004   : 16080000 dll-id (00000816)
(wmbus) 008   : 01 dll-version
(wmbus) 009   : 37 dll-type (Radio converter (meter side))
(wmbus) 010   : 8c ell-ci-field (ELL: Extended Link Layer I (2 Byte))
(wmbus) 011   : 20 ell-cc (slow_resp sync)
(wmbus) 012   : 47 ell-acc
(wmbus) 013   : 90 afl-ci-field (AFL: Authentication and Fragmentation Sublayer)
(wmbus) 014   : 0f afl-len (15)
(wmbus) 015   : 002c afl-fc (0 MACInFragment MessCounterInFragment MessControlInFragment LastFragment)
(wmbus) 017   : 25 afl-mcl (AES_CMAC_128_8 MessCounter)
(wmbus) 018   : 497a0000 afl-counter (31305)
(wmbus) 022   : 7912907D00C67008 afl-mac 8 bytes
(wmbus) 030   : 72 tpl-ci-field (EN 13757-3 Application Layer (long tplh))
(wmbus) 031   : 09193604 tpl-id (04361909)
(wmbus) 035   : 3041 tpl-mfct (PIP)
(wmbus) 037   : 3a tpl-version
(wmbus) 038   : 03 tpl-type (Gas meter)
(wmbus) 039   : 93 tpl-acc-field
(wmbus) 040   : 00 tpl-sts-field (OK)
(wmbus) 041   : 1007 tpl-cfg 0710 (AES_CBC_NO_IV )
(wmbus) 043   : 10 tpl-cfg-ext (KDFS=1)
telegram=|_3B4493151608000001378C2047900F002C25497A00007912907D00C67008720919360430413A03930010071096A3BBF23D953F309CE5BFC9456E8573|+803
(wmbus) telegram from 00000816,04361909 ignored by all configured meters!

Gas meter is a Pipersberg BK-G4 AcT with a Honeywell ACM 5.6 M-BUS Radio, manufacturer is Elster GmbH, Lotte
The key is printed on the side of the Honeywell adaptor and seems to work(?).

Is there any more I can help with?

Kind regards,
Sebastian

**Comment by kovu94** [comment]
Additional Info - telegram reading without encryption key

Auto driver  : not found!
Best driver  : apator08 04/08
Using driver : apator08 04/08
000   : 3b length (59 bytes)
001   : 44 dll-c (from meter SND_NR)
002   : 9315 dll-mfct (ELS)
004   : 16080000 dll-id (00000816)
008   : 01 dll-version
009   : 37 dll-type (Radio converter (meter side))
010   : 8c ell-ci-field (ELL: Extended Link Layer I (2 Byte))
011   : 20 ell-cc (slow_resp sync)
012   : 63 ell-acc
013   : 90 afl-ci-field (AFL: Authentication and Fragmentation Sublayer)
014   : 0f afl-len (15)
015   : 002c afl-fc (0 MACInFragment MessCounterInFragment MessControlInFragment LastFragment)
017   : 25 afl-mcl (AES_CMAC_128_8 MessCounter)
018   : 657a0000 afl-counter (31333)
022   : B71FC5D1DB43311C afl-mac 8 bytes
025 C!: *** 10
0c137442 total consumption (371634.436000 m3)
030   : 72 tpl-ci-field (EN 13757-3 Application Layer (long tplh))
031   : 09193604 tpl-id (04361909)
035   : 3041 tpl-mfct (PIP)
037   : 3a tpl-version
038   : 03 tpl-type (Gas meter)
039   : 9a tpl-acc-field
040   : 00 tpl-sts-field (OK)
041   : 1007 tpl-cfg 0710 (AES_CBC_NO_IV )
043   : 10 tpl-cfg-ext (KDFS=1)
044   : 2f2f already decrypted check bytes
046   : 0C dif (8 digit BCD Instantaneous value)
047   : 13 vif (Volume l)
048 C?: 74421400
052   : 2F skip
053   : 2F skip
054   : 2F skip
055   : 2F skip
056   : 2F skip
057   : 2F skip
058   : 2F skip
059   : 2F skip

{
    "media":"gas",
    "meter":"apator08",
    "name":"",
    "id":"04361909",
    "total_m3":371634.436,
    "timestamp":"2022-11-07T11:10:45Z"
}


Using: wmbusmeters: 1.9.0-76-gb9f3446
b9f3446bc6ba9b0e4e0ddd1f8bdc1cf22bcbe04a

--> with encryption key

Auto driver  : not found!
Best driver  :  00/00
Using driver :  00/00
000   : 3b length (59 bytes)
001   : 44 dll-c (from meter SND_NR)
002   : 9315 dll-mfct (ELS)
004   : 16080000 dll-id (00000816)
008   : 01 dll-version
009   : 37 dll-type (Radio converter (meter side))
010   : 8c ell-ci-field (ELL: Extended Link Layer I (2 Byte))
011   : 20 ell-cc (slow_resp sync)
012   : 63 ell-acc
013   : 90 afl-ci-field (AFL: Authentication and Fragmentation Sublayer)
014   : 0f afl-len (15)
015   : 002c afl-fc (0 MACInFragment MessCounterInFragment MessControlInFragment LastFragment)
017   : 25 afl-mcl (AES_CMAC_128_8 MessCounter)
018   : 657a0000 afl-counter (31333)
022   : B71FC5D1DB43311C afl-mac 8 bytes
030   : 72 tpl-ci-field (EN 13757-3 Application Layer (long tplh))
031   : 09193604 tpl-id (04361909)
035   : 3041 tpl-mfct (PIP)
037   : 3a tpl-version
038   : 03 tpl-type (Gas meter)
039   : 9a tpl-acc-field
040   : 00 tpl-sts-field (OK)
041   : 1007 tpl-cfg 0710 (AES_CBC_NO_IV )
043   : 10 tpl-cfg-ext (KDFS=1)
044   : 2f2f already decrypted check bytes

{
    "media":"gas",
    "meter":"unknown",
    "name":"",
    "id":"04361909",
    "timestamp":"1970-01-01T00:00:00Z"
}


Using: wmbusmeters: 1.9.0-76-gb9f3446
b9f3446bc6ba9b0e4e0ddd1f8bdc1cf22bcbe04a

(is the decryption key correct?)

**Comment by BIBOLV** [comment]
Last telegram you provided is decrypted. Are those readings correct?
```
{
    "media":"gas",
    "meter":"apator08",
    "name":"",
    "id":"04361909",
    "total_m3":371634.436,
    "timestamp":"2022-11-18T22:34:36Z"
}
```

**Comment by kovu94** [comment]
No, these values aren't correct. I got these values when I don't provide the encryption key. After updating wmbusmeters the result changes a bit and I can see those values also with provided encryption key in meter-file.

At the moment I'm in contact with my gas and water provider to get the key for the water meter and checking the key for the gas meter. They are in contact with their legal department and the manufacturers and I waiting for response.
I hope that they provide the key, the first contact sounds positive.

Logged again today with this values:
(shell) env "METER_ID=04361909"
(shell) env "METER_NAME=Gaszaehler-Pipersberg-WMBUS"
(shell) env "METER_MEDIA=gas"
(shell) env "METER_TYPE=apator08"
(shell) env "METER_TIMESTAMP=2022-11-19T09:40:59Z"
(shell) env "METER_TIMESTAMP_UTC=2022-11-19T09:40:59Z"
(shell) env "METER_TIMESTAMP_UT=1668850859"
(shell) env "METER_TIMESTAMP_LT=2022-11-19 09:40.59"
(shell) env "METER_DEVICE=cul"
(shell) env "METER_RSSI_DBM=-64"
(shell) env "METER_TOTAL_M3=846661.209333"

The actual value of the meter is 
![grafik](https://user-images.githubusercontent.com/5141666/202844891-e6551981-1fe1-4d35-852e-076f3fefc058.png)

I start another recompile now as some files are changed in the last days.

**Comment by kovu94** [comment]
New compiled version is **1.9.0-118-g978f2d1**

**wmbusmeters --useconfig=/  (wiithout meter config file)**

Received telegram from: 00000816
          manufacturer: (ELS) Elster, Germany (0x1593)
                  type: Radio converter (meter side) (0x37) encrypted
                   ver: 0x01
      Concerning meter: 04361909
          manufacturer: (PIP) Hermann Pipersberg jr, Germany (0x4130)
                  type: Gas meter (0x03) encrypted
                   ver: 0x3a
                device: cul
                  rssi: -67 dBm
                driver: unknown!
(wmbus) 000   : 3b length (59 bytes)
(wmbus) 001   : 44 dll-c (from meter SND_NR)
(wmbus) 002   : 9315 dll-mfct (ELS)
(wmbus) 004   : 16080000 dll-id (00000816)
(wmbus) 008   : 01 dll-version
(wmbus) 009   : 37 dll-type (Radio converter (meter side))
(wmbus) 010   : 8c ell-ci-field (ELL: Extended Link Layer I (2 Byte))
(wmbus) 011   : 20 ell-cc (slow_resp sync)
(wmbus) 012   : 39 ell-acc
(wmbus) 013   : 90 afl-ci-field (AFL: Authentication and Fragmentation Sublayer)
(wmbus) 014   : 0f afl-len (15)
(wmbus) 015   : 002c afl-fc (0 MACInFragment MessCounterInFragment MessControlInFragment LastFragment)
(wmbus) 017   : 25 afl-mcl (AES_CMAC_128_8 MessCounter)
(wmbus) 018   : 3b8b0000 afl-counter (35643)
(wmbus) 022   : 5E14142B93C11464 afl-mac 8 bytes
(wmbus) 030   : 72 tpl-ci-field (EN 13757-3 Application Layer (long tplh))
(wmbus) 031   : 09193604 tpl-id (04361909)
(wmbus) 035   : 3041 tpl-mfct (PIP)
(wmbus) 037   : 3a tpl-version
(wmbus) 038   : 03 tpl-type (Gas meter)
(wmbus) 039   : d0 tpl-acc-field
(wmbus) 040   : 00 tpl-sts-field (OK)
(wmbus) 041   : 1007 tpl-cfg 0710 (AES_CBC_NO_IV )
(wmbus) 043   : 10 tpl-cfg-ext (KDFS=1)
telegram=|_3B4493151608000001378C2039900F002C253B8B00005E14142B93C11464720919360430413A03D00010071035331731167561AC123F238257EF12A1|+77
(wmbus) telegram from 00000816,04361909 ignored by all configured meters!

**(with meter config file but without driver and key in it)**

(meter) Gaszaehler-Pipersberg-WMBUS: for me? 00000816,04361909 in 00000816
(meter) Gaszaehler-Pipersberg-WMBUS: yes for me
(meter) Gaszaehler-Pipersberg-WMBUS: meter detection could not find driver for id: 04361909 mfct: (PIP) Hermann Pipersberg jr, Germany (0x4130) type: Gas meter (0x03) ver: 0x3a
(meter) please consider opening an issue at https://github.com/weetmuts/wmbusmeters/
(meter) to add support for this unknown mfct,media,version combination
(meter) created Gaszaehler-Pipersberg-WMBUS auto 04361909 not-encrypted
(meter) used meter template Gaszaehler-Pipersberg-WMBUS 00000816 auto to match 00000816,04361909
(meter) started meter 1 (Gaszaehler-Pipersberg-WMBUS 04361909 auto)
(wmbus) parseDLL @0 60
(wmbus) parseELL @10 50
(wmbus) parseNWL @13 47
(wmbus) parseAFL @13 47
(wmbus) parseTPL @30 30
(wmbus) input to kdf for enc "003D8B00000919360407070707070707"
(wmbus) no key, thus cannot execute kdf.
(meter) Gaszaehler-Pipersberg-WMBUS: for me? 00000816,04361909 in 04361909
(meter) Gaszaehler-Pipersberg-WMBUS: yes for me
(meter) Gaszaehler-Pipersberg-WMBUS(1) auto  handling telegram from 04361909
(meter) Gaszaehler-Pipersberg-WMBUS 04361909 "3B4493151608000001378C203B900F002C253D8B000045FA6EB0416578AD720919360430413A03D000100710EDDE4F68627D9B4F5BD6CE9F91EDC07D"
(wmbus) parseDLL @0 60
(telegram) DLL L=3b C=44 (from meter SND_NR) M=1593 (ELS) A=00000816 VER=01 TYPE=37 (Radio converter (meter side)) (driver unknown!) DEV=cul RSSI=-67
(wmbus) parseELL @10 50
(telegram) ELL CI=8c CC=20 (slow_resp sync) ACC=3b
(wmbus) parseNWL @13 47
(wmbus) parseAFL @13 47
(telegram) AFL CI=90
(wmbus) parseTPL @30 30
(wmbus) input to kdf for enc "003D8B00000919360407070707070707"
(wmbus) no key, thus cannot execute kdf.
(meter) newly created meter (Gaszaehler-Pipersberg-WMBUS 04361909 auto) did not handle telegram!
(wmbus) telegram from 00000816,04361909 ignored by all configured meters!

**(with meter config file but with (test-)driver and key in it)**

(meter) Gaszaehler-Pipersberg-WMBUS: for me? 00000816,04361909 in 04361909
(meter) Gaszaehler-Pipersberg-WMBUS: meter detection did not match the selected driver unknown! correct driver is: unknown!
(meter) Not printing this warning again for id: 00000816 mfct: (ELS) Elster, Germany (0x1593) type: Radio converter (meter side) (0x37) ver: 0x01
(meter) please consider opening an issue at https://github.com/weetmuts/wmbusmeters/
(meter) to add support for this unknown mfct,media,version combination
(meter) Gaszaehler-Pipersberg-WMBUS: yes for me
(meter) Gaszaehler-Pipersberg-WMBUS(1) apator08  handling telegram from 04361909
(meter) Gaszaehler-Pipersberg-WMBUS 04361909 "3B4493151608000001378C203C900F002C253E8B00004C162F35E68CA92F720919360430413A03D0001007100FCCB47FA4CD1AB8C0B55BD69C7C1B91"
(wmbus) parseDLL @0 60
(telegram) DLL L=3b C=44 (from meter SND_NR) M=1593 (ELS) A=00000816 VER=01 TYPE=37 (Radio converter (meter side)) (driver unknown!) DEV=cul RSSI=-67
(wmbus) parseELL @10 50
(telegram) ELL CI=8c CC=20 (slow_resp sync) ACC=3c
(wmbus) parseNWL @13 47
(wmbus) parseAFL @13 47
(telegram) AFL CI=90
(wmbus) parseTPL @30 30
(wmbus) input to kdf for enc "003E8B00000919360407070707070707"
(wmbus) ephemereal Kenc AB25FE5C0BB93E5341C4B45D04477BFE
(wmbus) input to kdf for mac "013E8B00000919360407070707070707"
(wmbus) ephemereal Kmac EFD02E7BD76B77B53F4AA451B29158B9
(wmbus) input to mac 253E8B0000720919360430413A03D0001007100FCCB47FA4CD1AB8C0B55BD69C7C1B91
(wmbus) calculated mac 4C162F35E68CA92F3E3D16BC68807696
(wmbus) received   mac 4C162F35E68CA92F
(wmbus) mac ok!
(TPL) num encrypted blocks 1 (16 bytes and remaining unencrypted 0 bytes)
(TPL) IV 00000000000000000000000000000000
(TPL) decrypted  "2F2F0C13150424002F2F2F2F2F2F2F2F"
(dvparser) found new format "0C13" with hash a99b, remembering!
(telegram) TPL CI=72 ACC=d0 STS=00 CFG=0710 (AES_CBC_NO_IV) ID=09193604 MFT=3041 VER=3a TYPE=03 (Gas meter)
telegram=|3B4493151608000001378C203C900F002C253E8B00004C162F35E68CA92F720919360430413A03D0001007102F2F_0C13150424002F2F2F2F2F2F2F2F|+150
(meters) trying field info total(Volume)[0]...
(apator08) 000   : 3b length (59 bytes)
(apator08) 001   : 44 dll-c (from meter SND_NR)
(apator08) 002   : 9315 dll-mfct (ELS)
(apator08) 004   : 16080000 dll-id (00000816)
(apator08) 008   : 01 dll-version
(apator08) 009   : 37 dll-type (Radio converter (meter side))
(apator08) 010   : 8c ell-ci-field (ELL: Extended Link Layer I (2 Byte))
(apator08) 011   : 20 ell-cc (slow_resp sync)
(apator08) 012   : 3c ell-acc
(apator08) 013   : 90 afl-ci-field (AFL: Authentication and Fragmentation Sublayer)
(apator08) 014   : 0f afl-len (15)
(apator08) 015   : 002c afl-fc (0 MACInFragment MessCounterInFragment MessControlInFragment LastFragment)
(apator08) 017   : 25 afl-mcl (AES_CMAC_128_8 MessCounter)
(apator08) 018   : 3e8b0000 afl-counter (35646)
(apator08) 022   : 4C162F35E68CA92F afl-mac 8 bytes
(apator08) 030   : 72 tpl-ci-field (EN 13757-3 Application Layer (long tplh))
(apator08) 031   : 09193604 tpl-id (04361909)
(apator08) 035   : 3041 tpl-mfct (PIP)
(apator08) 037   : 3a tpl-version
(apator08) 038   : 03 tpl-type (Gas meter)
(apator08) 039   : d0 tpl-acc-field
(apator08) 040   : 00 tpl-sts-field (OK)
(apator08) 041   : 1007 tpl-cfg 0710 (AES_CBC_NO_IV )
(apator08) 043   : 10 tpl-cfg-ext (KDFS=1)
(apator08) 044   : 2f2f decrypt check bytes (OK)
(apator08) 046   : 0C dif (8 digit BCD Instantaneous value)
(apator08) 047   : 13 vif (Volume l)
(apator08) 048 C?: 15042400
(apator08) 052   : 2F skip
(apator08) 053   : 2F skip
(apator08) 054   : 2F skip
(apator08) 055   : 2F skip
(apator08) 056   : 2F skip
(apator08) 057   : 2F skip
(apator08) 058   : 2F skip
(apator08) 059   : 2F skip
(apator08) 025 C!: *** 10|0c131504 total consumption (22829.998667 m3)
(meters) render field total(Volume)[0] without dventry
(meters)             "total_m3":22829.998667
(shell) exec "/bin/sh"
(shell) arg "-c"
(shell) arg "HOME=/home/wmbusmeters/ /usr/bin/mosquitto_pub -h 192.168.178.3 -u mqtt -P mypass -t wmbusmeters/$METER_ID -m "$METER_JSON""
(shell) env "METER_JSON={"media":"gas","meter":"apator08","name":"Gaszaehler-Pipersberg-WMBUS","id":"04361909","total_m3":22829.998667,"timestamp":"2022-11-19T10:41:20Z","device":"cul","rssi_dbm":-67,"address":"xxx","city":"xxx"}"
(shell) env "METER_ID=04361909"
(shell) env "METER_NAME=Gaszaehler-Pipersberg-WMBUS"
(shell) env "METER_MEDIA=gas"
(shell) env "METER_TYPE=apator08"
(shell) env "METER_TIMESTAMP=2022-11-19T10:41:20Z"
(shell) env "METER_TIMESTAMP_UTC=2022-11-19T10:41:20Z"
(shell) env "METER_TIMESTAMP_UT=1668854480"
(shell) env "METER_TIMESTAMP_LT=2022-11-19 10:41.20"
(shell) env "METER_DEVICE=cul"
(shell) env "METER_RSSI_DBM=-67"
(shell) env "METER_TOTAL_M3=22829.998667"
(shell) env "METER_address=xxx"
(shell) env "METER_city=xxx"
(shell) waiting for child 4048 to complete.
(shell) /bin/sh: return code 0
Could not open file "/var/log/wmbusmeters/meter_readings/Gaszaehler-Pipersberg-WMBUS-04361909" for writing!

root@bananapi:~wmbusmeters  --logtelegrams --format=json auto:t1 test izar 00000816 KEYREMOVED
Started auto cul on /dev/ttyACM0 listening on t1
(meter) test: meter detection could not find driver for id: 04361909 mfct: (PIP) Hermann Pipersberg jr, Germany (0x4130) type: Gas meter (0x03) ver: 0x3a
(meter) please consider opening an issue at https://github.com/weetmuts/wmbusmeters/
(meter) to add support for this unknown mfct,media,version combination
(meter) test: meter detection did not match the selected driver unknown! correct driver is: unknown!
(meter) Not printing this warning again for id: 00000816 mfct: (ELS) Elster, Germany (0x1593) type: Radio converter (meter side) (0x37) ver: 0x01
(meter) please consider opening an issue at https://github.com/weetmuts/wmbusmeters/
(meter) to add support for this unknown mfct,media,version combination
telegram=|3B4493151608000001378C203D900F002C253F8B0000876DCCFF04AF38BF720919360430413A03D1001007102F2F_0C13150424002F2F2F2F2F2F2F2F|+91
(izar) Decoding PRIOS data failed. Ignoring telegram.
{"media":"gas","meter":"izar","name":"test","id":"04361909","prefix":"","serial_number":"000000","total_m3":0,"last_month_total_m3":0,"last_month_measure_date":"2-00-00","remaining_battery_life_y":0,"current_alarms":"overflow,mechanical_fraud","previous_alarms":"no_alarm","transmit_period_s":0,"manufacture_year":"0","timestamp":"2022-11-19T10:45:20Z","device":"cul","rssi_dbm":-66}

Maybe this data helps, if I can provide more detailed data please ask.

**Comment by BIBOLV** [comment]
```
{
    "media":"gas",
    "meter":"aventieswm",
    "name":"",
    "id":"04361909",
    "total_m3":240.415,
```

**Comment by kovu94** [comment]
![grafik](https://user-images.githubusercontent.com/5141666/202895328-4c1e412a-de46-4d8a-a04d-afb32ac75df1.png)

Works like a charm! Thank you so much! :-)
