### ISSUE TITLE
energy meter EGM Elgama

### ISSUE THREAD

**Issue by palibrzuch** [weetmuts/wmbusmeters#674]
Hello.
I have a counter as in the attachment.
Is it possible to add support to him?
Logs also in the attachment.
If there is anything else to read, I'll do it.
Regards

`(meter) licznik_eon: for me? 13829063 in 13829063
(meter) licznik_eon: yes for me
(meter) licznik_eon(1) auto  handling telegram from 13829063
(meter) licznik_eon 13829063 "BE44ED146390821301027A3A00B00545EB67E710003AB88210D29A44B41ED1876BE3A2DA383AE13C68A65E0277D81473EE8E2B62CA9191F6F694534C165BB8D2EE2F625701F6E83F1C9864C39CE53447D0B1C8EDD1163D7073DC15282700D4816CE1C29709DDAB6360137F62BA01932E052D8905AC5E62100DF75C6466A8D2415DA4FE266DA110C8939AD67E38F46972E3A0280A386E37100C38CF27679B7F194AE87C37A5DC3BF7AB9050DDA89F69B47725A48F0D21AD5C2705E2506ABDCF"
(wmbus) parseDLL @0 191
(telegram) DLL L=be C=44 (from meter SND_NR) M=14ed (EGM) A=13829063 VER=01 TYPE=02 (Electricity meter) (driver unknown!) DEV=rtlwmbus[00000001] RSSI=100
(wmbus) parseELL @10 181
(wmbus) parseNWL @10 181
(wmbus) parseAFL @10 181
(wmbus) parseTPL @10 181
(TPL) num encrypted blocks 11 (176 bytes and remaining unencrypted 0 bytes)
(TPL) AES CBC IV decrypting "45EB67E710003AB88210D29A44B41ED1876BE3A2DA383AE13C68A65E0277D81473EE8E2B62CA9191F6F694534C165BB8D2EE2F625701F6E83F1C9864C39CE53447D0B1C8EDD1163D7073DC15282700D4816CE1C29709DDAB6360137F62BA01932E052D8905AC5E62100DF75C6466A8D2415DA4FE266DA110C8939AD67E38F46972E3A0280A386E37100C38CF27679B7F194AE87C37A5DC3BF7AB9050DDA89F69B47725A48F0D21AD5C2705E2506ABDCF"
(TPL) IV ED146390821301023A3A3A3A3A3A3A3A
(TPL) decrypted  "15B59F26BA8DA23077847AE302E3B98BB148F546A2133505705DB49A4076B27E4CE774A2168A0A1ECBF0D32A22A316ED6EB0A21822EF8CEDD88E1E39563D3D27CD4A9580A22F21704136170AB6C6C700AFDE32F792A8A153E986023242CF2883C2FBFD2B6B47736EB2757EA14950C69AB8DAC7BF0F1D4107CB18E082047D8B00F16000C264C58771E5AE93A181B02B97149949525C965DB13D472AB2B0EE59A6B6AA205E929529606BFF8E92517F376C"
(wmbus) WARNING!! decrypted content failed check, did you use the correct decryption key? Permanently ignoring telegrams from id: 13829063 mfct: (EGM) Elgama Elektronika, Lithuania (0x14ed) type: Electricity meter (0x02) ver: 0x01
(telegram) TPL CI=7a ACC=3a STS=00 CFG=05b0 (AES_CBC_IV nb=11 cntn=0 ra=0 hc=0)
(meter) newly created meter (licznik_eon 13829063 auto) did not handle telegram!`

[egm.txt](https://github.com/weetmuts/wmbusmeters/files/10040259/egm.txt)
![egm](https://user-images.githubusercontent.com/65596240/202675472-a08e1ff6-1ff6-4bfb-a8ac-777e7f481473.jpg)

**Comment by BIBOLV** [comment]
Hi,
Do you have encryption key? Do you have more details about this meter, like are wmbus telegrams OMS compliant? 
I looked at meter manufacturer site but could not find this model.

**Comment by palibrzuch** [comment]
Unfortunately, I don't have a decryption key. I substitute the standard 32x0.
I also added a second counter without the decryption key.

Logs below.
Unfortunately, I cannot find any information about this counter.
I wrote to the operator for read access - impossible.



https://wmbusmeters.org/analyze/1E44ED146390821301027A740010052BF31A1A50A8402ABD4BB61316E6F319

(meter) licznik_eon2: for me? 13829220 in 13829063
(meter) licznik_eon2: not for me: not my id
(wmbus) telegram from 13829220 ignored by all configured meters!
(rtlwmbus) checkRTLWMBusFrame "T1;1;1;2022-11-22 08:35:32.000;48;11;13829220;0x1e44ed142092821301027a640010052c3f95ce1c88c37e4c55692af78e970a<0A>"
(rtlwmbus) received full frame
(wmbus) skipping already handled telegram leng=31.
(serial) received ascii "T1;1;1;2022-11-22 08:35:32.000;98;95;13829063;0x1e44ed146390821301027a740010052bf31a1a50a8402abd4bb61316e6f319<0A>T1;1;1;2022-11-22 08:35:32.000;82;94;13829063;0x1e44ed146390821301027a740010052bf31a1a50a8402abd4bb61316e6f319<0A>"
(rtlwmbus) checkRTLWMBusFrame "T1;1;1;2022-11-22 08:35:32.000;98;95;13829063;0x1e44ed146390821301027a740010052bf31a1a50a8402abd4bb61316e6f319<0A>T1;1;1;2022-11-22 08:35:32.000;82;94;13829063;0x1e44ed146390821301027a740010052bf31a1a50a8402abd4bb61316e6f319<0A>"
(rtlwmbus) received full frame
(wmbus) parseDLL @0 31
(wmbus) parseELL @10 21
(wmbus) parseNWL @10 21
(wmbus) parseAFL @10 21
(wmbus) parseTPL @10 21
(meter) licznik_eon: for me? 13829063 in 13829063
(meter) licznik_eon: yes for me
(meter) licznik_eon(1) auto  handling telegram from 13829063
(meter) licznik_eon 13829063 "1E44ED146390821301027A740010052BF31A1A50A8402ABD4BB61316E6F319"
(wmbus) parseDLL @0 31
(telegram) DLL L=1e C=44 (from meter SND_NR) M=14ed (EGM) A=13829063 VER=01 TYPE=02 (Electricity meter) (driver unknown!) DEV=rtlwmbus[00000001] RSSI=98
(wmbus) parseELL @10 21
(wmbus) parseNWL @10 21
(wmbus) parseAFL @10 21
(wmbus) parseTPL @10 21
(TPL) num encrypted blocks 1 (16 bytes and remaining unencrypted 0 bytes)
(wmbus) WARNING! no key to decrypt payload! Permanently ignoring telegrams from id: 13829063 mfct: (EGM) Elgama Elektronika, Lithuania (0x14ed) type: Electricity meter (0x02) ver: 0x01
(telegram) TPL CI=7a ACC=74 STS=00 CFG=0510 (AES_CBC_IV nb=1 cntn=0 ra=0 hc=0)
(wmbus) parseDLL @0 31
(wmbus) parseELL @10 21
(wmbus) parseNWL @10 21
(wmbus) parseAFL @10 21
(wmbus) parseTPL @10 21
(meter) licznik_eon2: for me? 13829063 in 13829063
(meter) licznik_eon2: yes for me
(meter) licznik_eon2(2) auto  handling telegram from 13829063
(meter) licznik_eon2 13829063 "1E44ED146390821301027A740010052BF31A1A50A8402ABD4BB61316E6F319"
(wmbus) parseDLL @0 31
(telegram) DLL L=1e C=44 (from meter SND_NR) M=14ed (EGM) A=13829063 VER=01 TYPE=02 (Electricity meter) (driver unknown!) DEV=rtlwmbus[00000001] RSSI=98
(wmbus) parseELL @10 21
(wmbus) parseNWL @10 21
(wmbus) parseAFL @10 21
(wmbus) parseTPL @10 21
(TPL) num encrypted blocks 1 (16 bytes and remaining unencrypted 0 bytes)
(TPL) AES CBC IV decrypting "2BF31A1A50A8402ABD4BB61316E6F319"
(TPL) IV ED146390821301027474747474747474
(TPL) decrypted  "85BEDD505A8276051A1A46BDF8EEB73F"
(wmbus) WARNING!! decrypted content failed check, did you use the correct decryption key? Permanently ignoring telegrams from id: 13829063 mfct: (EGM) Elgama Elektronika, Lithuania (0x14ed) type: Electricity meter (0x02) ver: 0x01
(telegram) TPL CI=7a ACC=74 STS=00 CFG=0510 (AES_CBC_IV nb=1 cntn=0 ra=0 hc=0)
(wmbus) parseDLL @0 31
(wmbus) parseELL @10 21
(wmbus) parseNWL @10 21
(wmbus) parseAFL @10 21
(wmbus) parseTPL @10 21

**Comment by BIBOLV** [comment]
Without key it will not possible to read values.

**Comment by palibrzuch** [comment]
Obtaining such a key is unlikely to be possible. I wrote to the operator and producer. We'll see.
We won't do anything without this key?

![liczniki](https://user-images.githubusercontent.com/65596240/203539037-88a855fc-0240-497b-a0a0-a8a490b6ce7d.jpg)

**Comment by BIBOLV** [comment]
It is not possible to proceed without encryption key that would be used to decrypt telegrams and process values in them. Closing issue for now. Please reopen if you manage to get key and collect decrypted telegrams.
