### ISSUE TITLE
Decoding Flowis

### ISSUE THREAD

**Issue by vierundvierzig** [weetmuts/wmbusmeters#676]
Hello,

I have water meters from Flowis ([some datasheet](https://odczytyradiowe.pl/Katalogi/eng/LibraRS-walkby-radio-system.pdf)) and wmbusmeteres can't read it. I can clearly see signals on 868.0MHz using SDR#. I tried commands:

- rtl_433 -f 868.0M
- rtl_sdr -f 868.0M -s 1600000 - 2>/dev/null | rtl-wmbus/build/rtl_wmbus
- wmbusmeters auto:c1,t1

but there is no signals from Flowis.

Can you point me what should I do to start new driver's decoding process?

Many thanks!

**Comment by BIBOLV** [comment]
You can try different frequencies and just use rtl_sdr|rtl_wmbus like this:

rtl_sdr -f 868.95M -s 1600000 - 2>/dev/null | rtl_wmbus -p s

Move up/down from the proper frequency using steps of 0.05.

**Comment by vierundvierzig** [comment]
Thank you BIBLOV for your response.

Unfortunately, no result. I even moved freq by 0.02.

Can I record somehow this signals (I can see them on SDR #) for further investigation? 

PS. It only transmits from Monday to Friday, 7-15.

**Comment by BIBOLV** [comment]
Hi,
Did you manage to get signal?

**Comment by vierundvierzig** [comment]
Hello,
unfortunately no, I have no idea where to start. I will really appreciate if you point me some tutorials or tips.
Thank you!

**Comment by BIBOLV** [comment]
There is one more open [issue](https://github.com/weetmuts/wmbusmeters/issues/713)  mentioning similar meter as your. Does your meter also has OMS marking? I did a quick search about this module and did not find that wmbus would be mentioned anywhere, just lora.

**Comment by vierundvierzig** [comment]
No, there is no OMS marking, take a look at the picture (black cable is for external antenna):

![20230109_003434](https://user-images.githubusercontent.com/58276948/211224718-22414022-b251-4179-8e56-6313e2556e9a.jpg)

**Comment by BIBOLV** [comment]
It could be then that those modules are not using wmbus but lora or some other protocol. That could be why see activity in freqency but nothing when looking for wmbus. You can try to talk to [them](https://metering.com.pl/oferta/doradztwo-techniczne/) as they are manufacturers if I'm not mistaken. Or try to find some written confirmation that wmbus is being used. Or, if in picture are your old modules, try to disassemble them and look at some chips, it could give maybe some hints what is being used there.

**Comment by vierundvierzig** [comment]
I have TTGO Lora, tried today but no success - no messages on LoRa and FSK modulation.
I can not disassemble them.
Still looking how to recognize signal.

**Comment by vierundvierzig** [comment]
Manufacturer said that it is closed protocol and it's impossible to understand it without source code.... Anyway :)

I can spot the signal on spectrogram:
![1](https://user-images.githubusercontent.com/58276948/212547613-893b00dc-dc83-4792-ae31-e004598dcf78.jpg)
As you can see, it is very short and I think it is FSK modulation. Any new ideas?

**Comment by BIBOLV** [comment]
I would bet on lora as it does not make sense to create new protocol in times when there are so many already created, but that`s just my guess.

**Comment by vierundvierzig** [comment]
Do you have any guess how to decode it?

**Comment by weetmuts** [comment]
@merbanan do you have any input on a mysterious fsk radio protocol? :-)

**Comment by merbanan** [comment]
@vierundvierzig use rtl_433 and follow the https://github.com/merbanan/rtl_433/blob/master/docs/ANALYZE.md instructions. This device is highly likely not wmbus compatible and then you are welcome over to the rtl_433 project for support.

**Comment by vierundvierzig** [comment]
Thank you very much for this link! I will follow instruction on Tuesday morning (water meter has specific time when it works) and post some result. 
Can we continue this topic here or should I open new one in rtl_433 project?

**Comment by merbanan** [comment]
Open a new issue there and then add a link to it from here.

**Comment by vierundvierzig** [comment]
Topic will be continued [here](https://github.com/merbanan/rtl_433/issues/2317). Thank you very much for help!

**Comment by merbanan** [comment]
So far we know that the Flowis protocol is using 100 kbps FSK with a 200 bit message excluding the preamble. It is not compatible with anything wmbus. Hopefully it will be added to the rtl_433 project if we get enough sample messages to analyse.

**Comment by merbanan** [comment]
This device is now supported in the rtl_433 project.
