### ISSUE TITLE
NexMeter Gas Meter support - 169 Mhz N mode

### ISSUE THREAD

**Issue by optiluca** [weetmuts/wmbusmeters#677]
Hi.  My gas meter appears to be a 169 Mhz N mode device (this seems to be the case for every gas meter in my area).

![20221119_163917](https://user-images.githubusercontent.com/1837843/202892246-49e584f1-03a9-4708-9697-e0dae0fdf394.jpg)

I see quite a few issues regarding support for devices on this band, but none seem to have been resolved.

I have an rtl-sdr,  patience, but no competence. :-)  What should I do to gather data to allow for this device to be supported?

Does it make sense to keep this ticket open, or should I chime in an already-existing one, for a different 169 Mhz N mode device?

Thanks!

**Comment by BIBOLV** [comment]
Hi,
Firstly support for N must be implemented in rtl_wmbus, so if you can, you can record some signal samples and post them [here](https://github.com/xaelsouth/rtl-wmbus/issues/26).
You can close this issue for now and open once more when support in rtl_wmbus is implemented and we can move forward.

**Comment by optiluca** [comment]
OK, thanks.  I'll try recording some data and posting it on the rtl_wmbus issue.

**Comment by weetmuts** [comment]
Note that there is a 169MHz hardware dongle that works with wmbusmeters: amb3665
(Search for Amber AMB 3665-M)
Make sure you buy a matching suitable antenna as well.
