### ISSUE TITLE
Feature request: Decrypt Mode 7

### ISSUE THREAD

**Issue by cinemarene** [weetmuts/wmbusmeters#71]
Can you please implement Mode 7 decryption? I need it for an Energy Meter.

If it helps, the SmartHome solution ioBroker has it already implemented:
https://github.com/ISFH/ioBroker.wmbus/blob/4fce68c57f915840c787f1d3df1194aae5afc56e/lib/wmbus_decoder.js

Here is the documentation of it: https://oms-group.org/fileadmin/files/download4all/specification/Vol2/4.0.2/OMS-Spec_Vol2_Primary_v402.pdf
how to do.
Page 52 => 9.2.3

**Comment by weetmuts** [comment]
Actually it is already implemented. :-) Please test!

**Comment by cinemarene** [comment]
Thanks for the quick feedback. I did not know that because I tested it yesterday and it did not work. I couldn't find anything in the code either. Maybe I did something wrong. I will test it again today and tell you about it.

**Comment by weetmuts** [comment]
Email me the key and I can test your telegram.

I am sure that there are things that still can go wrong.
