### ISSUE TITLE
Support DIEHL Sharky 774 ?

### ISSUE THREAD

**Issue by chpego** [weetmuts/wmbusmeters#744]
Hi,
I'm using wmbusmeters with HA; thank's for the addon. For 3 water meters, everything work's like a charm.
For a heat cooling load meter DIEHL (sharky774), i've this message :

```
(meter) Gaz: meter detection did not match the selected driver sharky774! correct driver is: unknown!
(meter) Not printing this warning again for id: 71942539 mfct: (DME) DIEHL Metering, Germany (0x11a5) type: Heat/Cooling load meter (0x0d) ver: 0x41
(meter) please consider opening an issue at https://github.com/weetmuts/wmbusmeters/
(meter) to add support for this unknown mfct,media,version combination
```

**Comment by BIBOLV** [comment]
Hi,
Please log some decrypted sample telegrams and post them here.

**Comment by chpego** [comment]
Hi @BIBOLV 
i don't know, is that enough?
``
telegram=|5E44A51139259471410D7A720050052F2F_0C06742400008C1006000000000C13823522008C2013494400000B3B0000000C2B000000000A5A22030A5E91020AA61800004C0619130000CC100600000000426CDF252F2F2F2F2F2F2F2F2F2F2F|+47044
``

**Comment by BIBOLV** [comment]
Can you check if those values are correct?
```

{
    "media":"heat/cooling load",
    "meter":"kamheat",
    "name":"",
    "id":"71942539",
    "status":"OK",
    "total_energy_consumption_kwh":2474,
    "total_volume_m3":223.582,
    "volume_flow_m3h":0,
    "power_kw":0,
    "t1_temperature_c":32.2,
    "t2_temperature_c":29.1,
    "target_energy_kwh":1319,
    "target_date":"2022-05-31",
    "timestamp":"2022-12-19T12:18:24Z"
}
```

**Comment by chpego** [comment]
Thanks @BIBOLV 
But my meter is a Sharky 774, not a **kamheat**.

There is just this warning message for the driver, but all the rest of the information is well recovered

**Comment by BIBOLV** [comment]
Yes, sorry, you are correct. Existing sharky774 driver also decodes most of values. Some values are not decoded and I guess those are for cooling.

**Comment by snapspizza** [comment]
Hi @BIBOLV. Just a note, if @chpego confirms that the values in your example above is correct, he will get incorrect values if he switches to the sharky774 driver. This is because of the changes made in #689, where the input value of total energy consumption was changed to MJ instead of kWh. As discussed in the thread in connection with #689, it seems that the meter can be set up to send data with different input units. It would be nice if the driver could be optimized to take this into account, maybe based on the information given in the telegram on line 18 in the 0E value.

**Comment by chpego** [comment]
Hi all,
I bring a precision on the fact that the current meter, is used to measure/capture a floor heating:
![image](https://user-images.githubusercontent.com/38792705/208606466-2487fc45-65aa-40ab-96f6-463d7b0f58d4.png)

Best regards,

**Comment by snapspizza** [comment]
Hi @chpego. Is the correct total_energy_consumption_kwh value 2504 or 695.555556? It should correspond to what is shown physically on the display on your unit.

**Comment by chpego** [comment]
Hi @snapspizza , you're right, the correct value is 2504

**Comment by snapspizza** [comment]
Thanks for the confirmation @chpego. I think I will create a separate issue regarding the incorrect values, as it is not directly related to your issue of correct meter and driver identification.

**Comment by chpego** [comment]
Thanks !

**Comment by weetmuts** [comment]
Thank you @chpego @snapspizza and @BIBOLV 

The sharky774 driver was indeed buggy in relation to MJ and KWH!!!! I have rewritten it using the latest driver format which makes it impossible to do the same mistake. :-)

@chpego please verify that it decodes correctly:
https://wmbusmeters.org/analyze/5E44A51139259471410D7A720050052F2F0C06742400008C1006000000000C13823522008C2013494400000B3B0000000C2B000000000A5A22030A5E91020AA61800004C0619130000CC100600000000426CDF252F2F2F2F2F2F2F2F2F2F2F

**Comment by chpego** [comment]
> Thank you @chpego @snapspizza and @BIBOLV 
> 
> The sharky774 driver was indeed buggy in relation to MJ and KWH!!!! I have rewritten it using the latest driver format which makes it impossible to do the same mistake. :-)
> 
> @chpego please verify that it decodes correctly:
> https://wmbusmeters.org/analyze/5E44A51139259471410D7A720050052F2F0C06742400008C1006000000000C13823522008C2013494400000B3B0000000C2B000000000A5A22030A5E91020AA61800004C0619130000CC100600000000426CDF252F2F2F2F2F2F2F2F2F2F2F
> 
> 
> 

Seems to be good 💪

**Comment by snapspizza** [comment]
Thank you for the fix @weetmuts. I just update to the latest version of wmbusmeters, and everything seem to work as expected now.

**Comment by BIBOLV** [comment]
Closing as solution was provided.
