### ISSUE TITLE
Suggestion : Check if rtl_sdr / rtl_wmbus exist

### ISSUE THREAD

**Issue by anonymous-one** [weetmuts/wmbusmeters#79]
I know there are probably many things that need to be done before something of this nature, but a small suggestion:

For someone playing with sdr for the first time, check to see if the rtl_sdr / rtl_wmbus binaries exist, if not, show something in the error logs. Currently its silent.  Once again, this is just for those of us who do not know about the rtl_sdr / rtl_wmbus binaries being required.

I know, fairly elementary... But besides this, the daemon spawned up without ANY issues on my RPI3B+ running Stretch.

**Comment by weetmuts** [comment]
Actually, I just pushed a fix for this yesterday. :-)

When starting wmbusmeters as a daemon it will check
that /usr/bin/rtl_sdr and /usr/bin/rtl_wmbus exists.
If not found, an error is printed in the wmbusmters.log file
before exiting.

When starting from the command line it uses the PATH
to find the binaries, so no such check is done.

**Comment by anonymous-one** [comment]
:)
