### ISSUE TITLE
Cannot install Addon in HAOS 2023.2.0

### ISSUE THREAD

**Issue by cococheaf** [weetmuts/wmbusmeters#836]
### Type of request

Bug

### HAOS version

2023.2.0

### wmbusmeters version

1.11.0

### Your message goes here

Hi, cannot install the addon, see the error in the screenshot. Any ideas ablut that? Thank you.

![FB99FAC4-334F-4BEB-AA5B-21CF4D6AEEDB](https://user-images.githubusercontent.com/54749655/216403530-66db8da6-878b-42aa-a64c-952355c21206.png)

**Comment by BIBOLV** [comment]
Please check https://github.com/weetmuts/wmbusmeters/issues/769 if suggested solution helps you.

**Comment by cococheaf** [comment]
> Please check #769 if suggested solution helps you.

Thank you - that was the problem.
Changed the DNS and then it installed.
