### ISSUE TITLE
Addon configuration expects meters as string, instead of JSON

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [weetmuts/wmbusmeters#837]
### Type of request

Bug

### HAOS version

9.5

### wmbusmeters version

1.11.0

### Your message goes here

Freshly installed wmbusmeters addon, `mqtt` section looks like proper code input field, but `conf` and `meters` sections expect strings.  
`conf` has to be prepared in external editor, with `\n` at end of each line, then compressing it to single line to paste it here.  
What's worse, `meters` is a drop-down, not input.  
This renders configuring wmbusmeters not possible.
![Screenshot 2023-02-03 at 13-23-44 Home Assistant](https://user-images.githubusercontent.com/24268470/216603269-c51abdb0-ebd7-4e40-8660-2bcc1178525a.png)

**Comment by KrzysztofHajdamowicz** [comment]
Quick look at Firefox Developer tools, mqtt section is declared as `<ha-code-editor mode="yaml" />`, where conf section was declared as `<input class="mdc-text-field__input" type="text" />`

**Comment by KrzysztofHajdamowicz** [comment]
I had some spare time and solved this via #838 .
Please, can you merge it with upstream?

**Comment by BIBOLV** [comment]
PR merged. Tnx!
