### ISSUE TITLE
Add-on store doesn't contain repository

### ISSUE THREAD

**Issue by dula34** [weetmuts/wmbusmeters#855]
### Type of request

Bug

### HAOS version

2023.2.4

### wmbusmeters version

Latest

### Your message goes here

I have add-on repository in repository list, but add-on store doesn't contain section with this add-on. I tried restart HA, clear cache.
Device: rpi4

**Comment by thecem** [comment]
if you have this:

![grafik](https://user-images.githubusercontent.com/46648579/218945125-17e6c351-630f-4e99-b92e-5ac967cdb2ff.png)

the hit update and then clear the cache. Reload the page with strg+F5.

This is a home assistant problem, not related to wmbusmeters.

**Comment by dula34** [comment]
<img width="497" alt="image" src="https://user-images.githubusercontent.com/11034597/218947128-91407868-d49d-45a4-8549-e024d01258c7.png">
I tried without success.
I also add another repository and worked, but this one not

**Comment by thecem** [comment]
I will test this today night, if this is working on a new system.

**Comment by dula34** [comment]
thx, btw I did clean install latest version HA on RPI3 with same result.

**Comment by chpego** [comment]
![image](https://user-images.githubusercontent.com/38792705/218994696-28ba71b0-e922-46e5-90a0-4568d60afd81.png)

**Comment by dula34** [comment]
It works after merge PR, thanks all for quick fix
