### ISSUE TITLE
json configuration files missing

### ISSUE THREAD

**Issue by jammedjackal** [weetmuts/wmbusmeters#879]
### Type of request

Enhancement

### HAOS version

9.5

### wmbusmeters version

1.11.0-2

### Your message goes here

I'm trying to add 2 water meters and 1 heat meter with mqtt_discovery, but receive in logs following error messages:

File /config/wmbusmeters/etc/mqtt_discovery/vario451.json not found.
File /config/wmbusmeters/etc/mqtt_discovery/mkradio4.json not found.

Would it be possible to add those json's configs to next release?

**Comment by BIBOLV** [comment]
@chpego created two mentioned templates and PR was merged. Thanks! Closing issue.
