### ISSUE TITLE
Lansen pulse meter telegram

### ISSUE THREAD

**Issue by merbanan** [weetmuts/wmbusmeters#90]
time      : 2020-03-03 18:44:04
model     : Wireless-MBus Mode      : T            Manufacturer: LAS         ID        : 23716
Version   : 20           Device Type: 0x00         Device Type String: Other Control   : 0x44          Data Length: 36
Data      : 234433301637020014007a8e0000002f2f0efd3a0000000000008e40fd3a000000000000                   Integrity : CRC
Control Info: 0x7A       Access number: 0x8E       Device Type: 0x00         Configuration Word: 0x0000 Counter 0 : 0

`[0e] [fd3a] 000000000000 [8e40] [fd3a] 000000000000` 

Two counters are present.

**Comment by weetmuts** [comment]
Thanks for the telegram! Pushed support for lansenpu as a pulse counter.
