### ISSUE TITLE
B METERS RFM-TX1 support?

### ISSUE THREAD

**Issue by trockenasche** [weetmuts/wmbusmeters#96]
Does anybody know if the [RFM-TX1 from B METERS](https://www.bmeters.com/en/bm_product/rfm-tx1/) will be working?
Unfortunately I don't have this device.

**Comment by weetmuts** [comment]
Well, they have the OMS mark on their web-page. So hopefully it should be OMS-compliant and not send proprietary data inside the wmbus protocol. 

We still need to have a few telegrams from the device to add it to wmbusmeters, but
if OMS-compliant, then it should be easy.

**Comment by trockenasche** [comment]
Thanks.

**Comment by bbiegun** [comment]
@trockenasche BMaters contains proprietary data, but is seems to be readable now :) Check #101 for updates.
